software-mansion/radon-ide

packages/docs/src/components/Sections/Overview/index.tsx
To remove warning of lack of 'key' use we added one.
=> Add key for overview items

packages/vscode-extension/src/project/project.ts
Tested by editing is-number package in the node_modules directory.
=> Check fingerprint on save when editing node_modules

packages/vscode-extension/src/builders/buildIOS.ts
Should help in debugging issues related to iOS build.
=> Add warning when multiple XCode project files are found

packages/vscode-extension/scripts/build-sim-server.sh
This PR pulls in new version of sim-server that includes https://github.com/software-mansion-labs/simulator-server/pull/163
The linked PR significantly improves the performance of streaming bringing CPU usage down for both the receiving end (panel) and the server on its own. From initial testing it shows:
- 40-50% less CPU usage on the renderer (IDE panel)
- 80% less CPU usage on the server when streaming iOS simulator
- 60% less CPU usage on the server when streaming Android emulator
On top of the above, this commit also includes some changes to the sim-server build script that allows us to build modified version of sim-server repo using build command. Before this change, when making modifications to stream-server submodule, the script would check out the version that's set in the parent …
=> Update sim-server to version that includes significant perf improvements

packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts
This PR gets rid of the onboarding modal that pops up with expo-dev-client apps after launch.
Since the modal is blocking JS looper, it prevents the app from establishing devtools connection which may lead to timeouts and hence prevent "app ready" events. As a consequence, the IDE fails to recognize the app is properly launched.
Before, we've been using `disableOnboarding` flag passed as URL parameter when launching the app. However, it appears like it's never worked properly (see this fix here: https://github.com/expo/expo/pull/29697). For the time being we decided to use an alternative approach in which we write onboarding parameter into shared props that are used to store the information whether the popup should be displayed or not.
=> Use shared-prefs to avoid onboarding screen that blocks the UI in expo dev client

packages/vscode-extension/src/builders/buildIOS.ts
We allowed only one result from the xcworkspace or xcproj. Those directories may contain more than one file so now we check if found files are from the same directory.
Fixes #388.
=> Fix iOS workspace resolution

packages/vscode-extension/lib/wrapper.js
When measuring any stack's frame fails, we catch the error and return undefined. It wasn't handled when we were filtering out frames without source information.
=> Fix inspector promise crash

packages/vscode-extension/src/project/project.ts
This PR fixes the logic behind the flag responsible for tracking fingerprint changes.
Before, we'd set the flag after detecting finger print updates. Then we'd only reset it back after project launches successfully. The issue with this approach was that despite the build would finish, we may have still got a failure when launching resulting in that flag never getting reset. As a result, all subsequent restarts would rebuild the app from scratch. To address this, we're making the following updates:
1. We're resetting the flag upon successful build and not only after the whole restart procedure is completed.
2. We're changing restart logic such that when flag is set we don't force clean build. It is enough to only perform device selection step as it will trigger the build and in case …
=> Clean fingerprint change flag upon succesfull build

packages/vscode-extension/src/builders/BuildManager.ts, packages/vscode-extension/src/builders/buildIOS.ts, packages/vscode-extension/src/dependency/DependencyManager.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/views/DiagnosticView.tsx
This PR completes Enhanced build pipeline, by improving how pods are detected and installed. 
resolves: #452
=> Enhance build pipeline - install pods automatically

packages/vscode-extension/.vscode/launch.json, packages/vscode-extension/package-lock.json, packages/vscode-extension/scripts/build-sim-server.sh
This PR updates the `simulator-server` submodule to use the new implementation of the simulator server and adjusts the build script accordingly.
=> Switch to new simulator server

packages/vscode-extension/lib/wrapper.js
This PR fixes a bug that was caused by PREVIEW_APP_KEY not being imported. 
This caused the following error: 
```
Cannot read property 'PREVIEW_APP_KEY' of undefined
=> Fix Preview 

packages/vscode-extension/src/webview/components/DeviceSettingsDropdown.tsx, packages/vscode-extension/src/webview/components/IconButtonWithOptions.tsx
This PR adds keys to lists in DeviceSettingsDropdown and IconButtonWithOptions to prevent error messages.
=> Fix lists without key prop errors

packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts, packages/vscode-extension/src/devices/IosSimulatorDevice.ts, packages/vscode-extension/src/devices/preview.ts
This PR changes the commands that are sent to simserver to comply with new format.
=> Adjust for new simserver CLI, update simserver submodule

packages/vscode-extension/src/builders/BuildManager.ts
=> Fix typo in fix for iOS build cycles

packages/vscode-extension/src/dependency/DependencyManager.ts
This PR fixes a mistake in condition checking if android and ios directories are optional.
=> Fix wrong Condition

packages/vscode-extension/src/builders/BuildManager.ts
This fixes a bug introduced in #615 that was causing Android rebuilds when pod check was failing.
In #615 we added a cocoapods check before starting a native build, which was then used as an additional indicator of when we should rebuild (when check was failing we'd clean build cache). This check however only makes sense for iOS builds. And in the scenario when pods aren't yet installed and you try to build for Android, it was causing native rebuilds every time.
The change here is to make the check only when building for iOS.
We're also adding some additional logs that should indicate the native build reason better in the logs.
1. Checkout clean copy of expo-51-dev-client
2. Open it for Android at first
3. Restart IDE card and see it no longer performs native build. Before this change, …
=> Only consider pods check when building for iOS

packages/vscode-extension/src/webview/components/DeviceSelect.css, packages/vscode-extension/src/webview/components/DeviceSelect.tsx, packages/vscode-extension/src/webview/components/shared/Dropdown.css
This PR adds scrollbars to the `device select` and the `device settings` dropdown.
- Added a large number of devices to extend the device list, then reduced the window heigh to test the scrollbar in the device select.
- Opened the device settings to verify that the scrollbar operates as expected.
after:
https://github.com/user-attachments/assets/144a1d58-9a74-4d1b-b61b-61455c026052
=> Add scrollbars to device select and device settings

packages/vscode-extension/package-lock.json, packages/vscode-extension/package.json
Bumping extension version to 0.0.22 and also updating simulator-server to latest 0.5.0 version.
=> Bump version -> 0.0.22

packages/vscode-extension/src/webview/components/shared/Select.css
This PR fixes the invisible hover and cursor pointer issue in components using Select (CreateDeviceView, LaunchConfigurationView).
Before:
After:
=> Fix hover issue in components using Select

.github/workflows/lint-extension.yml, .github/workflows/typecheck-extension.yml
This should cancel stale actions. Hopefully, it will reduce the queue for runners if we skip the unnecessary ones.
=> chore: cancel stale workflows

packages/vscode-extension/lib/preview.js
This PR fixes an issue when changes made to `preview` component directly wouldn't trigger UI updates.
The reason why this wasn't happening is due to the limitation of fast-refresh, which, when happens, replaces the implementation of the previous component. As a consequence, the root Preview component doesn't see the previewed one got updated.
In this PR we're adding `renderTrigger` callback that the root Preview component uses to register for updates in the preview map. When registering the preview, we check if a one already exists, and trigger update for it.
Caveat: note that with this approach the root component that is used by the preview won't persist state. I don't see how can we workaround this, but it doesn't seem too limiting at this point.
Fixes #725
1. Run expo-router example, …
=> Rerender preview if its function changes

packages/vscode-extension/src/project/metro.ts
This PR fixes issue with Expo Go on SDK 52 where the new debugger is enabled.
The issue there is that new debugger lists two hermes runtimes, one is used by the Expo Go shell, and the second one is used by the actual app. The fix is to detect that Expo Go is used with the new debugger, and in such case select second runtime from the list instead of the first one.
Note: While this PR fixes the debugger connection and the console logging mechanism, the breakpoints are still non-functional. This is due to the fact that expo go bundle doesn't use file path aliases ([metro-projectRoot] etc)
1. Use this reproducer repository which is an Expo Go SDK 52 project: https://github.com/friyiajr/debugger-reproducer
2. Run app and click the only button that's there
3. See logs in the console
=> Fix Expo Go on SDK 52 by selecting the right hermes runtime when connecting debugger

packages/vscode-extension/package-lock.json
This is a simple type dependency bump
=> Bump version of vscode API types

packages/docs/docs/getting-started/compatibility.md, packages/docs/docs/getting-started/overview.md, packages/docs/docs/guides/troubleshooting.md, packages/docs/src/components/Compatibility/index.tsx, packages/docs/src/components/Compatibility/styles.module.css, packages/docs/src/components/Pricing/CompatibilityInfo/index.tsx, packages/docs/src/components/Pricing/CompatibilityInfo/styles.module.css, packages/docs/src/components/Pricing/index.tsx, packages/docs/src/css/colors.css, packages/docs/src/css/overrides.css, packages/docs/vercel.json
https://radon-ide-git-kacperkapusciak-add-avail-de89a8-software-mansion.vercel.app/docs/getting-started/compatibility
=> Add compatibility page

packages/vscode-extension/src/webview/views/ActivateLicenseView.css, packages/vscode-extension/src/webview/views/ActivateLicenseView.tsx
This PR removes a scrollbar from activate license view and improves the default message the user sees after opening the modal.
- run IDE and see how it looks
https://github.com/user-attachments/assets/88b2da08-505b-4467-9410-9d4ea9ce7aa7
=> Fix Styling of ActivateLicenseView

packages/docs/src/components/Pricing/CompatibilityInfo/index.tsx, packages/docs/src/components/Pricing/CompatibilityInfo/styles.module.css, packages/docs/src/components/Pricing/PricingCard/pricing.module.css, packages/docs/src/components/Pricing/PricingPlansList/index.tsx, packages/docs/src/components/Pricing/PricingPlansList/styles.module.css, packages/docs/src/components/Pricing/index.tsx, packages/docs/src/components/Pricing/styles.module.css
https://github.com/user-attachments/assets/aeb95f4f-b95b-4d9c-9057-ef3867cacea3
=> Update pricing page

packages/docs/src/components/Pricing/CompatibilityInfo/styles.module.css
=> Fix mobile styles of compatibility info in pricing

packages/docs/docusaurus.config.js
=> Add announcement bar for Radon IDE launch on Product Hunt

packages/docs/src/components/Hero/StartScreen/index.tsx, packages/docs/src/components/HomepageButton/index.tsx, packages/docs/src/components/LearnMore/LearnMoreFooter/index.tsx, packages/docs/src/components/Pricing/CompatibilityInfo/index.tsx, packages/docs/src/components/Pricing/PricingPlansList/index.tsx, packages/docs/src/hooks/usePaddle.tsx
This PR adds more granular analytics which will enable us to make better informed decisions about the product:
**Landing page**
- `Download` button click
-  `See video` button click
**Pricing page**
- `See compatibility` button click
- Checkout events
- `checkout.loaded`
- `checkout.closed`
- `checkout.completed`
- `checkout.error`
Implemented thanks to https://vercel.com/docs/analytics/custom-events
=> docs: add better analytics

packages/docs/docs/guides/configuration.md
I thin this is some leftover as it doesn't make sense with the rest of the paragraph.
=> Fix the option name

packages/docs/docs/guides/troubleshooting.md
you know it had to happen eventually
=> Fix typo in troubleshooting.md

packages/docs/docs/getting-started/compatibility.md
This update updates information about PNPM workspaces compatibility to the `compatibility.md` file.
=> Update PNPM compatibility in docs

packages/docs/docs/guides/keyboard-shortcuts.md
This PR updates keybindings docs after #875 and adds descriptions to Unassigned actions.
- local dev build 
- vercel preview
=> Update Keybindings docs

packages/vscode-extension/src/webview/Preview/Device.tsx, packages/vscode-extension/src/webview/Preview/DeviceFrame.tsx, packages/vscode-extension/src/webview/Preview/MjpegImg.tsx, packages/vscode-extension/src/webview/Preview/hooks.ts, packages/vscode-extension/src/webview/components/Preview.tsx
Mini refactor that extracts some components to separate files. For now it's a bit weird that we're moving it to Preview, but my goal is to split entrie Preview.tsx in small chunks in Preview folder. 
Nothing should changed
=> Refactor: extract some some components from Preview 

packages/vscode-extension/src/debugging/CDPSession.ts, packages/vscode-extension/src/debugging/DebugAdapter.ts
This PR fixes a problem with debugger infinitely awaiting for variable from cdp, blocking the whole debugger process in consequence. The solution is to add a time out to the function that fetches the properties and return empty variable list if it passes. 
- add a `console.log(devtoolsAgent)` somewhere in `RNIDE_inspect` section of wrapper.js
- click through returned object before the change the `_persistedSelection` filled would load infinitely after it stops awaiting after 3 s.
=> Fix infinite loading when cdp does not return a variable

packages/vscode-extension/src/webview/components/shared/IconButton.css, packages/vscode-extension/src/webview/styles/theme.css
This PR inverses the colors, so the log counts are more visible. 
<video src="https://github.com/user-attachments/assets/d55d3e54-22c1-4bb4-b0e6-4f6dc1588dd4" />
- Run Radon IDE and see :))
=> Improve contrast of log counter

packages/vscode-extension/lib/network.js
In #933 we added network devtools panel integration. The implementation relied on WeakRefs to keep references to XHR objects that can later be queried by the network panel. However, WeakRefs aren't supported across all versions/configurations in RN.
This PR introduces an alternate implementation that clears up the references to XHR after 3minutes. This is needed such that we don't keep all the network requests in memory forever. We also make a change here that removes the kept object as soon as the details about the request are fetched. This will allow us to cleanup the refs as soon as the UI panel fetches the request body details.
1. Test fetch with expo-51 and expo-52. Add console.log to make sure the alternate implementation is only used in the former.
2. Before this change, fetches …
=> Add alternative implementation for WeakRefs for RN versions that doesn't support WeakRefs

packages/vscode-extension/src/debugging/BreakpointsController.ts, packages/vscode-extension/src/panels/SidepanelViewProvider.ts, packages/vscode-extension/src/project/metro.ts
=> chore: fix some typos

packages/vscode-extension/src/plugins/react-query-devtools-plugin/ReactQueryDevToolsPluginWebviewProvider.ts
This PR adds telemetry to react-query devtools plugin. Similarly like for other plugins in https://github.com/software-mansion/radon-ide/pull/974.
- Run expo-52-prebuild-with-plugins 
- Make sure react-query works by enabling it and inreasing counter on seccond tab 
- Restart the app and retest counter
- Restart the pluign and retest counter
- In all cases react-query devtools should work
=> Add telemetry to react-query

packages/vscode-extension/package.json, packages/vscode-extension/src/webview/views/LaunchConfigurationView.tsx
Updates the description of the "Auto" option for EAS build id in the lauch config dialog.
=> update "Auto" description for eas build id

packages/vscode-extension/.vscode/tasks.json
=> Fix Extension Development Host failing to start again

packages/vscode-extension/src/debugging/CDPSession.ts
After a JS Reload is triggered, in the new Hermes debugger implementation the breakpoints remain set, but our CDP implementation discards the source maps. This can cause a breakpoint to be hit before the source maps are loaded by the debugger, resulting in the IDE trying to display the unmapped source (as shown in the screenshot:)
This PR waits for the source maps to load before displaying the breakpoint to the user, which avoids the issue
- launch an app
- set breakpoints such that they will be hit soon after loading the bundle
- trigger a JS Reload
- verify that the IDE displays the position in the source code where the breakpoint was set
=> wait for sources before jumping to breakpoint

packages/docs/src/components/Hero/StartScreen/index.tsx, packages/docs/src/components/Hero/StartScreen/styles.module.css
=> docs: update the main H1 on landing

packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/metro.ts
Alternative solution for #1132 
This PR fixes an issue with how launch completion was reported that prevented users from using preview functionality in the following scenario:
- cause a bundle error 
- try to reload in that state 
- fix the bundle error 
- run auto-reload 
- now the app is launched but `isLaunching` prop is set to `true`
run the reproduction and check if it works
=> Fix Radon thinking the app is stuck launching after bundle error

packages/docs/docs/guides/keyboard-shortcuts.md
Updates docs to reflect the changes from #1144
=> update docs with new default keybinding

packages/vscode-extension/package-lock.json, packages/vscode-extension/package.json
This PR bumps the package version before release.
=> Bump package version to 1.7.0

packages/docs/docusaurus.config.js, packages/docs/src/components/ArrowRightSmallIcon/index.tsx, packages/docs/src/components/Contact/index.tsx, packages/docs/src/components/ContactCard/index.tsx, packages/docs/src/components/ContactCard/styles.module.css, packages/docs/src/components/FlagIcon/index.tsx, packages/docs/src/components/MailIcon/index.tsx, packages/docs/src/components/MessageIcon/index.tsx, packages/docs/src/components/UserIcon/index.tsx, packages/docs/src/pages/contact.module.css, packages/docs/src/pages/contact.tsx
This PR adds a new `/contact` page
=> docs: add a Contact Us page

packages/vscode-extension/src/project/DeviceSessionsManager.ts
Adds a warning notification when more than a certain number of emulators (>3 iOS or >1 Android) are running at the same time.
- open Radon
- launch 2 Android devices
- a warning should appear
- stop one of the devices
- open 4 iOS devices
- a warning should appear
=> warn the user when many devices are running concurrently

packages/docs/src/theme/Navbar/index.js, packages/docs/static/js/reddit-pixel.js
This PR adds Reddit Pixel according to [the Reddit documentation](https://business.reddithelp.com/s/article/Install-the-Reddit-Pixel-on-your-website) for marketing visibility purposes.
Pixel is turned off during development.
=> docs: add Reddit Pixel

.github/pull_request_template.md
This PR aims to improve our process of documenting new features or UI changes. By forcing the creator of the PR to link the relevant docs updates in the PR description.
=> Update PR template to remaind the contributor about documentation

packages/docs/docs/guides/development.md
=> docs: document Development prerequisites

packages/vscode-extension/src/webview/providers/WorkspaceConfigProvider.tsx
This PR fixes a regression introduced in #1324, where we removed support for legacy IDE themes and by accident we removed the listeners for the whole workspace configuration, not just the themes. 
- run test app and change "show device frame" setting 
- restart extension
=> Fix workspace configuration fetching

packages/docs/docs/_changelog/1.8.x.md, packages/docs/docs/_changelog/1.9.x.md
=> docs: add 1.9 changelog

packages/vscode-extension/src/panels/WorkspaceConfigController.ts
This PR fixes a mistake in #1383
=> fix: workspace confic sync

packages/docs/docs/features/radon-ai.md
This PR documents the possibility of disabling the radon AI functionality completely.
=> docs: enable radon ai 

packages/docs/docs/_changelog/1.3.x.md, packages/docs/docs/features/dev-tools.md
Fixes https://github.com/software-mansion/radon-ide/issues/1390
=> docs: update Redux section to specify Redux Toolkit

.github/workflows/ui-tests.yaml, packages/vscode-extension-tester/data/testData.js, packages/vscode-extension-tester/package.json
This PR introduces working tests in GitHub Actions.  
These are simple smoke tests that validate basic functionality.  
- The workflow was executed in GitHub Actions on branch `@KeyJayY/GithubActions`.
- Verified that the smoke tests ran successfully and completed without errors.
- Also confirmed that tests designed to fail indeed fail
- No documentation yet
=> feat: GitHub Actions 

packages/vscode-extension/src/webview/components/RenderOutlinesOverlay.tsx
This PR fixes an issue introduces by one of our state refactors (conditional hook) 
- reload test app until it breakes 
internal
=> fix: render outlines conditional hooks

packages/vscode-extension/src/webview/components/SendFilesOverlay.tsx
Adds feedback while the webview is reading the file to be sent to the device.
=> fix: no feedback while reading file to be sent

packages/docs/docs/features/screen-recording.md
This documents changes made in #1434
Preview
=> docs: configure default multimedia saving location

packages/docs/docs/guides/configuration.md
=> docs: add information about `usePrebuild` launch config

packages/vscode-extension/src/project/FingerprintProvider.ts
This PR allows for ignoring changes that happen on another platform while developing only one of the platforms. 
- run test app on `ios` and delete something in android directory, check if the build will happen after reload. 
- then delet something from ios dir and check if it rebuild as it should 
internal.
=> feat: platform specific fingerprint 

packages/vscode-extension/lib/inspector_bridge.js, packages/vscode-extension/src/project/devtools.ts
After #1500 moved the communication channel used for React DevTools to the debugger, we've encountered issues related to devtools messages being lost for backgrounded devices, which are disconnected from the debugger (mostly to avoid UI/UX issues with multiple active debug sessions in vscode).
This PR aims to fix these issues by introducing a message retransmission mechanism to our "Inspector Bridge" implementation, which allows the extension to ask the app for the messages it missed once the debugger is reattached.
The mechanism introduces:
- an incremental `id` field to inspector bridge messages
- an `"ack"` control message sent by the extension to the application to signify i successfully received messages up to a specified `id`
- a `"retransmit"` control message which asks the …
=> fix: inspector bridge message retransmission

packages/docs/src/components/EnterpriseForm/Captcha.tsx, packages/docs/src/components/EnterpriseForm/index.tsx
This PR adds a bot protection check to the enterprise contact form to prevent potential abuse. This is a frontend implementation as the backend verification is in the works.
=> rebranding: add reCAPTCHA to enterprise contact form
