packages/docs/src/theme/Navbar/index.js
This PR enables cookieless, anonymous analytics to our website provided by `@vercel/analytics`.
=> docs: enable anonymous analytics

packages/vscode-extension/src/builders/buildAndroid.ts, packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts, packages/vscode-extension/src/utilities/common.ts
We previously used `os.arch()` which returns things like `x64` or `ia32`. QEMU understands only `x86, x86_64, arm, arm64` as arch values ([Android config.ini reference](https://learn.microsoft.com/en-us/dotnet/maui/android/emulator/device-properties?view=net-maui-8.0)).
- Replaced `os.arch()` with typed `process.arch` (doing the same).
- Mapped NodeJS arch to QEMU arch.
- Fixed RN gradle arch and ABI to handle x86 as native instead of using x86_64 there.
Fixes #302.
=> Fix AVD config using invalid CPU archs

packages/vscode-extension/src/builders/buildIOS.ts
Seems like bundler stores some gems in there we want to ignore.
Tested building and running apps on bare app, expo go, and expo dev client.
Fixes #293.
=> Ignore vendor directory when looking for XCode files

packages/vscode-extension/src/project/project.ts
Used in event listener callbacks which changes `this` env.
=> Use arrow function for removeDeviceListener

packages/vscode-extension/lib/expo_router_plugin.js, packages/vscode-extension/lib/expo_router_v2_plugin.js
Currently, navigating to another page is impossible if a modal is opened. The root cause of the problem is using `router.push` that does not dismiss modals. You can read more about it.
https://github.com/expo/expo/issues/26922#issuecomment-1996862878 .
However approaches that they proposed aren't good because they introduce other bugs such as unnecessarily closing modals, because of this - thanks to @kmagiera catch  (https://github.com/software-mansion/react-native-ide/pull/204#discussion_r1594708930) I eventually bet on `navigate` combined with `setParams`. This approach works smoothly without introducing additional problems.
https://github.com/software-mansion/react-native-ide/assets/77052270/5b26f4cb-24cf-4c13-a57d-f33f9a20d680
By replacing the current implementation with `navigate` …
=> fix: closing modal through ide url panel

packages/vscode-extension/lib/expo_router_plugin.js, packages/vscode-extension/lib/expo_router_v2_plugin.js
This PR changes require to import syntax in expo-router plugin in order to address an issue with React Compiler.
The problem with compiler was because of some weird interference of babel plugins responsible for code transforms. The compiler plugin adds import statement to file it processes in order to import its runtime. However, since there were no other imports initially in the expo-router file, that new import statement would never be processed and it'd be kept in the file causing JS error that import statements should be on top of the file (plugin file would be somewhere in the middle of the bundle, so it can't use imports after being bundled).:
After changing require to import syntax, it appears like babel now understands that it needs to process imports and it processes all of them …
=> Use import syntax in expo-router plugin to fix React Compiler

packages/docs/src/css/overrides.css
Hire Us Container is redundant in `Privacy Policy`, `Terms Of Use` and `Refund Policy` subpages, so we decided to hide it there.
Before:
After:
=> docs: Remove Hire Us Container from subpages

packages/docs/docs/launch-configuration.md, packages/vscode-extension/package.json, packages/vscode-extension/src/project/metro.ts, packages/vscode-extension/src/utilities/launchConfiguration.ts
Fixes #318
This PR updates the way we detect whether project should use Expo CLI. There are two main changes here:
1) In addition for checking whether expo cli is installed, we also verify that scrtips section in package json contains some expo commands (like "expo start" etc)
2) We add launch configuration option for overriding this behavior and forcing the use of Expo CLI
=> Improve detection whether we should use Expo CLI

packages/vscode-extension/src/webview/hooks/useBuildErrorAlert.tsx
Bundle errors shouldn't require full rebuild to get fix as they are due to JS-only code changes. We shouldn't trigger clean builds from the bundle error dialog.
=> Don't perform clean rebuild on bundle errors

packages/docs/src/components/Pricing/PricingPlansList/index.tsx, packages/docs/src/components/Pricing/PricingPlansList/styles.module.css
=> Update styles & content for Early bird license pricing card

packages/vscode-extension/src/builders/BuildIOSProgressProcessor.ts
This PR solves an issue with iOS build Progress sometimes exceeds 100%.
Before: 
https://github.com/software-mansion/react-native-ide/assets/159789821/46cc5390-eae8-4dff-9781-207180879ebb
After:
https://github.com/software-mansion/react-native-ide/assets/159789821/79413d55-270e-47b9-89ff-ba51d3bad249
***recordings were made during a build of the same bare react native template.
=> Introduce a cap for iOS build progress.

packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/Preview.css, packages/vscode-extension/src/webview/components/Preview.tsx, packages/vscode-extension/src/webview/components/UrlSelect.css, packages/vscode-extension/src/webview/components/ZoomControls.tsx, packages/vscode-extension/src/webview/hooks/useResizableProps.tsx, packages/vscode-extension/src/webview/views/PreviewView.css, packages/vscode-extension/src/webview/views/PreviewView.tsx, packages/vscode-extension/src/webview/views/View.css
This PR fixes problems related to width of the webview: 
1) "Fit" functionality of zoom controls now fits the device to booth, width and hight of the container, instead of just hight.
2) top and bottom menus no longer warp, but url bar changes the size instead. To account for the change dropdown menu triggered by url bar is now visually separated  from the url bar itself. 
on top of the above changes this PR changes the behavior of x1 zoom level from dynamically meaning "fit the container" to meaning the constant original size of the phone.
=> Fix a range of webview resizing issues. 

packages/vscode-extension/package-lock.json, packages/vscode-extension/package.json, packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/common/utils.ts, packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts, packages/vscode-extension/src/devices/IosSimulatorDevice.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/DeviceSettingsDropdown.tsx, packages/vscode-extension/src/webview/components/shared/Button.tsx, packages/vscode-extension/src/webview/components/shared/Tooltip.tsx, packages/vscode-extension/src/webview/providers/ProjectProvider.tsx, packages/vscode-extension/src/webview/styles/theme.css, packages/vscode-extension/src/webview/views/DeviceLocationView.css, packages/vscode-extension/src/webview/views/DeviceLocationView.tsx
This PR adds an ability to set static device location. 
added functionality:
- setting location
- enable/disable location services
- coordinates validation
https://github.com/software-mansion/react-native-ide/assets/159789821/a22754ba-a832-4fab-a13a-23545da14b79
https://github.com/software-mansion/react-native-ide/assets/159789821/cf25e213-2af1-41d9-9ddd-6baef5c3444d
Fixes: #330
=> Add static geolocation

packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/ZoomControls.tsx
In #317 new fields have been added to device settings. However, since we persist device settings, the changes are not compatible with the old data that might've been stored there. To prevent this we are adding a versioning of device settings key (will increment version with future changes).
This PR also changes the defaults to use disabled location, especially that we need to have some coordinates specified, it'd be weird to have everyone using IDE pointing to the same geo location.
=> Fix errors caused by #317

packages/vscode-extension/src/devices/preview.ts, packages/vscode-extension/src/extension.ts, packages/vscode-extension/src/project/project.ts
When debugging IDE with some users I noticed a strange setup in which the IDE ended up in a state with no sim-server binary. We couldn't get to the bottom of this issue, as subsequent installation went through, but decided to add a more failsafe mechanism for this procedure to prevent similar issue in the future or at least to let us investigate it better.
The problem:
Before we'd "fix" sim-server binary by copying it first to temp location and then using `dd` moving it back to original path. When some of the commands would fail, we could end up with the sim-server binary completely deleted and subsequent runs wouldn't allow for recovery as there was no way to retry it once it's deleted. Furthermore, reinstalling the extension didn't help in those scenarios as it doesn't delete …
=> Add failsafe mechanism for cloning sim-server binary

packages/vscode-extension/src/webview/views/DevicesNotFoundView.tsx
In some code paths we didn't unset the isLoading state which sometimes caused the loading spinner to last indefinitely. This popped out mostly when, for some reason, dialog didn't show up.
Tested by creating new ios device on empty devices view.
=> Prevent infinite loading when creating first device

packages/vscode-extension/src/project/metro.ts, packages/vscode-extension/src/utilities/subprocess.ts
This PR fixes an issue with some modules that use the following pattern for accessing the project directory: https://github.com/zoontek/react-native-bootsplash/blob/master/src/generate.ts#L23
In that pattern PWD env variable takes precedence over process.cwd. However, this PWD variable may be inherited from the parent process and should not be passed down to child process when launched with cwd option.
This PR fixes this problem, by overriding PWD variable to point to cwd varlue when both are set. We also add stderr reading to metro subprocess such that it outputs error messages to the IDE logger.
=> Override PWD variable when launching subprocess from different directory

packages/vscode-extension/src/utilities/subprocess.ts
#369 introduced a regression as under certain conditions, options may be not set despite arguments array being long enough. We need to test for that before reading from the options object.
=> Fix crash caused by #369

packages/vscode-extension/src/utilities/fingerprint.ts
`expo-dev-launcher` in particular modifies its node_modules files, adding locks such as `app/node_modules/expo-dev-launcher/expo-dev-launcher-gradle-plugin/.gradle/buildOutputCleanup/buildOutputCleanup.lock`.
They change from launch to launch, modifying entire fingerprint.
Found by using `diffFingerprints` between last and current fingerprint, then utilizing `fswatch` to find offending files.
Tested by changing JS code in the [expo app](https://github.com/expo/react-conf-app).
=> Remove .gradle directories from fingerprint

packages/vscode-extension/lib/runtime.js, packages/vscode-extension/src/debugging/DebugAdapter.ts
This PR changes the way we override error handlers in our RN runtime.
Before, we'd register error handlers in initialization code, now we only do that once the debugger is connected.
The issue with the old approach was that in the case when there is some uncaught exception in the init phase, it'd go into our custom handler that'd stop the debugger. In that case we'd never be able to dispatch app-ready and hence the debugger would never connect.
In this PR we use CDP `Runtime.evaluate` to call new global handler `RNIDE_onDebuggerConnected` that is then used by the runtime to install error handlers. With this change in, initialization errors won't be caught in the debugger but they also won't freeze the app entirely w/o any clue.
=> Delay setting error handlers until debugger is connected

packages/vscode-extension/lib/wrapper.js
This PR rewrites the logic responsible for dealing with devtools agent inside the main app wrapper that's a part of RNIDE runtime.
The previous implementation was quite messy and not well organized. Specifically, handling changes of some of the callbacks wasn't implemented properly and might've resulted in certain events triggering old versions of callbacks.
This rewrite aims to organize this implementation a bit better. Here are some key points of the work being done here:
1) we extract individual elements into separate effects with proper dependency arrays
2) we make sure that event callbacks registered with devtools agent are also disconnected
3) properly handle the case when layout event comes before agent is present (before we'd never trigger "app ready" event in such case
=> Rewrite wrapper code to properly support cases when devtools connect  with some delay

packages/vscode-extension/lib/expo_router_v2_plugin.js
In #316 we introduced a regression with expo-router v2 integration. The used `router.navigate` method is only available in v3 and hence we revert that modification change for expo-router v2 plugin. This PR effectively reverts changes from #316 made to packages/vscode-extension/lib/expo_router_v2_plugin.js file
=> Revert changes from #316 for expo-router v2 implementation

packages/vscode-extension/src/builders/buildAndroid.ts, packages/vscode-extension/src/builders/buildIOS.ts, packages/vscode-extension/src/dependency/DependencyChecker.ts, packages/vscode-extension/src/dependency/DependencyInstaller.ts, packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts, packages/vscode-extension/src/project/metro.ts
When debugging some weird issues associated with env variables, I noticed that execa by default extends the process env. In most of the cases this is the desirable approach and hence we don't need to handle that ourselves as it only makes the whole flow more polluted with unnecessary options.
=> Rely on exec extending env by default

packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts
We recently added code that'd write to shaed prefs in order to disable dev menu popping up on expo dev client on Android. This apparently doesn't work with expo go, as the go APK installed on the emulator is not debuggable. In this PR we add a check for the bundle name before we write the setting.
=> Don't update shared prefs for expo go

packages/vscode-extension/src/webview/views/PreviewView.tsx
When reloading the project, logs were cleared (`Runtime.executionContextsCleared` event handler sends ctrl+J to the console which clears it). However, log counter wasn't cleared.
|Before|After|
|-|-|
|<video src="https://github.com/software-mansion/react-native-ide/assets/12465392/f3127666-1deb-4cae-b40a-2785230327b4" />|<video src="https://github.com/software-mansion/react-native-ide/assets/12465392/d83b2033-770e-4ecb-9ce0-c67b31dca245" />|
=> Clear log counter on start

packages/vscode-extension/src/webview/components/Preview.tsx
When inspecting via clicking inspect and then using right click, inspector was dismissed even if we didn't select any option.
|Before|After|
|-|-|
|<video src="https://github.com/software-mansion/react-native-ide/assets/12465392/c8965bd8-c9a9-4694-b607-366307882dc0" />|<video src="https://github.com/software-mansion/react-native-ide/assets/12465392/95e98e51-0ffc-47d0-b63e-8378faf5e924" />|
=> Fix right click when inspecting

packages/vscode-extension/package.json, packages/vscode-extension/src/extension.ts, packages/vscode-extension/src/panels/Tabpanel.ts
Currently, there is a chance of accidentally closing the IDE panel and it can be an unpleasant experience
Simple confirmation popup to avoid headaches.  The following popup only appears if users click `cmd+w/ctr+w` 
https://github.com/software-mansion/react-native-ide/assets/77052270/70c45f35-9d89-4b99-ad97-9f69e0cbc96e
https://github.com/software-mansion/react-native-ide/issues/387
=> Avoid closing IDE accidentally

test-apps/react-native-73/ios/.gitignore, test-apps/react-native-73/ios/.xcode.env.local
Some projects have .gitignore inside ios folder that excludes .xcode.env.local while otehr projects doesn't have it. This PR unifies this setting as we don't want dev's local paths included under version control as they may impact builds on other environments.
=> Add .xcode.env.local to gitignore across all projects

packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts
This PR solves an issue, with android reloads, that was causing new emulator  device to crash, because the old one was still active. 
Solution: 
check if the process with the same avd is running before booting the device.  
Before: 
https://github.com/software-mansion/react-native-ide/assets/159789821/3b9a5111-97ce-4b02-b8b0-51125f83bc52
After: 
https://github.com/software-mansion/react-native-ide/assets/159789821/427ae727-e5aa-44ef-bf30-0bb2e9fbbdc5
=> Fix Android crashing on reload

packages/vscode-extension/lib/preview.js
When `preview(<View />)` was used, URL bar shown "preview:undefined".
Turns out that forwarded ref components have different structure for `.type` which doesn't include meaningful name in it.
=> Fix displaying component names in the preview URL

packages/vscode-extension/src/common/DeviceManager.ts, packages/vscode-extension/src/utilities/iosRuntimes.ts, packages/vscode-extension/src/utilities/sdkmanager.ts, packages/vscode-extension/src/webview/views/CreateDeviceView.tsx
This PR adds some improvements to system image list that gets displayed in the new device creation flow.
1) We no longer limit number of Android images to 3
2) We still show images that are not available (before we'd hide them which was confusing in some cases as users saw they had some images installed but they couldn't use them in the IDE)
3) We mark android images with incompatible ABI as not available (we only allow images with the current cpu architecture to run)
Test plan:
1) Go over device creation flow
2) Install x86 android image on M1 mac and see it being listed but disabled.
=> Improve list of system images when creating new device

packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts
This PR fixes an issue we found with some setups. After the app is installed for the first time on Android, it sometimes would get the shared preferences file creates as an empty file. As a result, neither the parser nor the `cat` command would throw but the resulting prefs object would be null. 
This PR adds a check for the structure of prefs objects, such that we can be sure it has the expected structure (containing a `map` field in particular), before we continue with updating the prefs object.
Test:
As I couldn't reproduce this issue on my local environment, the change that I did was to clear up the shared preferences file after the app was already installed, then perform a clean build on Android.
=> Handle empty shared preferences file when setting options for Android

packages/vscode-extension/src/webview/components/PreviewLoader.css, packages/vscode-extension/src/webview/components/PreviewLoader.tsx, packages/vscode-extension/src/webview/components/shared/StartupMessage.tsx
The ability to click the startup message to see more was pretty obscure. Now, if some startup step takes more than 30s, we underline the message so users understand clickability. Most of the time it's not needed, this is meant for situations where RNIDE gets stuck on some step.
https://github.com/software-mansion/react-native-ide/assets/12465392/80ef8bff-9509-46cb-9650-fc8813fe695f
=> Make clicking progress message more discoverable

packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/SettingsDropdown.tsx, packages/vscode-extension/src/webview/components/shared/KeybindingInfo.css, packages/vscode-extension/src/webview/components/shared/KyebindingInfo.tsx
This PR is addressing a problem with discoverability of a keybinding that allows users to open dev-menu (cmd+shift+z by default). The new UI hopefully, will clear up the confusion users may had, caused by  their experience with expo shortcuts. It also provides a function that allows to check current keybinding for commands contributed by RNIDE, even if user has set custom ones.  
This functionality could be further improved by adding a listener that would inform the UI about changes in user keybindings (aka. keybindings.json file), but as it seems very unlikely that somebody is going to have a dropdown menu open and at the same time changing keybindings in vscode settings, it does not seem to be a priority right now. 
keybinding.json is the only place we should expect keybinding to be …
=> Add information about keybindings to dropdown menu. 

packages/vscode-extension/src/utilities/subprocess.ts
This fixes an issue when VSCode started from app launcher would populate PWD environment constant which interfers with some tooling.
We've already attempted to fix that in #369 but the fix really only worked when PWD was set as options.
Aparently execa library that we use for subprocess management by default inheritcs process.env (which is what we want). But in that case env.PWD would be provided even despite the fact it wasn't included in env from the options. This got broken along with #378 where we stopped manually passing process.env when launching.
As a consequence, we will now always override PWD with "0" which will result in third-party checks to fail on that variable.
Test plan:
Launch react-conf-app repo with VSCode started from launcher
=> Avoid passing PWD entirely to subprocesses when cwd option is set

packages/vscode-extension/src/utilities/subprocess.ts
This PR fixes a bug introduced in #432.
The bug caused "options" argument to be removed from subprocesses that did not specify the cwd.
=> Correctly pass options to exec-like functions

packages/vscode-extension/src/webview/components/Preview.css, packages/vscode-extension/src/webview/hooks/useResizableProps.tsx, packages/vscode-extension/src/webview/views/View.css
This PR hides, device selection that happens when user presses cmd + A. 
This change is required because the user-select css property is not inheritable, which is why it does not disable global selection (using ctrl + A or double-click). 
Fixes: #434
=> Fix cmd + A selecting the device image 

packages/docs/src/components/HomepageButton/styles.module.css, packages/docs/src/components/LicenceBanner/index.tsx, packages/docs/src/components/LicenceBanner/styles.module.css, packages/docs/src/pages/index.tsx
This PR adds Supporter Licence section banner.
=> docs: Add Supporter Licence section banner

packages/vscode-extension/src/devices/preview.ts
This PR adreses the problem that introduced by a change in sim-server that logs: 
`Stream live on ${adres}` instead of `${adres}` when the preview is ready. 
Additionally a new approach allows us to make sure that the url is the required  stream and frees up the sim-server to log other links in the future.
=> Extract just preview address from sim-server logs

packages/vscode-extension/src/project/project.ts
This PR fixes the issue of the error bar persisting even after removing the iOS device. 
After removing the device, the project state is set to "starting" to ensure it doesn't remain in the "buildError" state.
Although the error bar is visible after device removal, it disappears after a few seconds.
Resolving the issue of selecting the removed device ensures that the error bar is hidden completely in this case.
resolves: #466
=> Fix not disappearing error bar

packages/vscode-extension/src/common/utils.ts, packages/vscode-extension/src/panels/webviewContentGenerator.ts, packages/vscode-extension/src/utilities/platform.ts, packages/vscode-extension/src/utilities/utils.ts, packages/vscode-extension/src/webview/providers/DevicesProvider.tsx, packages/vscode-extension/src/webview/providers/UtilsProvider.tsx, packages/vscode-extension/src/webview/views/CreateDeviceView.tsx, packages/vscode-extension/src/webview/views/DevicesNotFoundView.tsx
Originally, we passed it as object with functions. We only transform top level functions as proxies. Additionally, to not require it to be async (or to wait until we resolve it) we pass it as global and reimplement functionality on the webview side.
=> Fix passing OS to webview

packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/devices/DeviceBase.ts, packages/vscode-extension/src/devices/preview.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/Preview.tsx
This PR adds implementation of multitouch support for iOS and Android devices.
To use multitouch feature press and hold `Option` button, then two markers indicating touch points show up. While holding `Option` button and pressing `left mouse` button movements and button clicks ("up", "down") are sent to the sim-server subprocess. To pan touch points press `Option` and `Shift` buttons at the same time.  When the mouse leaves device's screen area, multitouch ends with "up" command.
Instead of `Option` button use `Alt` button on Windows.
⚠️After implementing the backend part in sim-server (#470) ensure that a proper multitouch command is set in `sendMultiTouch` function in `src/devices/preview.ts` file.
resolves: #449
=> Add multitouch support

packages/vscode-extension/src/dependency/DependencyManager.ts
This PR fixes the dependency checker by excluding the check for Xcode, CocoaPods, and Pods on non-macOS systems.
=> Fix dependency checker for Windows

packages/vscode-extension/src/dependency/DependencyManager.ts
After #457 pods not being installed is not considered an error, so an error message was removed. But sometimes the installation process it self might fail and this PR exposes that error to the user.
=> Fix pod install not exposing an error to the user

packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/devtools.ts, packages/vscode-extension/src/project/metro.ts, packages/vscode-extension/src/project/project.ts
This is the first PR from series of six that try to extract as much code as possible from Project.
It extracts code related to controlling debugger to `DebugSession` class and does some minor improvements to `Project`'s code.
The end goal is to create simpler interfaces and allow for fine-grained controls of reloading.
The idea I had in mind was to move build and metro/devtools lifecycle into DeviceSession and allow to control lifecycle of both device-independent components (such as metro) and devices.
State that originally lived in Project was moved in other places or updated by creating callbacks and passing Project as delegate to those places.
This effort isn't finished but is ready enough to implement parts of original goal.
<details><summary>After-refactor API notes</summary>
<p>
``` …
```
=> Extract debugger code to own class

packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts
⚠️ Depends on https://github.com/software-mansion/react-native-ide/pull/472.
Second PR in refactoring effort, see https://github.com/software-mansion/react-native-ide/pull/472 for overall notes.
Extracts events coming from app to `DeviceSession` in order to move devtools there in the future. Also extract device selection step to its own function in order to cut code in future refactorings.
=> Move app event handling to device session

packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/metro.ts, packages/vscode-extension/src/project/project.ts
⚠️ Depends on https://github.com/software-mansion/react-native-ide/pull/473.
Third PR in refactoring effort, see https://github.com/software-mansion/react-native-ide/pull/472 for overall notes.
- Changes metro.reload() to wait until app is ready. This allows for removal of `reloadingMetro` state in `Project`.
- Adds initial implementation of `DeviceSession.perform(type)`.
=> Remove reloadingMetro state from project

packages/vscode-extension/src/devices/DeviceBase.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts
⚠️ Depends on https://github.com/software-mansion/react-native-ide/pull/474.
Fourth PR in refactoring effort, see https://github.com/software-mansion/react-native-ide/pull/472 for overall notes.
- Adds `onPreviewReady` callback to `Project`.
- Adds `DeviceSession.perform("restartProcess")`
=> Implement restartProcess reload option

packages/vscode-extension/src/builders/BuildManager.ts, packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts, packages/vscode-extension/src/devices/DeviceBase.ts, packages/vscode-extension/src/devices/DeviceManager.ts, packages/vscode-extension/src/devices/IosSimulatorDevice.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts
⚠️ Depends on https://github.com/software-mansion/react-native-ide/pull/475.
Fifth PR in refactoring effort, see https://github.com/software-mansion/react-native-ide/pull/472 for overall notes.
- Adds `DeviceSession.perform("reinstallApp")`.
- Adds device info to device instances.
- Remove `DeviceSession.restart()` and replace uses with `DeviceSession.perform("restartProcess")`.
=> Implement reinstallApp reload option

packages/vscode-extension/src/devices/DeviceManager.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/devtools.ts, packages/vscode-extension/src/project/metro.ts, packages/vscode-extension/src/project/project.ts
⚠️ Depends on https://github.com/software-mansion/react-native-ide/pull/476.
Sixth PR in refactoring effort, see https://github.com/software-mansion/react-native-ide/pull/472 for overall notes.
This change was mostly focused on moving `BuildManager` into `DeviceSession` but I also did a lot of small improvements in project's and device session's code.
=> Move buildManager into device session

packages/vscode-extension/src/panels/WebviewController.ts
Device manager have nothing to cleanup after it's destroyed.
=> Remove device manager from disposables list

packages/vscode-extension/src/project/project.ts
This PR fixes a bug introduced in #477, that caused deviceSession.buildApp call a method that was not properly bind, which resulted in the following error: 
```rejected promise not handled within 1 second: TypeError: Cannot set properties of undefined (setting 'detectedFingerprintChange')
extensionHostProcess.js:147
stack trace: TypeError: Cannot set properties of undefined (setting 'detectedFingerprintChange')
at onBuildSuccess
```
=> Fix binding in EventDelegate in device session

packages/vscode-extension/src/panels/webviewContentGenerator.ts
Fixes "Refused to execute inline script because it violates the following Content Security Policy" error.
=> Add nonce for inline script

packages/vscode-extension/lib/wrapper.js
This PR fixes a problem with navigation after using preview functionality. 
It turns out that navigation is not ready immediately  after mounting the wrapper component, the solution is to await layout instead. 
Bug: 
```
Attempted to navigate before mounting the Root Layout component. Ensure the Root Layout component is rendering a Slot, or other navigator on the first render.
```
To Reproduce: 
go to expo-51 example and try navigating from preview to any path in main application
=> Fix navigation after Preview. 

packages/vscode-extension/lib/metro_helpers.js
This pull request fixes an issue with scheduler not being loaded, when it wasn't an explicit dependency of an application.  The scheduler is an internal module for all react applications, you can find out more about it [here](https://github.com/facebook/react/tree/main/packages/scheduler).  Before our changes that replace React Native Renderer it was imported automatically by metro, because renderer was part of react-native package.  
Error message from the old version: 
```
Unable to resolve module scheduler from /Users/filip/Documents/react-native-ide/packages/vscode-extension/lib/rn-renderer/ReactNativeRenderer-dev.js: scheduler could not be found within the project or in these directories:
../../react-native-ide/packages/vscode-extension/node_modules
node_modules
29 | …
```
=> Fix scheduler not being loaded

packages/vscode-extension/src/builders/expoGo.ts, packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts, packages/vscode-extension/src/devices/DeviceBase.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/metro.ts
There's currently an error which prevents sending `RNIDE_appReady` events. This results in IDE being stuck at "Waiting for an app to load" state. We workaround it on Windows to never wait.
This is caused by wrapper.js not being loaded as app's wrapper. This also means we can't use inspector functionality and other things that rely on communication with the app.
=> Skip waiting to load on windows

packages/vscode-extension/src/builders/BuildManager.ts, packages/vscode-extension/src/builders/buildAndroid.ts, packages/vscode-extension/src/builders/buildIOS.ts, packages/vscode-extension/src/builders/cancelToken.ts, packages/vscode-extension/src/builders/expoGo.ts, packages/vscode-extension/src/dependency/DependencyManager.ts
- Removed DisposableBuildImpl, now we return dispose method directly
- Moved Platform tags into ios/android building code
- Extracted functions managing VSC workspace storage for cache
Tested by full clean building on expo-51 (dev, go, android, ios) and switching simulators when it was building. I wasn't able to run Android (same as on main) but build part completed successfully
=> Simplify BuildManager

packages/vscode-extension/src/webview/hooks/useBuildErrorAlert.tsx
This PR fixes useBundleErrorAlert which previously was modeled on useBuildErrorAlert and had options that were not really useful in bundle error case. 
Before: 
After:
=> Change the behavior of useBundleErrorAlert 

packages/vscode-extension/src/webview/components/Preview.tsx, packages/vscode-extension/src/webview/styles/theme.css, packages/vscode-extension/src/webview/views/PreviewView.css
This PR hides zoom controls outside of the screen unless user hovers over the left border of our web view. 
https://github.com/user-attachments/assets/03a169b0-bc0a-4251-ac18-195a8d8a2e5c
=> Hide Zoom controls

packages/vscode-extension/src/extension.ts, packages/vscode-extension/src/utilities/subprocess.ts
When launching VS Code from Applications, we sometimes get a `PATH` env var that doesn't have path to node, npm, or other tools. This happens because some tool managers like nvm, asdf, mise, etc update `PATH` only in rc files, which are only used when launching shells interactively.
To prevent errors, we start user's shell (or ZSH in case $SHELL isn't defined) interactively once when opening IDE panel for the first time and use its env with execa. In case of an error, we show a warning a proceed.
To test this, run VS Code from applications, comment out `preLaunchTask` in `launch.json`, run `npm run build:extension-debug` and `npm run watch:extension` and launch extension development task (F5 or run launch.json).
You should not see any error in debug console and extension should work …
=> Set environment on startup

packages/vscode-extension/lib/babel_transformer.js, packages/vscode-extension/src/project/deviceSession.ts
We're using filenames which are platform-specific to check what files should be modified. Windows uses backslashes so it wasn't ever matched.
Run any app on windows and check if RN IDE functionality works (inspector, etc).
=> Fix wrapper to work on Windows

packages/vscode-extension/lib/babel_transformer.js
This PR adds a missing import in the previous PR #522 and changes `/` path separator to platform-specific in`babel_transformer.js`.
=> Fix missing import in babel_transformer

packages/vscode-extension/src/webview/components/PreviewLoader.css, packages/vscode-extension/src/webview/components/shared/StartupMessage.css
This PR updates CSS for startup messages in Preview Loader to ensure proper wrapping on smaller device displays.
Before:
After:
=> Update startup messages wrapping in Preview Loader

packages/vscode-extension/package.json, packages/vscode-extension/src/debugging/DebugAdapter.ts
This PR updates call to prettier from lint script to use npm.
Previously the script would use `yarn prettier` to call prettier from `node_modules/.bin`, however, this comand fails now with newer version of yarn as the new yarn thinks this project is a yarn workspace project (due to package.json structure) which is not the case.
Since we're using `npm` as package manager, it's better to stick to it instead of relying on yarn for simple script calls. 
This PR updates `yarn prettier` command to call `npm exec prettier` instead.
=> Update prettier call in lint command to use npm

packages/radon-ide/index.d.ts, packages/radon-ide/index.js, packages/radon-ide/package.json, packages/vscode-extension/lib/android/buildProgressEvaluation.initscript.gradle, packages/vscode-extension/lib/babel_transformer.js, packages/vscode-extension/package.json, packages/vscode-extension/scripts/build-sim-server.sh, packages/vscode-extension/src/builders/BuildAndroidProgressProcessor.ts, packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/extension.ts, packages/vscode-extension/src/panels/LaunchConfigController.ts, packages/vscode-extension/src/panels/Tabpanel.ts, packages/vscode-extension/src/panels/webviewContentGenerator.ts, packages/vscode-extension/src/providers/PreviewCodeLensProvider.ts, packages/vscode-extension/src/utilities/common.ts, packages/vscode-extension/src/utilities/launchConfiguration.ts, packages/vscode-extension/src/webview/views/PreviewView.tsx, test-apps/expo-router/app/components/NiceButton.js, test-apps/expo-router/app/components/UglyButton.js, test-apps/expo-router/package-lock.json, test-apps/expo-router/package.json
This is the first step for our renaming process. It renames most react-native-ide occurences that doesn't affect users or are not visible.
1) We're republishing react-native-ide under radon-ide package name (next step would be to fallback from react-native-ide to radon-ide)
2) We are adding new configuration scheme "radon-ide" but for now keeping it as a copy. We want to accept new and old schemes going forwards and deprecate the old one after renaming is complete.
3) We're keeping all user-facing name as-is for the time being. Will want to update docs first for the transition to complete – those changes will come as a follow up.
4) Code changes are mostly made to be backwards compatible and when possible we are supporting old names (i.e. for NPM package or for the config scheme)
Final …
=> First phase of react-native-ide to radon IDE renaming - renaming non-visible bits first

packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/devices/DeviceBase.ts, packages/vscode-extension/src/devices/preview.ts, packages/vscode-extension/src/panels/WebviewController.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/Preview.tsx, test-apps/expo-router/app/index.js, test-apps/expo-router/app/rotato.js
This PR builds on top of changes from https://github.com/software-mansion-labs/simulator-server/pull/173 where we add support for multitouch events to be dispatched to device (Android for the time being).
This change restructures the multitouch handling code both on the front-end and in extension code such that we follow the new protocol. Now, instead of having separate command for multitouch, we allow for the dispatchTouch method to take an array of touches (typically one or two). Then, we send `touchDown` or similar command with additional coordinates after the x and y of the first pointer are added.
The main change on the frontend was that we don't send leading point and anchor points but instead send two concrete touch points,. This removes coupling because sim-server and frontend …
=> Use touchX command with extra args to dispatch touch events to sim-server

packages/vscode-extension/src/webview/components/shared/Button.tsx, packages/vscode-extension/src/webview/components/shared/Modal.tsx, packages/vscode-extension/src/webview/views/ManageDevicesView.tsx
this PR fixes a problem initially solved in #276, unfortunately the previous approach prevented us from autofocusing on input fields in modals when opening modals for the first time, as it kept focus on the background.
=> Fix focus when entering modal dropdown.

packages/vscode-extension/package.json, packages/vscode-extension/src/Logger.ts, packages/vscode-extension/src/builders/BuildManager.ts, packages/vscode-extension/src/extension.ts, packages/vscode-extension/src/integration-tests/extension.test.ts, packages/vscode-extension/src/panels/LaunchConfigController.ts, packages/vscode-extension/src/panels/SidepanelViewProvider.ts, packages/vscode-extension/src/panels/Tabpanel.ts, packages/vscode-extension/src/panels/WorkspaceConfigController.ts, packages/vscode-extension/src/project/project.ts
This phase 3 of renaming React Native IDE to Radon IDE.
This part touches the elements in the extension user interface that were using the old name including vscode configuration, launch configuration, command names and error messages.
As part of this PR we are adding a small migration function to copy global configuration. It runs in the extension activation phase before we start initializing the panel.
After this phase the things that are left are:
Run expo-router app on Android iOS
With the previous version change panel location -> see this setting is kept across the configuration name change
Test keybindings
=> Rename react native IDE to Radon IDE (the parts visible to the user)

packages/docs/docs/troubleshooting.md, packages/vscode-extension/src/devices/preview.ts
This PR allows non standard xcode setups.
- change the name of xcode.app in your application directory
- update xcode-select using `xcode-select --switch ${PathToYourXCode}/Contents/Developer`
- run ide
=> Fix alternative xcode paths

packages/vscode-extension/src/builders/buildAndroid.ts, packages/vscode-extension/src/builders/buildIOS.ts, packages/vscode-extension/src/devices/preview.ts, packages/vscode-extension/src/project/metro.ts, packages/vscode-extension/src/utilities/subprocess.ts
This PR modifies the behavior of lineReader which would previously only tried on reading from stderr when requested.
Since typically stderr is used to pass on important information and given almost all uses in out codebase would set stderr as `true`, this method now connects to stderr by default. 
For the use-cases where we want to be able to tell whether line comes from stderr or stdout (like with the sim-server stdout that is used as communication and control channel), the line callback gets an additional argument that indicates whether line comes from stderr.
Run expo-router, try clean rebuild on Android and iOS
=> Modify line reader to always consume stderr and mark stderr in callback

packages/vscode-extension/src/Logger.ts, packages/vscode-extension/src/extension.ts, packages/vscode-extension/src/webview/components/Preview.tsx
This PR:
- changes the button that initiates the multitouch gesture to the `control` key on Windows
- fixes the error message display when the `diagnoseWorkspaceStructure` command cannot find the `appRoot` folder
- corrects warning messages in `Logger`
=> Change multitouch button for windows and fix misc minor bugs

packages/vscode-extension/src/devices/IosSimulatorDevice.ts
This PR fixes a bug introduced by #562 witch always searched for localization settings in new caches directories for ios devices.
=> Fix new caches location in localization settings

packages/docs/src/pages/privacy-policy.mdx, packages/docs/src/pages/purchase-terms.mdx, packages/docs/src/pages/refund-policy.mdx, packages/docs/src/pages/supporter-terms.mdx, packages/docs/src/pages/terms-of-use.mdx
This PR renames all occurences of React Native IDE to Radon IDE in legal pages in the IDE documentation.
This also affects the version of the documents presented (`1.0` -> `2.0`) and the `effective as of` date.
=> Rename React Native IDE to Radon IDE in legal

packages/docs/docs/troubleshooting.md, packages/vscode-extension/src/common/DeviceManager.ts, packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/dependency/DependencyManager.ts, packages/vscode-extension/src/devices/DeviceManager.ts, packages/vscode-extension/src/devices/preview.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/utilities/packageManager.ts, packages/vscode-extension/src/utilities/subprocess.ts, packages/vscode-extension/src/webview/providers/ProjectProvider.tsx, packages/vscode-extension/src/webview/views/PreviewView.tsx
this PR addresses a few issues with the loading devices  flow: 
- `checkIfCLIInstalled` no longer logs errors when returning false instead just logs with debug level, this change makes the logs more alined with expected results for setups without xcode
- initial device load is performed with force, as xcode installation could change between session of the ide
- initial loading screen no longer "jumps" between states 
- removed `DYLD_FRAMEWORK_PATH` as it is no longer needed
- `trySelectingInitialDevice()` creates "devicesChanged" listeners before selectingInitial device is complete, so it catches cases in which `lastDeviceId` points to the device that no longer exists (e.g. because of xcode update)
=> Improve a flow of loading devices and xcode detection

packages/vscode-extension/src/project/project.ts
This PR fixes a mistake introduced in  #563, the return value of `selectDevice` should indicate if device was chosen successfully, not if processes on it are successful otherwise if build fails and the selected device was set by `trySelectingInitiallDevice` we are getting stuck in infinite loop.
=> Fix infinite reload

packages/vscode-extension/.vscode/settings.json, packages/vscode-extension/package-lock.json, packages/vscode-extension/package.json, packages/vscode-extension/src/debugging/logFormatting.ts, packages/vscode-extension/src/utilities/common.ts, packages/vscode-extension/src/utilities/throttle.ts
Upgrades TS and fixes various reported errors.
=> Upgrade TS to 5.6.2

packages/vscode-extension/src/common/utils.ts, packages/vscode-extension/src/panels/WebviewController.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/utilities/utils.ts, packages/vscode-extension/src/webview/components/shared/Anchor.tsx, packages/vscode-extension/src/webview/views/DevicesNotFoundView.tsx
A while ago we introduced a new messaging mechanism that uses TypeScript interface and JS proxies to provide a RPC-like experience. We still had some leftover commands in the codebase, some of which were triggering some abandoned and unused code sections. This PR migrates the remaining commands to use the new RPC mechanism and cleans up dead code some of the unused commands were accessing.
1. We are migrating error message and open URL commands to Utils interface
2. We are updating relevant parts of the webview UI code to use Utils interface instead of calling into vscode API directly
3. We are deleting "file follow" commands and related code that was only updating some internal variables that we never used.
1. Open project with IDE
2. Click "report issue command" (which uses open URL)
=> Move all commands to use message proxies

packages/vscode-extension/src/project/project.ts
This PR fixes an issue with infinite loop we'd fall into with initial device selection that caused "This device is already used..." warning appearing every second.
The problem would occur, when the previously selected device was being used in some other window. The root cause of the problem was that the 'devicesChanged' event can be triggered regardless of whether the device list actually updates, but at any point we trigger the code that loads the devices list. As a consequence `selectInitialDevice` would fall into a loop as it was requesting to load the device, and then setup a listener that'd call `selectInitialDevice` again.
While this issue isn't specific for the case where device is in use, and the infinite loop would still be spinning in case the initial device fails to be selected …
=> Fix infinite loop for device selection when device is already in use

packages/vscode-extension/src/Logger.ts, packages/vscode-extension/src/debugging/DebugAdapter.ts, packages/vscode-extension/src/extension.ts
This PR fixes the logging of errors to include stack traces in the log output.
Before this change, we'd append error as last element to log output channel, whereas VSCode API expects the error to be passed as first item. As a consequence, error would just be treated as strings and we'd only get error.message in the output.
This PR reorders the elements if error object is passed as the last item to Logger.error (we do it in a number of places throught the codebase). Error messages are then provided as the first item which makes VSCode format them properly and also display stack trace in the output.
This is particularily usecul for unhandled exception handlers where we have no clue of where a given error could be thrown.
This PR also disables expected rejections in certain CDP calls that we …
=> Include stack trace for unhandled promises and error logging

packages/vscode-extension/src/builders/BuildManager.ts, packages/vscode-extension/src/project/deviceSession.ts
This PR adds more loggind and telemetry around build and launch process.
Building and launching the app is one of the most fragile element of the IDE pipeline and we get numerous reports around that. While there are a few known issues around it that we are fixing and investigating. I figured it'd be good to also add telemetry around that such that we can track how it works for a larger group of people and also be able to detect regressions.
Just run the example app with clean build and make sure nothing breaks.
=> Add build and launch telemetry

packages/vscode-extension/src/utilities/android.ts
In #592 we broke the Android Studio path on Mac while replacing the actual path with `path.join` calls. Apparently, `path.join` doesn't start at the file system root, but creates relative path if no lash at the start is provided.
This PR updates the logic of the code that finds java home:
1. We no longer use path.join where it doesn't make sense. Specifically given we have Platform.select we now exacly how paths are constructed on each individual system. Using path.join just makes it more difficult to process this code.
2. We move constants that doesn't need to live under global scope into findJavaHome method (specifically path for android studio)
3. We extract fs root on windows using cwd path root attribute to make it more resilient depending on the users' filesystem setup.
1. Make sure …
=> Fix android studio path after #592

packages/vscode-extension/src/debugging/DebugAdapter.ts
Previously, we added `catch` statements to avoid certain, expected errors from being reported in the log output. However, this turns out to not work, as it seems the catch with no handler method doesn't seem to catch the exception. 
This PR adds a no-op handler for catch statement which makes the error no longer appear in the extension output.
=> Suppress expected errors for certain CDP commands

packages/vscode-extension/lib/wrapper.js, packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/metro.ts
This PR uses a different method for opening dev menu.
Previously we'd call native dev menu module, which was causing problems, specifically in expo-go where the module resolution was resulting in bundle error. Since it turned out to be easier to use the standard method that metro uses for triggering the menu than to debug the old method, I decided to rework the underlying implementation.
Now, we use metro /message endpoint that is used to proxy messages between dev tools and device. One of the messages is "devMenu" which opens the dev menu on the device side (which is what we wanted).
This PR also removes old code which was placed in the wrapper, but also for android we were using a different method that was relying on adb. The new method works on both devices, hence we don't need …
=> Use metro message endpoint to dispatch dev menu request

packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/UrlBar.tsx
This PR renames "hot reload" option from the reload menu to "reload JS" which is a more accurate name. Hot reloading refers to the option of hot-swapping individual modules, whereas this option was doing a full bundle reload.
1. Test reloading JS from reload dropdown
=> Rename hotReload option to reloadJs

packages/vscode-extension/src/project/project.ts
Changes from #477 broke restart flow for the cases when just reloading is not possible.
Previously, when "reload" button was clicked in the UI, we were trying to do the least invasive reload method possible. For that purpose we'd first attempt to reload JS, but only if the app process is alive. Apparently, due to the changes in #477 we were no longer checking whether app is running and we'd always call reload JS and let the restarting process end there.
This turns out to be a problem for example in scenarios where we get bundle error at the app startup. As a consequence, the app process never starts, and it is not possible to reload JS even once the bundle error we're getting gets fixed.
In this PR we're restoring this mechanism:
1) we update `reloadMetro` method to forward the result …
=> Let restart process continue when reload JS is not possible

packages/vscode-extension/src/builders/buildAndroid.ts, packages/vscode-extension/src/dependency/DependencyManager.ts, packages/vscode-extension/src/webview/providers/DependenciesProvider.tsx
#605 introduced new platform folder checks. Apparenly also introduced a small error that got fixed in #607 but while testing this I figured the error messages weren't clear + we were using some weird constructs like "Ios"
=> Rephrase error messages for platform folder checks

packages/vscode-extension/src/panels/webviewContentGenerator.ts
This PR updates CSP used for the IDE panel. This is needed for replays to work, as the built-in player streams the video over http, we need to allow for this.
The issue wasn't detected with non-release builds before as we use different CSP settings there that are much more permissive in order to allow for things like hot reload.
Try out replays on release build
=> Update CSP to allow replays to play in release builds

packages/vscode-extension/src/webview/components/Preview.tsx
This PR disables default context menu on windows, as it clashed with right-click inspector functionality. 
Test plan: 
- open Radon IDE 
- right click inside app previe to trigger inspector
=> Disable default context menu on windows

packages/vscode-extension/src/webview/styles/theme.css
Fixes #618 
Tested select menus in "Manage Device" modal and "Launch Configuration" modal on both dark and light color scheme.
=> Make select content background darker in dark mode for distinction

packages/vscode-extension/lib/runtime.js
This PRs allows apps to use `AppRegistry.setWrapperComponentProvider` API.
The IDE "runtime" uses wrapper component API to provide a top-level component that is responsible for setting up communication between app and the IDE (debugger / inspector / routing). This API is not considered "public" but, apparently, there are some third party libraries (as mentioned in #544) that also rely on this API, which only support a single wrapper component.
As a consequence of the above, those libraries would override the IDE's runtime wrapper breaking the communication channel and causing the app to be stuck on the loading phase.
In this PR, we are providing an override for `setWrapperComponentProvider` method, that provides a wrapper component that renders both the IDE runtime wrapper and the custom …
=> Fix app loading error when AppRegistry.setWrapperComponentProvider is used

packages/vscode-extension/lib/runtime.js, packages/vscode-extension/src/common/utils.ts, packages/vscode-extension/src/panels/WebviewController.ts, packages/vscode-extension/src/utilities/utils.ts, packages/vscode-extension/src/webview/index.jsx, packages/vscode-extension/src/webview/providers/UtilsProvider.tsx, packages/vscode-extension/src/webview/utilities/rpc.ts
This PR adds a mechanism for redirecting logs and unhandled error from webview to the main extension. 
The reason for this change is that we can see potential issues and logs in a unified log output that we create for the extension context. This way we provide better visibility of errors that happen in the webview. Without this change, we'd always need to check both the extension log output, and the vscode devtools panel. With this change, having everything in a single output is specifically helpful when receiving logs from the users, as we no longer need to ask them to check devtools console and can focus on a single log file they need to check or send as a part of the report.
Add log statement and unhandled error to the main webview App.tsx. See that this gets included in the main log …
=> Redirect logs/uncaught errors from webview to the main extension logger

packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts, packages/vscode-extension/src/project/deviceSession.ts
This PR fixes the recovery mechanism when bundle error occurs. Previously, when bundle error happened on Android, we attempted to restart the process by using `launchApp` code path. This, however, would only try to launch the app process, while it may already be in a bad state. Launching it again using deeplink wouldn't recover the process, and similarly to how we do this on iOS, we should terminate the process prior to launching via deeplink or with the `monkey` adb command.
Along with this PR we are enhancing the logging for the case when app gets stuck. I'd often search for stream URL to diagnose, and now it gets printed along the "stuck" message.
1. Open project dev-client project with JS errors, see bundle error when it launches
2. Fix errors and try reloading
3. It should now fully …
=> Restart app process on Android when launching app

packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/hooks/useBuildErrorAlert.tsx
This PR updates the error dialog we show when detecting bundle error.
Previously, we'd direct the users to app logs from that dialog. Those logs apparently never display any valuable information about bundling as they come from the app process, while bundle errors are reported by metro.
In addition, the reload button from bundle error would request JS reload, which isn't sufficient in the case when the app boots up with a bundle error.
We are therefore making the following changes:
1. We're updating the logs button from bundle error dialog to open IDE logs where metro errors are getting printed: <img width="1737" alt="image" src="https://github.com/user-attachments/assets/8078639b-3a09-41d0-bf4c-4f4d1a56c955">
2. We're changing the reload button to call `restart` – restart implementation …
=> Bundle error dialog enhancements

packages/vscode-extension/src/webview/components/ReplayOverlay.tsx
This PR fixes a bug introduced when adding video replays in #579 that was making the timer freeze and sometimes show negative values during rewind.
The issue was caused by updating only the video player's current time and not propagating the change to the element rendering the overlay. We've seemed to rely on `handleTimeUpdate` callback registered on `"timeupdate"` event, but this event is not emitted when updating the current time of the video programmatically.
Sometimes, the timer indicated negative values during rewind, and this was also caused by setting the current time on video without updating the overlay's `time` accordingly, which in turn led to `time = 0` (default on mount) and `startTime = [video duration - 5]`, causing the timer to show negative values when `video duration > …
=> Fix `ReplayOverlay` rewind timer

packages/vscode-extension/lib/runtime.js, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/metro.ts, packages/vscode-extension/src/project/project.ts
Under some (yet uncertain) circumstances, metro process may be terminated. This causes the restart functionality to stop working and the only recovery option was clean rebuild or restarting the IDE tab.
The reason was that we had a `ready` call in metro, that would always use a single promise instance that is created when metro starts. When the startup was successful, the promise resolves and future call to `ready` would always be successful. This logic wouldn't consider the case when the process starts up fine but terminates later on. As a consequence, we'd always assume the metro process is healthy which resulted in the app being stuck in "waiting for app to load" state.
After fixing the above logic, by resetting the startup promise to reject once the metro process is terminated. I …
=> Improve error recovery after metro process terminates

packages/vscode-extension/src/builders/BuildAndroidProgressProcessor.ts, packages/vscode-extension/src/builders/BuildIOSProgressProcessor.ts
This PR changes the maximum progress for iOS and android build from 1 to 0.999 to avoid situations in which users are send 100% for prolonged  periods of time. 
- run clean build in any test app
=> Adjust Progress Processorss

packages/vscode-extension/package.json, packages/vscode-extension/src/devices/DeviceManager.ts, packages/vscode-extension/src/extension.ts, packages/vscode-extension/src/utilities/platform.ts
This PR fixes fixes issue where error messages for unsupported platforms were not displayed and prevents Xcode errors from appearing on Windows by ensuring the checkXcodeExists function is only executed on macOS.
Previously, an error related to the OS const in `platform.ts` was always thrown before the check in `extension.ts`. This change ensures the verification process happens correctly.
Fixes #620 
- run extension on currently unsupported platform (linux)
- run extension and check the logs for any errors caused by xcrun on Windows
=> Show unsupported platforms error message

packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/webview/components/InspectDataMenu.css, packages/vscode-extension/src/webview/components/InspectDataMenu.tsx, packages/vscode-extension/src/webview/components/Preview.tsx, packages/vscode-extension/src/webview/views/PreviewView.tsx
This PR includes improvements to the inspector menu:
- hides inspector in the replay view
- corrects the positioning of the `InspectDataMenu`, ensuring the `DropdownMenu` appears at the cursor location
- adds label that displays the dimensions of the inspected element to the `InspectDataMenu` (similar to #585)
- adds a key prop to the components list in `InspectDataMenu` to prevent error messages
- open the replay view and attempt to use the inspector using right mouse button
- close the replay view and confirm the inspector menu operates correctly
- ensure that the inspector menu displays the components' dimensions at the top as expected
=> Correct positioning of InspectDataMenu

packages/vscode-extension/src/webview/components/InspectDataMenu.css, packages/vscode-extension/src/webview/components/InspectDataMenu.tsx
Fixes a small style regression after #639 
#639 introduced class names conflict, which caused an unexpected change in appearance of "Device Settings" (most notably, smaller padding). This PR fixes it.
Tested in `react-native-75`
=> Change InspectDataMenu style class names to fix naming conflict

packages/vscode-extension/lib/metro_helpers.js, packages/vscode-extension/lib/runtime.js, packages/vscode-extension/src/builders/buildAndroid.ts, packages/vscode-extension/src/debugging/DebugAdapter.ts, packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/project/metro.ts, packages/vscode-extension/src/utilities/reactNative.ts
This PR fixes a problem with debugger on expo projects, caused by prelude lines added to the entry bundle file added by expo. The solution is t0 add the required offset to the prelude causing the problem and scanning for it when receiving source map in the debuger.
It is possible that the changes will no longer be needed in future versions of react native as the expo team tries to correct source map generation to include extra lines, for more information read those PRs:
- [expo side ](https://github.com/expo/expo/pull/29463)
- [metro side](https://github.com/facebook/metro/pull/1284)
This is why we add version check before adding lineOffset to initial source map.
- open expo project and set a breakpoint, before the changes it would trigger 2 lines above the place it's been set. 
- save …
=> Fix misaligned lines in debugger

packages/vscode-extension/src/devices/preview.ts
This PR brings on the changes from simulator-server that aim to address the issue with empty / erronous replays.
This issue would arise in when user enables the replays for the device and then w/o any interaction with the screen would snap a replay. With the previous version, this would result in an error, as sim-server wouldn't register any frames since replays were enabled. The second issue was similar but had to do with the fact that after snapping the replay we'd need to stop and start replays again, resulting in the same behavior that'd arise immediately after starting. For this purpose `save` command have been introduced that apart from fixing the issue would let the video buffer retain frames when saving. This way the follow-up replays can also contain frames from previous ones if …
=> Use new save command to fix issue with empty replays

packages/vscode-extension/src/builders/buildIOS.ts, packages/vscode-extension/src/builders/expoGo.ts, packages/vscode-extension/src/webview/hooks/useBuildErrorAlert.tsx, test-apps/expo-go/package-lock.json, test-apps/expo-go/package.json, test-apps/expo-go/tsconfig.json
When testing expo-go I encountered a few small issues this PR is addressing:
1) Unclear messages when expo-go project couldn't launch 
2) Recently we added "shared example code" to expo-go project, but since it is using typescript, expo-go project should have the typescript dependencies added
3) Because of the missing dependencies, metro process would terminate, resulting in the deeplink lookup failure which wasn't properly reported
We are making the following adjustments to address these issues:
1) Updating text in errors to clearly indicate when talking about "android" and "ios" folders. We also change the wording a bit which should now be easier to understand (at least in my opinion)
2) We are adding missing packages to expo-go test app project
3) We are changing the logic for handling …
=> Fix expo-go project configuration and better handle metro being terminated when quering for launch deeplink

packages/vscode-extension/lib/runtime.js, packages/vscode-extension/lib/wrapper.js
This PR fixes an issue we detected in some app configurations (specifically in react conf app). We identified the issue to be rooted in the fact we've been using JSX syntax in the main runtime.js file. The runtime is one of the first files included in the bundler. Using JSX there was making it import react internals, which impacted the order of the modules being loaded. Apparently, some applications are sensitive to this order, and the runtime shouldn't impact it.
The fix was to move JSX code inside of wrapper.js that is loaded lazily and hence doesn't impact the order of modules being processed when bundle is loaded.
1. Run react-conf-app example (should successfully start)
2. Add `setWrapperComponentProvider` call to one of the other test apps to make sure the fix from #616 is still …
=> Remove JSX code from main runtime.js file

packages/vscode-extension/src/project/project.ts
This PR stops focus on debug panel when debug was paused if the IDE is located in side panel, to avoid hiding it when debugger is used. 
Run ide in side panel and use debugger, then do the same in the tab panel.
=> Don't focus on debug panel if it means hiding IDE

packages/vscode-extension/lib/runtime.js, packages/vscode-extension/src/debugging/DebugAdapter.ts
This PR fixes the problem with debugger ignoring uncaught errors after reloading JS. Because errors Global Handler  was only set on first connection to the debugger it would not be added after reload. The solution was to move the logic of setting the handler to happen on debugger event that is triggered both on first and consecutive application loads. 
1. Run Test application and cause error
2. reload JS 
3. repet step 1). Before the change it would pass the error to the debug console and not stop the application
4. Test it both on application using RN version older then 76 and 76. 
Additional changes:
this PR also hides related internal logging from the users debug console
=> Fix handling of uncaught errors

packages/vscode-extension/src/webview/components/Preview.css, packages/vscode-extension/src/webview/components/ZoomControls.tsx, packages/vscode-extension/src/webview/hooks/useResizableProps.tsx
This PR fixes the issue where the "fit" mode causes indefinite shrinking of the device display. Included changes:
- sets a minimum device height of 350px in the CSS, which restricts the "fit" mode
- adds minimum zoom level of 0.4 (`MIN_ZOOM_LEVEL`) to prevent excessive zooming out
Fixes #654 
- `MIN_ZOOM_LEVEL` and minimal device height in CSS settings were chosen and tested on a 14-inch MacBook 
- Select "fit" mode and adjust the tab's height. Use the zoom out button to zoom out as far as possible. In both cases, ensure that the minimum device size display remains readable.
before:
https://github.com/user-attachments/assets/5fbb86e1-ad9f-4338-9070-6679d9b26d08
after:
https://github.com/user-attachments/assets/8fa2437d-fa49-4702-8464-89652a21e8f6
=> Set minimum size for the device in zoom controls

packages/vscode-extension/src/devices/IosSimulatorDevice.ts
This PR removes the "previous app button" from top left corner of the ios simulator. Before this change If the user switched workspaces without shouting down the ios simulator, the button pointing to the previous app would appear in top left corner of the application. Clicking the button would break the IDE functionality as there is no way of navigating through the simulator and the only way to recover would be to restart app process (which would still  leave the button in the corner).
The solution it to terminate any open applications before launching a new one. 
- open an application ios using IDE
- switch workspaces without closing ide 
- in the new workspace open the ios application using the same device 
- switch workspaces back to the original one without closing ide
=> Remove previous app button

packages/vscode-extension/src/debugging/DebugAdapter.ts
This PR fixes the issue with the heuristic checking if the parsed script is the main bundle, in some RN versions the module `__prelude__` is called `/__prelude__ ` instead, so we change the logic to match both possibilities  
- Run RN 76 test app and set a breakpoint in changed line if on the first pass isMainBundle is true everything works as expected.
=> Fix the Debugger.scriptParsed event handling

packages/vscode-extension/src/project/metro.ts
In Expo 52, the metro /reload endpoint has been moved to a new location. As a consequence we couldn't perform JS reloads which resulted in the app being stuck in "reloading" state.
This PR updates the way we trigger reload action. A while ago, we switched the mechanism for triggering devMenu to use /message endpoint. This endpoint is also capable of handling reload command. Here, we are swapping out the reload implementation to use the /message websocket endpoint to deliver it. This method is more portable and work across older version while also being supported by expo SDK 52 (given https://github.com/expo/expo/issues/32399 is published)
Fixes #664
1. Use reloads and dev menu across different projects, specifically older ones like RN 73, expo-go and on Expo 52 (not yet added here as test …
=> Use websocket /message endpoint to deliver reload request

packages/docs/docs/getting-started.md
We no longer have a generic discord channel and instead prefer communication on Github. The discord channel is currently only available for supporter's license holders. Therefore I'm deleting the link to discord to avoid confusion.
=> Remove discord section in docs

packages/vscode-extension/src/builders/PlatformBuildCache.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/utilities/throttle.ts
When testing Radon I encountered an issue with newly cloned repo in which the IDE would generate an excessive number of npm subprocesses. The issue turned out to be related to fingerprint library, which on some occasions can spawn at least three npm processes. The main problem though was that this problem was amplified by the fact we'd request fingerprint calculation upon the watched files update. Even though the requests were throttled, because they'd take significant time to compute, we'd end up spawning many concurrent processes. This was specifically noticeable at the moment when the project was installing node modules which generates a ton of fs events that resulted in the fingerprint calculation getting triggered.
The solution this PR is implementing is to add a new throttling …
=> Refactor throttling logic for async function

packages/vscode-extension/src/builders/BuildManager.ts, packages/vscode-extension/src/builders/buildIOS.ts
In #587 we updated the way we build iOS apps. We started extracting the SDK from the selected device, and using that for the build. Apparently, the assumption that the installed SDK matches the simulator SDK isn't necessarily correct.
When new SDK is released and xcode is updated, the previous versions of SDK seem to get deleted. This isn't true for simulator runtimes. As a result, simulators can continue to use older runtimes while it is no longer possible for xcodebuild to access these.
In this PR, we are updating iOS build pipeline to use "iphonesimulator" without specifying the exact version. This turns out to be handled well by xcodebuild and allows it to select the most recent, available SDK.
1. Create iOS device with iOS 17 runtime (make sure you don't have SDK 17 installed by …
=> Update iOS builds to use latest iOS SDK

packages/vscode-extension/src/devices/DeviceBase.ts, packages/vscode-extension/src/devices/IosSimulatorDevice.ts, packages/vscode-extension/src/devices/preview.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts
This PR adds text paste support on iOS.
For Android, we use simulator-server to pass paste command. On iOS that was tricky to do and since there's a simctl command for paste we can use that instead.
In this change, we are overriding the sendPaste implementation for iOS that uses simctl pbcopy command that expects the pasted text to be sent via standard input.
In addition, we disable sending cmd+v key combination as HID keys to the simulator. It turned out to result in a buggy behavior when sometimes the key combination would trigger paste action and actually paste text into a focused text input, while most of the times it'd just do nothing. There were also instances where the previous text was pasted instead. Blocking this behavior isn't ideal but it puts iOS functionality in pair with …
=> Support text paste on iOS

packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts
This PR fixes an issue with setting android device GPS coordinates. The command `adb emu geo fix` that we use to set the location has a bug that causes it to not work when coordinates 0 0 are passed. The fix changes 0 0 to 0.00001 0.00001 instead. 
The fix is worthwhile as 0 0 is a natural think to type into the coordinates box when you want to just check is your application responses in any way to the change in location. (this is how the bug was discovered) 
- run android emulator 
- open google maps 
- change location to 0 0
=> Fix setting a 0 0 coordinate on Android  

packages/vscode-extension/src/dependency/DependencyManager.ts
In #457, we added a concept of stale pods flag, that was used to mark whether pod install command should run as a consequence of node_modules.
Since that time, I got bitten by this setting causing unexpected rebuilds to the point where some projects I'm testing run native build every single time despite no change in fingerprint.
In general I don't like the fact we are adding additional state to facilitate checks that seemingly can be done offline. From my testing, I'm now a bit confused as to what was the purpose of this flag as #457 lacks a proper description and we also don't have any inline comments about this flag and related code. Therefore I'm assuming that the purpose of it was that we trigger pod installation if we had to reinstall node_modules. However, this still seem to not be …
=> Remove stalePods checks from dependency manager to fix rebuild issues

packages/vscode-extension/lib/wrapper.js, test-apps/react-native-76/babel.config.js, test-apps/react-native-76/package-lock.json, test-apps/react-native-76/package.json
This PR fixes issue with Radon IDE not working with recent versions of react compiler.
We've been testing Radon with some previous versions of the compiler where this issue didn't occur. I only recently stumbled upon it when testing an app that was using a most recent version of the compiler.
The issue I started seeing is when compiler was enabled, I would get errors about react-compiler-runtime not being a function when accessed from the wrapper component. I'm assuming this has to do with wrapper component being injected by the IDE babel plugin which may confuse babel which while processes the file with react runtime plugin may not properly link the runtime imports which are necessary for React 17 and 18.
For the time being, the fix is to disable react compiler at the wrapper file level. …
=> Disable react compiler for app wrapper to workaround runtime issues

packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/devices/DeviceBase.ts, packages/vscode-extension/src/devices/preview.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/DeviceSettingsDropdown.tsx, packages/vscode-extension/src/webview/providers/ProjectProvider.tsx
This PR add option to show touches on the device screen and on replays.
As part of this PR:
1) We're updating simulator server version to include changes necessary for drawing touch pointers
2) We're adding new device setting for showing touches
3) We're renaming "screen recording" section to "screen settings" as it now includes both "screen recording" and "show touches" options.
1. Run one of the test apps
2. Enable show touches -> start pressing the screen to see touch indicator
3. Record video to see the indicator being visible on the recording
4. Disable show touches option to see them gone
=> Add option to display screen touches

packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts
In #475 we accidently broke the functionality that'd allow users to tap on "waiting for app to load" text in order to reveal the device preview.
This option was pretty handy specifically to troubleshoot issues when app gets stuck because of expo devclient onboarding dialog.
This PR brings back the callback-based code that got removed in #475 with small adjustments as the underlying implementation from deviceSession got split into two separate methods in the meantime.
1. Run expo dev client 51
2. Use "reinstall app" option, the app would get stuck on the waiting to load screen
3. Click on the "waiting to load" text to reveal preview – after this change you should be able to see the preview, without this change the button would do nothing as the frontend code doesn't have access to the …
=> Bring back ability to reveal preview when stuck on waiting

packages/vscode-extension/lib/babel_transformer.js, packages/vscode-extension/lib/metro_helpers.js, packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/project/metro.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/UrlBar.tsx, packages/vscode-extension/src/webview/hooks/useNativeRebuildAlert.tsx
When working on a single project with IDE and from CLI interchangeably, metro cache may cause bundling issue because of the way we override files in babel transformer. This can happen when transformed output of certain files, for which we modify the source code is cached. Although I couldn't find a reliable way of reproducing this problem, it seem to randomly pop up when building from CLI and then using the IDE, and can surface via the CLI bundler or the IDE bundler.
To workaround this problem, we are using cacheVersion metro configuration option. This lets the IDE to generate its own, unique cache keys such that to avoid cache collisions between the metro started via CLI and in the IDE. 
Here's a breakdown of changes we're making here:
1) We're adding cacheVersion config option to metro …
=> Fix metro cache issue when running project from CLI and IDE interchangeably

packages/vscode-extension/src/debugging/DebugAdapter.ts
This PR adds a proper cleanup of debugger threads and source maps when the runtime is cleared fixing the issue where multiple hermes instances would appear in the threads section of the debugger after reloads.
Fixes #703
In this PR we utilize the `Runtime.executionContextsCleared` CDP message to delete virtual threads that we create in `Runtime.executionContextCreated` to track hermes VM instances.
We also update that message handler to clear source maps object as it is associated with the running VM, so when the VM reloads we need to propagate source maps again (which already happens).
1. With old and new debugger (i.e. on RN76 and epxo-router projects) try the below
2. Set breakpoint, make sure the debugger stops
3. Reload JS several times
4. Observe there are no additional hermes …
=> Fix debugger threads not being cleaned up properly

packages/vscode-extension/lib/wrapper.js
This PR fixes problem with preview functionality being broken on React Native 76 (and on Fabric specifically).
The root cause was in the missing parameters we send to AppRegistry.runApplication
On React Native 76, the renderer expects to receive `fabric` parameter and also optionally `concurrentRoot` parameter that is placed under `initialProps` objects. Because of the fact both of those parameters were missing, rendering of the Preview container would throw weird error about missing createElement and similar methods.
The fix is to capture `initialProps` and `fabric` attributes from the original app wrapper, and forward them when calling AppRegistry.runApplication later on.
1. Open RN 76 example
2. Launch preview – before nothing would happen and there'd be a wall of errors in the …
=> Fix preview on RN 76

packages/vscode-extension/src/webview/views/ManageDevicesView.css, packages/vscode-extension/src/webview/views/ManageDevicesView.tsx
This PR improves the appearance of the ManageDevicesView button group. On hover, buttons now have a circular background shape instead of the previous elliptical shape. Additionally, tooltip texts have been updated.
Fixes #706 
Before:
After:
=> Update ManageDevicesView buttons hover

packages/vscode-extension/src/webview/styles/theme.css
Fixes #702 
Set theme to `Dark High Contrast` or `Light High Contrast` in vscode and open any app in extension. Check appearance of component:
- any dialog/modal
- any popup
- tooltips
- buttons
- inspector menu
- inspector overlay
- device settings
- manage devices
- replay overlay
- replay UI
=> Fix appearance on high contrast themes

packages/vscode-extension/src/webview/components/DeviceSelect.tsx, packages/vscode-extension/src/webview/components/DeviceSettingsDropdown.tsx
This PR removes unnecessary shadow inside the device settings dropdown and manage devices select on light mode. 
This visual change shouldn't have any effect on the dark mode.
Run the extension on both light and dark mode to test.
=> Fix light theme shadows

packages/vscode-extension/src/webview/components/DeviceSettingsDropdown.css, packages/vscode-extension/src/webview/components/DeviceSettingsDropdown.tsx, packages/vscode-extension/src/webview/components/shared/Dropdown.css, packages/vscode-extension/src/webview/styles/theme.css
This PR simplifies the Device Settings UI by reordering items and removing unnecessary labels. It also adds shadows to `--swm-backdrop-shadow` in dark theme to visually distinguish them from the background.
|Before|After|
|-|-|
|<img width="522" alt="Screenshot 2024-11-18 at 10 57 30" src="https://github.com/user-attachments/assets/153e56c6-4d79-47da-8ae7-fa70ac48e22f">|<img width="501" alt="Screenshot 2024-11-18 at 13 07 51" src="https://github.com/user-attachments/assets/60710772-86b0-4c8e-ae0b-3007cedf4659"><img width="501" alt="Screenshot 2024-11-18 at 13 06 56" src="https://github.com/user-attachments/assets/0b94a980-c129-499b-9e97-1abd04f97c15">|
=> Simplify Device Settings menu

packages/vscode-extension/src/webview/components/DeviceSettingsDropdown.tsx, packages/vscode-extension/src/webview/components/SettingsDropdown.tsx, packages/vscode-extension/src/webview/components/shared/Dropdown.css
This PR addresses the issue of inaccessible submenus when the side panel is too narrow.
Fixes #669 
|Before|After|
|-|-|
|<img width="373" alt="Screenshot 2024-11-18 at 16 20 11" src="https://github.com/user-attachments/assets/a279c90a-56c2-4fef-98a0-b13e33b42ba6">|<video src="https://github.com/user-attachments/assets/a0749108-49fc-4d57-b554-db04fa303e39" />|
=> Fix inaccessible context menu on narrow window

packages/vscode-extension/src/webview/components/ReplayOverlay.tsx
This PR shortens duration of rewind animation to improve the usability of the rewind feature.
Ensure that the duration of the replay takes 0.6sec.
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/68c8354f-49b7-4d1e-af49-11230540591e"/>|<video src="https://github.com/user-attachments/assets/c03b42f3-ec96-4174-8418-bf596b62a2a2" />|
=> Shorten duration of replay rewind animation

packages/vscode-extension/src/project/deviceSession.ts
This PR fixes log counter multiplication after, either `restartProcess`  or `reinstall` reload options. It was caused by the old DebugSession not being disposed of. 
To solve the issue we dispose the old debag session before creating a new one.
- run any application and reload it using  `restartProcess`  or `reinstall` 
- check if the log counter works as expected
=> Fix log counter multiplying itself after reload 

packages/vscode-extension/src/devices/IosSimulatorDevice.ts, packages/vscode-extension/src/utilities/common.ts, test-apps/react-native-76/ios/Podfile.lock
The motivation of this PR is to pass native logs to Radon IDE. Currently, if the app crashes on the native side developer needs to open Xcode anyway.
⚠️ DISCLAIMER: The current approach won't work with Expo Go and Expo Dev Client, as those are run through deep link not `xcrun simctl launch`. 
I tried: `xcrun simctl --set {deviceLocation} spawn booted log stream`, `react-native log-ios`, looking through files in the container if there is something that looks like logs - none of those work. 
<s>What I did:
- add params to `xcrun simctl launch`  that print `stderr` and `stout` to file,
- watch for changes in this log file,
- send new chunks into VSCode output.</s>
**Changed during review:**
What I did:
- add `--console` param to `xcrun simctl launch`, which logs the process output 
- …
=> [iOS] Add native logs 

packages/vscode-extension/src/builders/eas.ts, packages/vscode-extension/src/panels/LaunchConfigController.ts, packages/vscode-extension/src/webview/hooks/useBuildErrorAlert.tsx, packages/vscode-extension/src/webview/providers/LaunchConfigProvider.tsx
This PR adds additional user facing information about eas builds, to let users know when production build is used instead of development one. More over eas build crashes are getting a new build error alert description to redirect users to Radon IDE log instead of non existing build logs.
Finally this PR adds .apk file extension to android packages to avoid errors with tools we use to install and uninstall application on device.
Fixes android portion of  #678
Run an application using eas on android using production and development profiles.
=> Fix Eas builds on Android

packages/docs/docs/guides/troubleshooting.md
Extend troubleshooting guide by mentioning native logs channels.
vercel preview
=> Document native logs option

packages/vscode-extension/src/webview/components/shared/Dropdown.css
This PR ensures the `KeybindingInfo` component is consistently aligned to the right within the `.dropdown-menu-item-content` container.
|Before|After|
|-|-|
|![Screenshot 2024-11-22 at 17 09 34](https://github.com/user-attachments/assets/f2026644-dcd9-45ad-b539-fa3cc8f6d091)![Screenshot 2024-11-22 at 17 09 23](https://github.com/user-attachments/assets/410dfdcb-c299-4342-a785-005b87d39972)|![Screenshot 2024-11-22 at 17 08 39](https://github.com/user-attachments/assets/fe6e186a-7441-4cde-b434-34ade68469b1)![Screenshot 2024-11-22 at 17 09 03](https://github.com/user-attachments/assets/3b3c0945-e6aa-4318-92a9-3d0404dc84a0)|
=> Align KeybindingInfo to the right edge in settings

packages/vscode-extension/src/webview/components/DeviceSettingsDropdown.tsx
This PR introduces a switch for controlling the visibility of the device frame in the IDE panel.
- Toggled the switch to verify that the `Show Device Frame` setting updates correctly and that the device frame visibility is changed accordingly.
- Changed the `Show Device Frame` setting through the VSCode settings and checked if the device settings dropdown reflects this setting correctly after reopening.
Screenshots:
|off|on|
|-|-|
|![Screenshot 2024-11-22 at 16 35 33](https://github.com/user-attachments/assets/f430e927-d90b-4af6-ba6e-52e76e30de21)|![Screenshot 2024-11-22 at 16 35 39](https://github.com/user-attachments/assets/fb5108aa-5bc0-4615-84c1-d18f92283ec7)|
=> Add switch for device frame visibility

packages/vscode-extension/package.json, packages/vscode-extension/src/common/LaunchConfig.ts, packages/vscode-extension/src/dependency/DependencyManager.ts, packages/vscode-extension/src/utilities/packageManager.ts, packages/vscode-extension/src/utilities/requireNoCache.ts
This PR changes how we detect package manager used by the application, to better deal with a situation when a user has multiple lock files in their repository. A situation like that is quite common, because  users sometimes accidentally run `npm install` before checking that the project actually uses yarn. 
Solution: 
- information set up in package.json takes priority, as it is unprovable that set it up accidentally
- in case the information is missing from package.json we still perform the old check but, we send a warning to the console if multiple lock files are detected
- finally we allow user to set up the package manager in launch configuration by hand and than it takes priority 
- run https://github.com/Almouro/react-native-performance-workshop in IDE which has multiple lock files …
=> Fix package manager detection

packages/vscode-extension/src/devices/preview.ts
This PR increases the recording buffer size from 50MB to 2000MB and switches from in-memory to on-disk storage to support up to 10 minutes of video recordings. 
Thanks to @balins, we've established that in a worst-case scenario, video sizes are approximately 125MB/minute on Pixel 7 and 150MB/minute on iPhone 15, ensuring that 2000MB provides a safe margin.
- Ensured that recording functionality remains stable after these updates.
=> increase recording buffer to support 10 minute videos

packages/vscode-extension/lib/wrapper.js
This PR fixes a regression in element inspector on RN 73 introduced in #693 
Because of the new approach of traversing component hierarchy added there, we broke compatibility with older versions of react native where renderer didn't have `getInspectorDataForInstance` method.
The fix is to restore the old behavior as a fallback and rely on component hierarchy returned by `getInspectorDataForViewAtPoint` when this renderer method isn't available.
1. Open inspector hierarchy on expo-go app
2. Make sure inspector works on RN 75 and RN 76
=> Fix inspector on RN 73 after #693

packages/vscode-extension/src/utilities/packageManager.ts
https://github.com/software-mansion/radon-ide/pull/735 uses the `packageManager` variable that comes from launch configuration instead of `manager` that was just matched for the given lock file. This results in packager beeing `undefined`. 
Fixes #760
- Remove node_modules from expo-go project 
- Run IDE in given project
- The IDE should launch
=> Fix package manager undefined

packages/vscode-extension/src/panels/Tabpanel.ts
This PR resolves the issue where selecting a codeLens with a preview or Storybook's preview unintentionally relocates the IDE panel to the editor column to the side of the active one (`ViewColumn.Beside`). The `showIDEPanel` function has been fixed to ensure that the IDE panel remains in the active column, labeled with our IDE's name.
Fixes #761
- The IDE was opened in the left tab and code with a preview in the right tab. After selecting the codeLens, it was confirmed that the IDE remained in its original position.
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/86211141-f8ee-402a-9e65-74681227771e" />|<video src="https://github.com/user-attachments/assets/bdeb37cf-8130-45c9-988d-1c85abb7f75d" />|
=> Fix IDE panel relocation after selecting preview/storybook

packages/vscode-extension/src/builders/BuildManager.ts, packages/vscode-extension/src/builders/PlatformBuildCache.ts, packages/vscode-extension/src/project/project.ts
This PR updates some Logger statements to use Logger.debug instead of Logger.log
Logger.log are dev-only entries but was likely misused in a few places that this PR updates. When using Logger.debug, users will get additional traces for the log statements which is helpful when troubleshooting issues.
n/a
=> Use debug level for logs previously logged with Logger.log

test-apps/react-native-73/.vscode/launch.json, test-apps/react-native-73/ios/Podfile
Fixes #775
This PR fixes the configuration of `test-apps/react-native-73`. Two things changed:
- get rid of Flipper as suggested in https://github.com/facebook/react-native/issues/43335
- force added `launch.json`, which was git ignored by `.gitignore` in `radon-ide` root, imo it makes sense to merge it as this is project specific config, and this is the suggested approach in our docs: https://ide.swmansion.com/docs/guides/configuration#creating-configuration-file
- open `test-apps/react-native-73` using Radon IDE
=> Fix react-native 73 test app configuration

packages/vscode-extension/src/debugging/SourceMapsRegistry.ts
This PR adds try/catch block around source map consumer call. These calls seem to throw a lot of exception, while in some cases it is possible for the code to recover from those errors. The method where we add try/catch would still return `null` indicating the position couldn't be translated. This would result in breakpoints not getting verified and at least giving some visual clues for the users as opposed to just resulting in uncaught exception.
We don't have a good reproducer for the case where source map methods throw this type of exceptions, so this change hasn't been tested apart from just checking that breakpoints continue to work in normal settings.
=> Catch source-map errors when calculating generated location

packages/vscode-extension/src/debugging/BreakpointsController.ts, packages/vscode-extension/src/debugging/CDPBreakpoint.ts, packages/vscode-extension/src/debugging/DebugAdapter.ts, packages/vscode-extension/src/debugging/DebugSession.ts
This PR fixes the issue when breakpoints set before JS reloads on the new debugger would be effectively set twice and we wouldn't have a way of deleting them later on. This issue is a regression introduced in #755
The issue stems from a difference in behavior between old and new debugger. The old debugger, when JS is reloaded, looses all the information about the previously set breakpoints. Thanks to that, we can forget all the breakpoints in our Debug Adapter and rely on VSCode to request setting them again when new context is instantiated (we send InitializedRequest).
On the other hand, the new debugger keeps the breakpoints in between reloads. Therefore, resetting the list of breakpoints in our registry would lead to the cases where we'd set a single breakpoint for the second time with …
=> Fix breakpoints set in between JS reloads when using new debugger

packages/vscode-extension/src/debugging/SourceMapsRegistry.ts
This PR fixes exception reported by a number of users and also seen in telemetry:
`RangeError: Start offset -2033400168 is outside the bounds of the buffer`
The root cause of this issue was in misuse of [source-map](https://github.com/mozilla/source-map) package which requires destroy method to be called on `SourceMapConsumer` instances when they are no longer used.
The reason why `destroy` call is necessary, is that source-map package uses wasm under the hood where it allocates data structures that allows for fast processing of source map translation queries. Since the wasm memory space is limited, when too many maps were loaded in the memory, the allocate call from [parseMappings](https://github.com/mozilla/source-map/blob/3cb92cc3b73bfab27c146bae4ef2bc09dbb4e5ed/lib/source-map-consumer. …
=> Fix sourcemap RangeError issue by properly freeing source map consumers

packages/vscode-extension/package-lock.json, packages/vscode-extension/package.json, packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/devices/preview.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/utilities/license.ts, packages/vscode-extension/src/utilities/simulatorServerBinary.ts, packages/vscode-extension/src/webview/components/SettingsDropdown.tsx, packages/vscode-extension/src/webview/providers/ProjectProvider.tsx, packages/vscode-extension/src/webview/styles/theme.css, packages/vscode-extension/src/webview/views/ActivateLicenseView.css, packages/vscode-extension/src/webview/views/ActivateLicenseView.tsx, packages/vscode-extension/src/webview/views/PreviewView.css, packages/vscode-extension/src/webview/views/PreviewView.tsx
This PR adds a way for the user to register device, using a license key, by adding an an "Activate license" button in place of "report issue" button on the main screen. 
Additionally we add a new report issue button to the settings dropdown.
- An account was created on customer portal and the license was activated.
=> Add license registration

packages/vscode-extension/src/project/project.ts
This PR updates fingerprint throttling such that it runs less often. In practice it doesn't seem like the delay of several seconds makes for an important difference when detecting native changes. When updating native changes most of the time, the refresh would trigger exception regardless of how soon we're able to detect them based on the fingerprint. What is important is to give a clear indication that this was due to native changes getting updated.
On the other hand, to frequent fingerprint calls are annoying in cases a lot of files are invalidated at the same moment (for example when installing node_modules) in which case this process incurs a significant CPU load.
1) run one of the test apps
2) add some comments to Podfile
3) see the native changes dialog pop up
=> Make fingerprint run less often

packages/vscode-extension/src/builders/eas.ts
This PR fixes a regression introduced in #727, that performed android specific check regardless of the platform, causing iOS builds to fail.
-run eas development build on ios
-run eas development build on android
=> Add Platform check when validating EAS builds

packages/vscode-extension/src/builders/buildAndroid.ts, packages/vscode-extension/src/utilities/android.ts
This PR changes the logic for obtaining JAVA_HOME location.
We used to select JDK that's bundled with Android Studio when JAVA_HOME wasn't set in the process.env – the reason for this approach was that in many setups people may not have JAVA available at the default location. However after #515 we can reliably say java should be on the PATH if someone can build their project using CLI.
The reason why the version from the PATH should be preferred is that Android Studio now ships with modern versions of JDK 21 which is not compatible with libraries from the ecosystem. React Native docs recommend version 17: https://reactnative.dev/docs/set-up-your-environment
This PR updates the logic such that we test for JAVA_HOME env variables first, later we check if java is available in PATH, and if …
=> Don't prefer Android Studio's JDK over java from PATH

packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts
When running IDE with Android device and another Android Emulator, the logcat commands fail on `error: more than one device/emulator`. This PR adds selecting a proper device with `-s <serial>` adb param. Similar pattern is used for other adb executions. 
- Run a standalone Android emulator 
- Run project with IDE using an Android device 
- The native logs should appear
=> Fix device android native logs not working when multiple devices are available 

packages/docs/src/pages/legal/supporter-terms.mdx
Fix continuity error in the provided example in the Supporter's license terms
=> Fix typo in legal

packages/vscode-extension/lib/preview.js
This PR fixes fast refresh of previews after a regression introduced in #726
The issue that started occuring in #726 was that previews after getting fast refresh would sometimes fail to render. Here's an example of problematic component: https://github.com/software-mansion-labs/radon-ide-demo/blob/main/src/components/Message.tsx#L21 – when you update emoji list in that component, the render would throw exception when attempting to access styles.
The reason for the above exception was that in #726 we started triggering state updates. However, the state update would be triggered at the point when preview method is called which is before the whole file is executed. As a consequence, we'd still try to render the old version of component that would trigger for hoisted variables – in this …
=> Fix fast refresh for previews after #726

packages/vscode-extension/package.json
Fixes #821
Currently, we look for different files in the root of the workspace to recognize if VSCode should activate the extension, this doesn't work in monorepo, as those files might be deeper in the file tree. This pr adds `**/` before each pattern to fix that. 
- Open nx-monorepo 
- Confirm the "Open IDE Panel" is visible 
- Repeat for any other repo
=> Fix monorepo structure not triggering activation in VSCode

packages/docs/src/css/overrides.css
Compatibility tables were unreadable on mobile devices.
https://github.com/user-attachments/assets/2c53f9ec-ac03-462b-8a92-2dbb2f7096f6
https://github.com/user-attachments/assets/205274a4-fd0b-4b7f-91e0-272d59142220
=> Fix compatibility table responsiveness

packages/vscode-extension/src/webview/components/shared/Select.css, packages/vscode-extension/src/webview/components/shared/Select.tsx, packages/vscode-extension/src/webview/styles/theme.css, packages/vscode-extension/src/webview/utilities/consts.ts, packages/vscode-extension/src/webview/views/CreateDeviceView.css, packages/vscode-extension/src/webview/views/CreateDeviceView.tsx
This PR adds a warning for users trying to install older versions of android on newer devices, as they may not be compatible.
We opt to still allow users to ignore the warning because android studio allows installing any sdk on any emulator. 
- pixel 9 with sdk 35 has a status bar overflowing the device frame
- open manage devices modal and click through possibilities
=> Add a warning for users trying to use android sdks older then selected device

packages/docs/docusaurus.config.js, packages/docs/src/components/CloseIcon/index.tsx, packages/docs/src/components/FaqList/FaqItem/styles.module.css, packages/docs/src/components/Hero/StartScreen/index.tsx, packages/docs/src/components/Hero/StartScreen/styles.module.css, packages/docs/src/components/LearnMore/LearnMoreFooter/index.tsx, packages/docs/src/components/LearnMore/LearnMoreFooter/styles.module.css, packages/docs/src/components/LinkButton/index.tsx, packages/docs/src/components/LinkButton/styles.module.css, packages/docs/src/components/Pricing/PricingCard/styles.module.css, packages/docs/src/components/Pricing/PricingPlansList/styles.module.css, packages/docs/src/components/Pricing/styles.module.css, packages/docs/src/components/SecondaryButton/index.tsx, packages/docs/src/components/SecondaryButton/styles.module.css, packages/docs/src/components/Sections/FAQ/styles.module.css, packages/docs/src/components/Sections/Installation/InstallationStep/styles.module.css, packages/docs/src/components/Sections/Installation/styles.module.css, packages/docs/src/components/Sections/Overview/OverviewItem/index.tsx, packages/docs/src/components/Sections/Overview/OverviewItem/styles.module.css, packages/docs/src/components/Sections/Overview/styles.module.css, packages/docs/src/pages/index.module.css, packages/docs/src/pages/legal/index.module.css, packages/docs/src/pages/pricing.module.css
This PR:
- changes the main CTA from `Download from VSCode Marketplace` to `Get started for free`,
- adds `View demo` modal,
- adds `Get started` buttons in the feature overview section under each feature,
- changes the bottom CTA from  `See the video` to `Try Radon IDE free`,
- hides the product hunt announcement bar
- improves styles on mobile
https://github.com/user-attachments/assets/bb5f9603-f086-4f2f-984e-a9ed1f5843c2
=> Update CTAs 

packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts, packages/vscode-extension/src/extension.ts, packages/vscode-extension/src/utilities/android.ts, packages/vscode-extension/src/utilities/platform.ts, packages/vscode-extension/src/utilities/simulatorServerBinary.ts, packages/vscode-extension/src/utilities/subprocess.ts, packages/vscode-extension/src/utilities/utils.ts, packages/vscode-extension/src/webview/components/Preview.tsx, packages/vscode-extension/src/webview/providers/UtilsProvider.tsx, packages/vscode-extension/src/webview/views/CreateDeviceView.tsx
This PR adds Linux support to the VSCode extension, implementing platform-specific paths and configurations. The changes follow patterns established in PR #462 (Windows support) and make the extension functional on Linux systems.
- Add Linux as a supported platform in Platform module
- Implement Linux paths for Android SDK and tooling
- Add Linux-specific configurations for file system and processes
- Update UI components to handle Linux keyboard shortcuts
Fixes #688
To ensure the changes in this PR work as expected, the following test plan was carried out:
- Run development version of the extension successfully on my Linux Mint (based on Ubuntu 24.04) machine. 
- Ensure the ANDROID_HOME 
environment variable was correctly set on my system 
- A React Native project was initialized, and …
=> Add Linux support for VSCode extension (#688)

packages/vscode-extension/src/webview/views/ActivateLicenseView.css, packages/vscode-extension/src/webview/views/ActivateLicenseView.tsx
This PR introduces a confirmation for successful license activation and fixes the box-shadow cut in the "Activate" button's right bottom corner.
- Tested by activating the license using both correct and incorrect keys to ensure the system responded properly in each scenario.
Screenshots:
Before:
=> Add license activation confirmation

packages/vscode-extension/src/common/DependencyManager.ts, packages/vscode-extension/src/dependency/DependencyManager.ts, packages/vscode-extension/src/webview/providers/DependenciesProvider.tsx, packages/vscode-extension/src/webview/views/DiagnosticView.tsx
This PR adds a package manager status info to the DiagnosticView, this update will help identify issues from using the wrong package manager, especially when multiple lock files are present in a workspace.
It also introduces a new `details` field to the DependencyStatus type. This field stores the name of the detected package manager and can also hold version numbers or other relevant details for future needs.
- Tested on project with various package manager configurations (supported, unsupported, installed, uninstalled) set in the launch settings.
- Tested on project without package manager lock files and with different lock files (`yarn.lock`, `package-lock.json`, `pnpm-lock.yaml`, `bun.lockb`).
- Verified that an error is displayed in the Diagnostic view when no package manager is …
=> Add package manager to DiagnosticView

packages/vscode-extension/src/utilities/packageManager.ts
This PR resolves the incorrect marking of the Node Modules dependency as uninstalled when a project lacks a `package.json` file.
The issue occurred because the functions `isNpmModulesInstalled` and `isYarnModulesInstalled` did not check for an empty parsedOutput, which is the result of the `npm ls --json` command. Previously these functions mistakenly returned true when parsedOutput was empty. Now, they correctly return false if parsedOutput is empty.
- Tested scenarios with and without a `package.json`, lock files, and the `node_modules` folder  to ensure accurate dependency status.
|Before|After|
|-|-|
|<img width="766" alt="Screenshot 2024-12-10 at 10 00 39" src="https://github.com/user-attachments/assets/b0f82c42-5dda-429c-8924-b0b75844ad6e">|<img width="766" alt="Screenshot …
=> Fix Node Modules detection without package.json

packages/vscode-extension/src/webview/components/Preview.css
This PR addresses the issue where the phone screen was not centered vertically within narrow IDE window.
|Before|After|
|-|-|
|![Screenshot 2024-12-13 at 11 09 57](https://github.com/user-attachments/assets/50c3eacd-5fb2-4675-b1d4-568474480aaa)|![Screenshot 2024-12-13 at 11 09 51](https://github.com/user-attachments/assets/b6521d20-c032-4d0a-98e0-699dde3870fd)|
=> Fix vertical centering of phone screen in narrow IDE window

packages/vscode-extension/lib/expo_router_plugin.js
This PR hides expo-routers internal parameter called __EXPO_ROUTER_key from being used when building the display URL we show in the URL bar.
This parameter is being automatically generated and doesn't carry any meaningful information for the user, hence we can hide it from appearing in the URL bar. The parameter is still kept in router params, so this change doesn't impact the behavior when switching between the routes, it only impacts the representation of that route in the URL bar.
1. I wasn't able to reproduce this on the project where that option appears, so the testing ewas limited to expo-router examples from test-apps and I verifies that nothing broke there
=> Hide expo-router's internal __EXPO_ROUTER_key from displayURL

packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/PreviewLoader.tsx
This PR solves an issue with reload, clean rebuild and clear metro cache functionality when debugger was not attached. 
Because the above methods caused debug session to be disposed be triggered a session getter which throws error when debugger does not exist, breaking the flow of the reboot. To solve that issue we use `this.vscSession` instead. 
Additionally debugging this issue reveled that initial state of the `reload` functionality is trigering initially startup message "attaching debugger" because that is the last one that was set by initial startup process. To fix that we immediately set it to "restarting" similarly to how we did it in `restart` method. 
To avoid progress bar jumping back and forth we set the progress of "restarting" to 0.
- add `return undefind` at the beginning of …
=> Improve the reloading experience

packages/vscode-extension/src/webview/components/Preview.css
This PR addresses the issue of a scrollbar appearing when the IDE window is narrow and the device frame is hidden.
The scrollbar appeared because the `touch-area` for edge swipe gestures extends beyond the phone content width. To fix this, `overflow: hidden` is applied for windows narrower than 415px to override `overflow: auto` in `phone-wrapper`.
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/ed75fdb6-7090-4e6a-a13e-c8bd864df648" />|<video src="https://github.com/user-attachments/assets/c9ba00e3-1ad9-47ab-8182-f31a0d4de055" />|
=> Hide scrollbar in narrow IDE window with hidden device frame

packages/vscode-extension/src/webview/utilities/localeList.json
This PR adds missing Hebrew localeIdentifierto the `localeList.json`.
- Tested following the test plan from #590 (same for iOS).
|Before|After|
|-|-|
|<img width="484" alt="Screenshot 2024-12-17 at 17 10 02" src="https://github.com/user-attachments/assets/24721583-6d19-4c9d-b14f-96f882de92cd" />|<img width="477" alt="Screenshot 2024-12-17 at 17 19 23" src="https://github.com/user-attachments/assets/efc0c7ae-1ae7-444e-b123-aad738ce6334" />|
|iOS|Android|
|-|-|
|<img width="562" alt="" src="https://github.com/user-attachments/assets/c85ab9bd-e791-48ca-90fc-675cfdc15720" />|<img width="562" alt="" src="https://github.com/user-attachments/assets/1efa550e-67a2-4afc-99cd-d716ade4c743"/>|
=> Add Hebrew to locale list

packages/vscode-extension/package.json
This PR fixes an issue that occurred on fresh clones of the repository. In  #846 we added a new submodule `vscode-js-debug` along with preinstall actions that should build it. This PR adds initialization to that flow so the command works on fresh clones as well.  
run:
- `git clone git@github.com:software-mansion/radon-ide.git` 
- `cd packages/vscode-extension`
- `npm i` 
everything should work
=> Fix vscode-js-debug submodule initialization

packages/vscode-extension/src/builders/buildAndroid.ts, packages/vscode-extension/src/builders/buildIOS.ts, packages/vscode-extension/src/dependency/DependencyManager.ts, packages/vscode-extension/src/devices/DeviceManager.ts, packages/vscode-extension/src/panels/WorkspaceConfigController.ts, packages/vscode-extension/src/project/project.ts
This PR adds more detailed telemetry to the Radon IDE project, we add the following list of events: 
-  `build:expo-go-requested`
-  `build:eas-build-requested`
-  `build:custom-build-requested`
-  `build:pod-install-failed`
-  `device-manager:create-device`
-  `device-manager:remove-device`
-  `workspace-configuration:panel-location-changed`
-  `workspace-configuration:show-device-frame-changed`
-  `recording:start-recording`
-  `recording:capture-and-stop-recording`
-  `replay:capture-replay`
-  `url-bar:reload-requested`
-  `url-bar:go-home`
-  `url-bar:restart-requested`
-  `device-settings:update-device-settings`
run all the tracked functionality and check if it appears in the data base
=> Add additional telemetry to better understand the problems with the application

packages/vscode-extension/src/webview/providers/AlertProvider.tsx, packages/vscode-extension/src/webview/providers/DependenciesProvider.tsx, packages/vscode-extension/src/webview/providers/DevicesProvider.tsx, packages/vscode-extension/src/webview/providers/LaunchConfigProvider.tsx, packages/vscode-extension/src/webview/providers/ProjectProvider.tsx, packages/vscode-extension/src/webview/providers/WorkspaceConfigProvider.tsx
this PR prevents unnecessary rerenders caused by setting states inside objects therefore triggering rerender even f the value didn't change.
Run test application and see if it works as expected.
=> Improve performance with useMemo

packages/vscode-extension/src/extension.ts, packages/vscode-extension/src/panels/SidepanelViewProvider.ts, packages/vscode-extension/src/panels/Tabpanel.ts, packages/vscode-extension/src/providers/PreviewCodeLensProvider.ts
Fixes #278
This PR refactors logic related to opening previews. We were using `showIDEPanel` for `RNIDE.showPanel`/`RNIDE.openPanel` commands, the launch preview depended on the existence of the `fileName` and `lineNumber`. The problem is that VSCode passes its arguments there, but instead number in lineNumber we get an object with the panel's id, which triggers this logic always. Thus, I refactored the opening preview to use a separate command. 
Additionally, startPreview was running even if the project wasn't set up yet, which led to an error that we used `.project` on `null`. Now, we open the panel and show a warning in that case. 
Repeat those scenarios for preview both in `tab panel` and `side panel`: 
**Steps:**
- Close the IDE panel
- Reopen (or restart if in debug mode) VSCode 
- …
=> Refactor open preview logic

packages/vscode-extension/lib/wrapper.js
This PR fixes a bug that occur when using "home" button to close preview on new architecture.
In #712 we fixed previews for new architecture. With the new architecture, it is required for AppRegistry to get `fabric` attribute specified when rendering the app. We began to use it for new architecture when launching previews. However, the "home" button runs a different code paths when use from within the app and when triggered while in preview mode. When in "preview" mode, the home button also uses AppRegistry to launch the main app bundle back again. In #712 we missed that and only been applying fabric prop when launchin preview but not when launching the main bundle. This PR fixes this by adding fabric prop to AppRegistry calls that are triggered when using home button in preview mode. …
=> Fix home button when closing preview on fabric

packages/vscode-extension/lib/wrapper.js, packages/vscode-extension/src/extension.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts
Currently Radon IDE preview is limited to files that are loaded by the main application bundle. This is because the requested preview component need to register in runtime. While we eventually want to support such a case (have an issue open here #31), currently there's no visible way for the user to tell when they attempt to open not-loaded preview.
This PR adds a way to communicate back an error due to preview not being loaded for specific key and displays an error message in the IDE to indicate the source of the issue.
1. Open example app with preview installed
2. Make sure the existing prviews work as expected
3. Add new file that isn't loaded by any of the existing files (not a route file either). And add preview there.
4. Use "open preview" in that new file to see the new error …
=> Provide visible feedback when attempting to start preview for non loaaded source file

packages/vscode-extension/src/debugging/DebugAdapter.ts
This PR add fetching a source map when received `sourceMapUrl` is actually an URL and not a encoded source map.
- Run react native 77 app and det debugger functionality  
- run react native 76 app and test debugger functionality
=> Fix fetching source map on react native 77

packages/vscode-extension/src/webview/components/UrlBar.tsx, packages/vscode-extension/src/webview/components/UrlSelect.tsx
This PR changes the UrlBar behaviour in projects not using Expo Router navigation.
When the user intends to close the preview by pressing the goHome button (or reload), the UrlSelect's trigger value needs to be reset to a placeholder ("/"). 
Additionally, this update disables the `goBack` button for projects that do not use Expo Router.
- Tested on expo-router and react-native-76 apps.
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/3fa5b50a-c5c3-4f70-b184-f7a1853f101b" />|<video src="https://github.com/user-attachments/assets/051577d3-5f43-454c-92b8-eefdd1d37426" />|
=> Fix UrlSelect trigger value reset for non expo router projects

packages/vscode-extension/src/webview/components/DeviceSelect.css, packages/vscode-extension/src/webview/components/DeviceSettingsDropdown.tsx, packages/vscode-extension/src/webview/components/IconButtonWithOptions.css, packages/vscode-extension/src/webview/components/ReplayOverlay.css, packages/vscode-extension/src/webview/components/SettingsDropdown.tsx, packages/vscode-extension/src/webview/components/UrlSelect.css, packages/vscode-extension/src/webview/components/ZoomControls.css, packages/vscode-extension/src/webview/components/shared/Alert.css, packages/vscode-extension/src/webview/components/shared/Button.css, packages/vscode-extension/src/webview/components/shared/IconButton.css, packages/vscode-extension/src/webview/styles/theme.css, packages/vscode-extension/src/webview/views/PreviewView.css
This PR reduces the amount of margins between buttons in order to make it easier to fit more UI controls while also giving the device preview as much space as possible in the panel.
We've been struggling with fitting all the buttons that we needed in the panel. Specifically after adding screenshots and tools buttons to the top bar. While we may want to eventually group some of the functions (i.e. ones responsible for recording/screenshots) as proposed in #819 it still seems like we're not using our space efficiently enough.
For example, the size of the icons is the same as with all the editor button bars that VSCode renders, while we only add a significantly big paddings around these. The buttons in VSCode are functional and for users who need them to be bigger, can adjust that by …
=> Reduce spaces between icons on top and bottom bars in the IDE panel UI

packages/vscode-extension/src/webview/components/InspectDataMenu.css, packages/vscode-extension/src/webview/components/InspectDataMenu.tsx
This PR addresses a gap in the split lines of dimensions in the InspectDataMenu by removing space characters from the displayDimensionsText and reducing the line-height.
Fixes #861 
|Before|After|
|-|-|
|<img width="262" alt="Screenshot 2025-01-10 at 10 39 01" src="https://github.com/user-attachments/assets/5654ba28-6322-4056-9c08-36459bbcca57" />|<img width="262" alt="Screenshot 2025-01-10 at 10 38 44" src="https://github.com/user-attachments/assets/f413ddad-b3e9-4e2e-8914-6e6196951ab5" />|
=> Fix gap in split lines of dimensions in InspectDataMenu

packages/vscode-extension/src/utilities/packageManager.ts
In Bun v1.1.39, a new text-based lockfile  (`bun.lock`) was introduced: https://bun.sh/blog/bun-lock-text-lockfile
Without this change, when the text-based lock file is used, Radon would pick up npm as the package manager. It would then generate a `package-lock.json`.
A workaround is to keep the old `bun.lockb` file even with the new text-based lockfile.
1. On a bun project, run `bun install --save-text-lockfile`.
2. Remove the `bun.lockb` file.
3. `Clean rebuild` on Radon.
Without this change, a `package-lock.json` file will be generated.
Followed the instructions [here](https://ide.swmansion.com/docs/guides/development) and verified that the `package-lock.json` is not being populated.
=> Add support for Bun's text-based lockfile in packageManager.ts

packages/vscode-extension/src/webview/styles/theme.css
In #893 we updated styles to increase available space for icon buttons and for simulator.
Apparently #893 introduced an error, because the button size constant was only being set for dark theme and not for the light one.
This PR fixes this error by moving the definition of that size variable to the root object instead of keeping it to be theme-specific.
Before:
After:
1. Open IDE in light mode.
2. Check if it looks good in dark mode too
=> Fix light theme styles after #893

packages/vscode-extension/src/utilities/subprocess.ts
Fixes #896 
This PR solves the problem of IDE not being able to obtain $PATH when something is printed at the launch of the shell, by adding unique tokens before and after  `$PATH` value. This way we make sure only $PATH is extracted. 
- add `echo "SOMETHING"` to your `./zshrc` 
- IDE should be able to obtain $PATH anyway
=> Fix failing to obtain $PATH 

packages/vscode-extension/lib/wrapper.js
In #878 we introduced a regression due to some final renaming that wasn't caught. The `devtoolsPluginsChanged` variable got renamed to `expoDevPluginsChanged` but not updated in all the places. This resulted in preview functionality triggering the code with that bug and crashing as a result
1. Open any project with preview installed
2. Use preview functionality and make sure it doesn't crash
=> Fix preview crash after #878

packages/vscode-extension/src/webview/components/DimensionsBox.css, packages/vscode-extension/src/webview/components/DimensionsBox.tsx
This PR fixes BoxDimension which isweirdly large.
|Before|After|
|-|-|
|<img width="358" alt="SCR-20250114-qzhe" src="https://github.com/user-attachments/assets/15d03d41-f520-41e0-80e8-ea9fc82a2fdb" />|<img width="365" alt="SCR-20250114-ratv" src="https://github.com/user-attachments/assets/2b39d889-08fc-45a8-b3a6-4cae466b1f59" />| 
|Before|After|
|-|-|
|<img width="359" alt="SCR-20250114-qzik" src="https://github.com/user-attachments/assets/9b819f32-7c26-4bbf-a2a4-20ebfd1e4d60" />|<img width="366" alt="SCR-20250114-rasx" src="https://github.com/user-attachments/assets/553c8113-3176-4d88-afc4-a72a8c27ad79" />|
|Before|After|
|-|-|
|<img width="355" alt="SCR-20250114-qzjm" src="https://github.com/user-attachments/assets/76a3b74b-9236-4eda-90fe-929be96fb2b1" />|<img width="296" …
=> Fix DimensionBox size

packages/vscode-extension/src/project/metro.ts
In #864 where we tried to address the debugger listing changes in RN 77 we accidently broke debugger connection on older versions of React Native (in particular expo-router example app).
The reason is that we wrongly assumed that the existence of `reactNative` field in the debugger listing is exclusive to the new debugger entries while it still appears with old version of the debugger and on older versions of React Native. As a consequence, older apps (and expo-router in particular) may select a wrong runtime to connect to (which in case of expo-router was the reanimated runtime).
In this PR we partially revert changes from #864 responsible for filtering new debugger entries from debug endpoints list. Instead, for RN 77 specifically we rely on a suffix "[C++ connection]" that has been …
=> Fix new debugger detection after #864

packages/docs/docs/guides/configuration.md
Update docs about `customBuild` command after changes from https://github.com/software-mansion/radon-ide/pull/833.
=> Update docs about customBuild

packages/vscode-extension/package.json
This solves an issue when an external contributor tries to build from a source. This narrows down `git submodule update` to just `vscode-js-debug`
- run `npm install` in `packages/vscode-extension`
=> Fix preinstall command

packages/vscode-extension/package-lock.json
This PR is updates NPM lockfile which is a result of running `npm audit fix` command that bumps versions of certain dependenciies that may contain vulnarabilities. As a consequence we don't get as many warnings when installing while this update seem completely neutral as far as functionality.
=> Fix npm audit errors

packages/vscode-extension/lib/wrapper.js
This PR fixes an issue with loading bar not disappearing, for some time after application was already running. 
We caused the issue by overriding `LoadingView.hide`, to fix it we call the OG method in the new one.
Reload js, restart app process and reload IDE for expo-52 test app
=> Fix Loading view not disappearing

packages/vscode-extension/src/webview/components/DeviceSettingsDropdown.tsx, packages/vscode-extension/src/webview/components/DropdownMenuRoot.tsx, packages/vscode-extension/src/webview/components/IconButtonWithOptions.tsx, packages/vscode-extension/src/webview/components/SettingsDropdown.tsx, packages/vscode-extension/src/webview/components/ToolsDropdown.tsx
This PR forces dropdown menus to close when focus is taken away from the IDE.
Fixes #908
Run IDE, open dropdown menu, click outside of the ide
=> Close drop downs on blur 

packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts
This PR adreses a problem with multiple debugSessions being held by vscode, after performing multiple reloads in quick succession. This was caused by `debug.stopDebugging(this.vscSession)` not removing the previous session if called in to rapid succession. We trigger the `stopDebugging` method is by dispossessing `debugSession`. Because we dispose of the old `debugSession` every time we create a new one, attempt to create multiple instances of debug session in a row leads to the problem. 
In our current flow multiple instances of `debugSession` might be created after multiple restarts happening before, the previous one finishes. To avoid that we introduce a cancel token to `launchApp` method (which is triggered by the restart)  to exclude parallel execution.
Fixes #860
Performed …
=> Fix debugger after multiple reloads

packages/vscode-extension/README.md, packages/vscode-extension/package.json
Fixes #911
Our README on VSCode Market looks very empty and generic. This PR reuses our README from GitHub with skipped unrelated parts (as installation guide, contributing), and the license is moved lower to highlight the extension's features. 
- `npm run vscode:package`
- install created extension 
Tested on: VSCode, Cursor, Windsurf
=> Improve marketplace readme

packages/vscode-extension/lib/runtime.js, packages/vscode-extension/src/debugging/DebugAdapter.ts
This PR fixes an issue with console.logs used inside a worklet causing  unhandled exception.
The exception was caused by stack generated on the JS side not having location, line and column information. To solve it we just don't send that information to debugger if it does not exist. 
Additionally solving this problem reviled missing await in `handleConsoleAPICall` method in debagAdapter in case that can only be reached if debugger does not receive the above information so we fix that problem.
Run `react-native-reanimated` fabric-example and play `useFrameCallback` test
=> Fix console logs coming from worklets

packages/vscode-extension/src/webview/App.css, packages/vscode-extension/src/webview/index.jsx, packages/vscode-extension/src/webview/providers/WorkspaceConfigProvider.tsx
This PR fixes color glitch at the beginning. It's done in two stages: 
- we don't set the background until we have theme selected 
- we don't display rest of the UI until we know which one to display 
- Restart the extension and see if the glitch exists
=> Fix color glitch at the beginning

packages/vscode-extension/src/webview/components/SettingsDropdown.tsx
After adding theme switch menu option, I found the proposed text to not be indicative enough to what the option mean:
1) We use "VSCode" in the naming while also allow extension to work on Cursor and Windsurf
2) Name "built-in" is misleading as the editor theme can also be built-in
The new proposed wording is as follows:
1) Match editor theme – this makes Radon IDE panel use the same theme as the editor
2) Use Radon IDE theme – this makes the panel use Radon's theme (light or dark depending on the editor setting)
1) Use theme switcher, make sure it switches between using editor theme and theme from Radon
=> Update wording for theme switcher

packages/vscode-extension/src/panels/webviewContentGenerator.ts, packages/vscode-extension/src/webview/App.css, packages/vscode-extension/src/webview/providers/WorkspaceConfigProvider.tsx
This PR improves upon  #938. 
Instead of the CSS trick for empty attribute and holding the rendering, we just provide the **proper** initial value in the html. This seems to be the smoother solution. 
I'm using `workspace.getConfiguration("RadonIDE");` instead of `IDE.getInstance` as IDE is not attached at this point yet. 
- Restart the extension and see if the glitch exists
=> Fix startup theme glitch

packages/vscode-extension/src/builders/eas.ts, packages/vscode-extension/src/builders/easCommand.ts, packages/vscode-extension/src/common/DependencyManager.ts, packages/vscode-extension/src/dependency/DependencyManager.ts, packages/vscode-extension/src/webview/hooks/useBuildErrorAlert.tsx, packages/vscode-extension/src/webview/providers/DependenciesProvider.tsx, packages/vscode-extension/src/webview/views/DiagnosticView.tsx
- Improves build error messages when trying to use EAS Build without `eas-cli` installed.
- Adds `eas-cli` installation status to the diagnostics window.
Try to build an EAS Build project without `eas-cli` installed (`eas` executable should not be in `PATH`).
=> Improve user messaging when eas-cli is not installed

packages/vscode-extension/src/debugging/CDPSession.ts
Because of changes introduced to react native in this [PR](https://github.com/facebook/react-native/commit/1a9780f0e3714ac18ffae34cb67376c711b0e031) we need to call `ReactNativeApplication.enable` through the cdp on debug session start.
-run `react-native-78` app (For testing You'll need to disable `useReduxDevTools, isReduxDevToolsReady`  in `wrapper.js`  by hand it will be fixed by #[943](https://github.com/software-mansion/radon-ide/pull/943))
=> Adapt radon to RN 78 debugger

packages/vscode-extension/src/webview/styles/theme.css
This PR makes the IDE panel adapt the background color depending on its position when in editor-theme mode.
Previously, we'd always use background color that was set to the editor background. However, depending on whether the panel is rendered in editor on in side-panel, the built-in panels have different background colors. This is particularily important in case of side-panel, where in many themes there's no delimited between the editor and side-panel, so the only way to distinguish where the panel starts is by its background color.
Before (no visual indicator when there the panel starts):
After (background defins the panel threshold):
1. Test switching between editor theme and Radon theme across different themes and in tab + side-panel modes:
=> Don't force background color when in editor-theme mode

packages/vscode-extension/src/common/EasConfig.ts, packages/vscode-extension/src/common/LaunchConfig.ts, packages/vscode-extension/src/panels/LaunchConfigController.ts, packages/vscode-extension/src/utilities/eas.ts, packages/vscode-extension/src/webview/providers/LaunchConfigProvider.tsx, packages/vscode-extension/src/webview/views/LaunchConfigurationView.tsx
Adds options to the "Launch Configuration" GUI for enabling EAS Build, selecting build profiles and specifying build UUIDs.
- open [`expo-52-eas`](https://github.com/software-mansion-labs/radon-ide-test-apps/tree/main/expo-52-eas) and open the "Launch Configuration" window
- the settings for EAS Build should appear
- changing the settings in GUI should update `launch.config` file appropriately
- open an application without `build` config in `eas.json` (for example, [`react-native-77`](https://github.com/software-mansion-labs/radon-ide-test-apps/tree/main/react-native-77) or remove the `build` entry in `eas.json` in [`expo-52-eas`](https://github.com/software-mansion-labs/radon-ide-test-apps/tree/main/expo-52-eas)) and open the "Launch Configuration" window
- the settings for EAS Build …
=> Implement GUI for selecting eas build configuration

packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/common/utils.ts, packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts, packages/vscode-extension/src/devices/DeviceBase.ts, packages/vscode-extension/src/devices/IosSimulatorDevice.ts, packages/vscode-extension/src/devices/preview.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/utilities/utils.ts, packages/vscode-extension/src/webview/components/Preview.tsx
This PR introduces bidirectional clipboard support for iOS Simulator. The copying behaviour is similar to how cmd+v works, but instead of transferring hosts' clipboard content to the simulator, cmd+c transfers the simulator's clipboard to host's.
Apart from that, this PR prevents typing 'c' and 'v' when holding cmd and fixes multiline pastes (previously, newlines were recognized as starting separate commands, resulting in `unrecognized command` errors from simserver). It also adds a toast notifying user when copying/pasting is performed.
https://github.com/user-attachments/assets/c4014a7d-6023-4b30-b3ed-32c353fade02
Fixes #160, #701
Verified that:
- command+C copies the Simulator's clipboard content to host
- command+V pastes the host's clipboard content to the Simulator
- command+C is …
=> Add bidirectional clipboard for iOS Simulator, support multiline paste, show toast when copying/pasting

packages/docs/docs/getting-started/compatibility.md
Since we've added a support of Radon IDE for Linux (https://github.com/software-mansion/radon-ide/pull/829), it's time to change its support in compatibility table 😄 
This PR changes the value of compatibility for Linux, indicating that this system is officially supported from now on.
Manually, by building the `docs` package and running it in development mode with `yarn start`.
=> fix(docs): Change support for Linux in compatibility table

packages/vscode-extension/src/project/project.ts
This PR adds missing dispose to the project, object the lack of which was causing devtools panels to be visible before app was ready, if the IDE panel was closed and then opened again in one session 
- run `react-native-78` app and check if it works properly now
=> Don't show dev tools panels before activation

packages/vscode-extension/package.json, packages/vscode-extension/submodules-NOTICES.json
This PR adds separate notices file that includes licenses of dependencies that we include via submoduels, specifically vscode-js-debug, chrom-devtools-ui and the redux plugin. Those dependencies were omitted before from being collected by our license extraction scripts as they are not added as npm dependencies but rather are only included via build scripts run by npm.
Going forward we will have to manually maintain separate file that lists all submodule licenses. This PR introduces this file under main directory in vscode-extension folder. Then we expand third-party notices script to also pull in that newly added file.
1. Run build:third-party-notice script
2. Make sure the licenses for vscode-js-debug, chrom-devtools and redux plugin are included in the output (ThirdPartyNotices.json)
=> Include license notices from dependencies we include via submodules

packages/vscode-extension/lib/plugins/redux-devtools.js
This PR fixes issue that under certain conditions would break the devtools connection in Radon and prevent the app from loading as a consequence.
The issue could arise in situations when redux plugin is initialized before the devtools connection is established. When this happens, we rely on "react-devtools" event subscription. We call `hook.on` method to register for the event. The issue is that when the event is called we call `off` immediately from the callback. This prevents the subsequent event callback from being executed as the implementation of `hook.emit` uses `map` call and doesn't account for the fact that the array of listeners may change during iteration:
```js
function emit(event, data) {
if (listeners[event]) {
listeners[event].map(function (fn) {
return fn(data);
});
}
} …
```
=> Prevent callig hook.off from hook.on callback

packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/project/tools.ts, packages/vscode-extension/src/webview/components/ToolsDropdown.tsx
Makes it possible to register tool plugins with no corresponding VSC panel. This is meant to be used by https://github.com/software-mansion/radon-ide/pull/967 
Remove `openTool` method from one of the tool plugins and verify:
- the project still typechecks
- the tool dropdown does not display the "Open Panel" button
=> Allow tool plugins with no tool panels

packages/vscode-extension/lib/wrapper.js, packages/vscode-extension/src/webview/components/PreviewLoader.css, packages/vscode-extension/src/webview/components/PreviewLoader.tsx
This PR adds clear CTA buttons to the loading screen when we detect it is stuck in "Waiting for app to load" state.
The buttons pop up after 12 seconds of waiting – we are reducing it down from 30 seconds.
The possible options are:
1) open Radon IDE logs
2) force show device screen
3) open troubleshooting guide
4) Clean rebuild
1. Disable "app ready" event to force the app to get stuck on waiting
2. Test each individual option from the new menu
=> Add buttons with hints on what to do when stuck on Waiting for ap to Load

packages/vscode-extension/src/plugins/expo-dev-plugins/ExpoDevPluginWebviewProvider.ts, packages/vscode-extension/src/plugins/network/NetworkDevtoolsWebviewProvider.ts, packages/vscode-extension/src/plugins/redux-devtools-plugin/ReduxDevToolsPluginWebviewProvider.ts, packages/vscode-extension/src/plugins/redux-devtools-plugin/redux-devtools-plugin.ts, packages/vscode-extension/src/project/tools.ts
Reports telemetry events related to tool usage:
- enable/disable tool
- opening from tools dropdown
- toggling webview visibility
By placing breakpoints on `getTelemetryReporter` calls and toggling/opening/hiding the tools
=> Report telemetry events related to tool usage

packages/vscode-extension/src/plugins/expo-dev-plugins/expo-dev-plugins.ts, packages/vscode-extension/src/plugins/network/network-plugin.ts, packages/vscode-extension/src/plugins/redux-devtools-plugin/redux-devtools-plugin.ts, packages/vscode-extension/src/project/tools.ts
Allows tools to configure (via the `persist` boolean property) whether their enabled/disabled status should persist IDE restarts.
This is motivated by the "Outline Renders" tool (PR #967), which shouldn't be enabled when the IDE starts.
- change the `persist` value for one of the tool plugins to `false`
- verify that when the extension is restarted:
- tools which have `persist` set to `true` remember their status
- tools which have `persist` set to `false` are disabled
=> Allow tools to not persist their status

packages/vscode-extension/src/webview/Preview/hooks.ts
This PR fixes handling CapsLock by taking into account that simulators expect full keydown-keyup sequence to properly trigger CapsLock – currently, we only send a keydown when enabling CapsLock and defer sending keyup up until its deactivation, leading to desynchronization of CapsLock state. It also introduces reading CapsLock state from incoming inputs and synchronizing its state on the device, preventing desynchronization when pressing CapsLock with unfocused preview.
Verified that CapsLock is synchronized properly when using the IDE, as well as when changing its state outside and coming back to IDE.
=> Fix CapsLock handling

packages/vscode-extension/src/webview/components/DeviceSettingsDropdown.css, packages/vscode-extension/src/webview/components/SettingsDropdown.tsx
This PR adds version information to settings banner. This will make it easier for the users to tell which version they are running as sometimes even though the extension is updated, users may forget to reload extension in which case the new version despite being listed as installed is not running/
1. Open device settings dropdown
2. See the current version there. Check it under different vscode themes
=> Add Radon IDE version info to settings dropdown

packages/vscode-extension/src/utilities/expoCli.ts
This PR adds additional method for detecting if expo is used in the user application. The current method was assuming that if expo is used, users have defined scripts that use, expo CLI in their package json. This assumption unfortunately does not hold true for every user especially those using exclusively eas builds. To solve that issue we also check if a user has `"expo"`, configuration in their `app.json`. 
Run `expo-52-prebuild-with-plugins` test app and remove all scripts form `package.json` before the change  rudon would crash, after it works.
=> Additional expo detection method

packages/vscode-extension/package.json, packages/vscode-extension/src/common/LaunchConfig.ts, packages/vscode-extension/src/project/metro.ts
In one of the projects we heard the feedback from, they use `--scheme` option provided to expo start command. This is necessary for legacy reasons that they keep using expo this way.
The `--scheme` option makes it so that expo bundler uses the provided scheme when generating app URLs that we use for launching the app when expo dev client is detected. We eventually want to avoid relying on launching dev clients via URL, but the necessary changes only landed in SDK 52 (https://github.com/expo/expo/pull/33182), so for compatibility reasons we need to have a way for the schema to be customized on older versions (and until we add a way to launch dev client with extra arguments like proposed here https://github.com/expo/expo/pull/33182)
For the time being, the easiest workaround is to extend …
=> Add configuration option to specify arguments passed to expo start

.github/workflows/package-extension.yml, packages/vscode-extension/package-lock.json, packages/vscode-extension/vite.config.js
This PR makes it possible to only build the extension and store it as an artifact instead of always publishing.
It also updates `package-lock.json`, bumping our custom `react-scan` tarball (had to fix it upstream to properly build with Vite).
=> Add an option to build and upload extension artifact with GitHub Actions

packages/vscode-extension/src/utilities/subprocess.ts
This PR fixes the issue introduced by  #975, that was causing for the path variable to be incomplete.
The problem could be surfaced  when trying to use `sim-server fingerprint` functionality as it relies on the PATH variable. 
The solution is to in addition to the new path finding method, append the old path at the end of the new one to fill in any missing paths. 
- Run `react-native-78` test app
- add license
=> Add a fallback path to the end of the path variable

packages/vscode-extension/vite.config.js
This PR fixes an issue when webview is disconnecting, when laptop goes sleep. It happens only on development setup. The solution is based on this thread: https://stackoverflow.com/a/73560133
- Run Radon IDE 
- Close MacBook lid 
- Open it back
- The Radon IDE webview should be working as usuall
=> Fix WebView disconnecting in debug mode when laptop goes to sleep 

packages/vscode-extension/lib/expo_start.js, packages/vscode-extension/lib/metro_helpers.js, packages/vscode-extension/src/project/metro.ts, packages/vscode-extension/src/utilities/common.ts
Passes a concrete port number (picked by getting an ephemeral port briefly assigned by the OS and then releasing it) to Metro instead of "0", which causes issues with Metro's internal implementation.
Open the various test apps in the `test-apps` repo and verify the packager connects.
=> pass a concrete port number to Metro

packages/vscode-extension/src/debugging/DebugAdapter.ts, packages/vscode-extension/src/plugins/redux-devtools-plugin/ReduxDevToolsPluginWebviewProvider.ts, packages/vscode-extension/src/plugins/redux-devtools-plugin/redux-devtools-plugin.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/project/tools.ts
This PR fixes the issue with redux devtools webview not connecting properly after restarts/reloads or device changes reported in #992.
There were two separate reasons for the described issues:
1) The first issue stems from the timings between redux sents its init messages and when communication channel is established. Uless devtools agent is sent, we silently swallow all messages generated by the devtools. This is mostly ok, as we also need to support connecting the devtools at some later point, so we can't rely on the devtools being ready as soon as the store is created. However, if the devtools frontend was already opened at that time, which happens when we switch between devices, we can't ignore such messages as this would cause the frontend to never properly communicate. The fix for …
=> Fix redux plugin after reloads or device switch

packages/vscode-extension/src/panels/WebviewController.ts
Fixes an issue where the objects obtained through `makeProxy` in the webview
couldn't access the newly created objects, breaking:
- `"LaunchConfig"` after changing `appRoot`
- `"RenderOutlines"` after "Clean rebuild" or "Reload IDE" action, 
- possibly others
- "Reload IDE" or "Clean rebuild" and check that Outline Renderer still works
- change the App Root and verify the `LaunchConfigController.update` method is called on the newly created `LaunchConfigController` object
=> fix webview callable objects breaking on clean rebuild

packages/vscode-extension/package-lock.json, packages/vscode-extension/package.json
In `react-scan`'s outline renderer implementation, the duration of the outlines is fixed to 45 frames. This causes issues on high refresh rate displays, with frames disappearing too quickly.
This PR updates the version of `react-scan` to our fork which includes a fix for that.
The actual fix was made in https://github.com/software-mansion-labs/react-scan/commit/406f48e31cbd3ff0d16f6568597cbc980626350f
=> fix render outline duration changing with display refresh rate

packages/vscode-extension/src/debugging/BreakpointsController.ts
When setting breakpoints in our Debug Adapter, we sent in the response the list of our internal breakpoint objects. Because they referenced other parts of our implementation, when VSCode attempted to serialize them, it ran into reference cycles which resulted in stack overflows. This PR returns the breakpoint objects from `BreakpointController` in a form which should be safe for serialization.
- set breakpoints
- don't get stack overflows in logs
=> fix stack overflow when serializing breakpoints

packages/vscode-extension/src/debugging/BreakpointsController.ts, packages/vscode-extension/src/debugging/CDPBreakpoint.ts
This PR fixes an issue with CDPBreakpoints owning CDPSession causing circular dependency after #964.  
We solve the problem by: CDPBreakpoints no longer owns CDPSession and only takes a callback that alows it to send CDP messages
Run `expo-go` test app and set some breakpoints
=> Fix circular dependency in CDPBreakpoints

packages/vscode-extension/package-lock.json, packages/vscode-extension/package.json, packages/vscode-extension/src/webview/components/RenderOutlinesOverlay.tsx
Fixes #1012  
Fixes misalignment of render outlines when the display is scaled.
The actual fix was made in https://github.com/software-mansion-labs/react-scan/pull/1/commits/5e45c560a964b7c5d490505cac89618d739b777b
=> fix misalignment of render outlines

packages/vscode-extension/package-lock.json
Updates package-lock after updating the react-scan package to include https://github.com/software-mansion-labs/react-scan/commit/b3afb2f427d2fefb8d61bcab98a26bafe9141c69
=> update react-scan hash in package lock

packages/vscode-extension/package.json, packages/vscode-extension/src/debugging/CDPDebugAdapter.ts, packages/vscode-extension/src/debugging/CDPDebugSession.ts, packages/vscode-extension/src/debugging/DebugAdapter.ts, packages/vscode-extension/src/debugging/DebugAdapterDescriptorFactory.ts, packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/extension.ts, packages/vscode-extension/src/providers/DebugConfigProvider.ts
Refactors the changes introduced in #964 to separate logging metro messages and JS debugging into separate DAP Sessions. This will also make integrating #1001 easier with other changes made to `DebugAdapter`.
Open an app and check the debugger still works correctly:
- breakpoints and uncaught errors should still stop the application
- debugger controls in the preview should resume/step over breakpoints
- check profiling still works
- check if Metro errors are logged to the debug console.
=> Start separate debug adapters for Metro and JS debugging

packages/vscode-extension/src/project/metro.ts
this PR fixes how bundle error source was created in case when `originModulePath` is missing
run `react-native-77` test app and force syntax error
=> Fix bundle error source

.github/workflows/package-extension.yml
This PR changes the behavior of the publishing CI to allow for automatic packaging process to take place when publishing instead of using an artefakt created for github publication. 
This change is needed because `vsce` and `osvx` publishing commands are not capable of changing the metadata of already packaged `vsix` directories and the universal target specified in original artefakt would conflict with targets specified by CI user. 
it can only be tested by running it :(
=> Rework CI to build fresh versions for publication

.github/workflows/package-extension.yml, packages/vscode-extension/package-lock.json, packages/vscode-extension/package.json
This PR changes the approach to the publishing CI and removes the external `HaaLeo/publish-vscode-extension@v1` replacing it with underling `vsce` and `osvx` commands. This is necessary because of a bug that was surfaced by [this](https://github.com/software-mansion/radon-ide/actions/runs/13769019110) CI run.
The final version was not tested as it would mean running the CI
=> Remove external publishing workflow form the CI

packages/vscode-extension/src/project/metro.ts
This PR changes how we check if the new JS debugger (aka. Fusebox) is enabled by inspecting the debugged Page's `capabilities` for the `prefersFuseboxFrontend` flag, which is set by the RN application when the new debugger is enabled.
=> Fix new debugger detection

packages/vscode-extension/package-lock.json, packages/vscode-extension/package.json, packages/vscode-extension/src/builders/buildAndroid.ts
This PR fixes an issue with some setups that contain complicated native structures. 
Some apps contain native android code that is failing gradle builds, but is not application dependency, to avoid that we try to determine  app name and add it as a prefix to build task name.
- run clean build in `react-native-78` test app
=> Pass app name to gradle

packages/vscode-extension/src/builders/buildAndroid.ts
This PR fixes a regression introduces in #1004. It seems that in some configuration loadConfig is returning an object but gives no details for `platform.android` that caused Radon to crash. As we already expect that config might not exist the fix is to read `projectConfig` conditionally.
The problem surfaced itself for me in `expo-52-prebuild-with.-plugins` test app. It build correctly after this fix
=> Fix android app name detection

packages/vscode-extension/src/builders/customBuild.ts
This PR adds a support for inline shell script in `customBuild.{Platform}.buildCommand` configuration. For many users the mos intuitive way of utilizing build command was to wirite something like `echo ${PWD}/apkPath` this would not work tho as `$ENV` syntax requires full shell, so we start running `buildCommand` in shell. 
build `expo-52-prebuild-with-plugins` android project and find generated apk in `android/app/build/outputs/apk/debug` copy this apk to the root of the application and set the android build command as `echo ${PWD}/apkPath` remove the whole android folder from the project root and run application, it works correct.
=> Support inline shell scripts for custom build script

.github/workflows/package-extension.yml, packages/vscode-extension/package.json
This change allows us for packaging each target only once and not 3 times. 
Dry job was run here https://github.com/software-mansion/radon-ide/actions/runs/13837593885
with `Publish to Visual Studio Marketplace for each target` printing the targets instead of publishing them 
unfortunately publishing it self can only be tested live
=> Refactor publishing CI so it publishes the same artefacts it packges

packages/docs/docs/getting-started/compatibility.md, packages/vscode-extension/lib/babel_transformer.js
This PR allows react native version 78 to run on the IDE and update docs for 0.77 and 0.78 support
=> Added support for 0.78 and updated docs.

packages/vscode-extension/src/builders/BuildCache.ts
This PR adds `DerivedData` to ignore paths of fingerprint command. 
This is a solve for very long calculation times for users that keep this data relative to their ios project. 
To enable this behavior:
1) open `xcode`
2) from top menu choose xcode>settings
3) go to locations tab
4) switch derived data to relative
- switch the option as described above 
- clean rebuild `expo-52-prebuild-with-plugins` test app
- reload after the clean build and check if calculation takes normal amount of time
=> Ignore derived data for fingerprint calculation

packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts, packages/vscode-extension/src/devices/DeviceBase.ts, packages/vscode-extension/src/devices/IosSimulatorDevice.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/views/OpenDeepLinkView.css, packages/vscode-extension/src/webview/views/OpenDeepLinkView.tsx
This PR adds an option to terminate an app before sending deep link to the device.
- run `expo-52-prebuild-with-plugins` test app 
- test the termination flow with `myapp://` deeplink 
- test flow without termination (ass app is opened nothing should happen) 
https://github.com/user-attachments/assets/b6925895-4d71-4c3f-b9c7-43a74608aee4
=> Add an option to test deeplinks with app terminated

packages/vscode-extension/src/webview/views/OpenDeepLinkView.css
This PR fixes an issue that snicked into #1035, by making the text color responsive.
open `Open Deep Link` view and change themes
=> Fix appearance of send deep link on diffrend themes

packages/vscode-extension/src/chat/api.ts, packages/vscode-extension/src/chat/history.ts, packages/vscode-extension/src/chat/index.ts
Changes:
- allow Assistant to call tools multiple times during a single Assistant turn
- fix errors after Assistant uses a tool
- simplify history retrieval
---
This PR is still work-in-progress - debugger logs may still be present.
- use the following prompt to test if the chatbot is capable of using tools: 
- `Leave feedback using "leave_feedback" function, and reply to me with the result that you will get`
- use the following prompt to test how the chatbot handles tool-usage edge-cases: 
- `Now call "leave_feedback" function multiple times, by creating mutliple tool calls in a single request, and reply to me with the results that you will get`
=> [Radon AI] Chat fixes and improvements

packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/debugging/CDPDebugAdapter.ts, packages/vscode-extension/src/debugging/CDPSession.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/Preview.css, packages/vscode-extension/src/webview/components/Preview.tsx
Removes some leftover code after we stopped handling exceptions ourselves in #1040 
- Open an app with RN version <0.76 (in order to use the old debugger)
- trigger an uncaught exception
- don't crash and burn
=> remove exception handling related code

packages/vscode-extension/src/webview/components/DeviceSelect.tsx
This PR fixes a UI glitch where the device selection button would stay in focused state after being dismissed or when changing devices.
Before this change when you tap on the device select button and dismiss or select item from it, it'd stay focused / highlighted:
Now it is no longer in the focused state after interacting:
We use the same technique as with other dropdown buttons where we use `onCloseAutoFocus` to dismiss the focus propagation.
1. Click device select button, dismiss the menu, see it no longer stay highlighted
=> Prevent device select dropdown from staying focused after change

packages/vscode-extension/src/debugging/CDPDebugAdapter.ts, packages/vscode-extension/src/debugging/DebugAdapter.ts, packages/vscode-extension/src/debugging/DebugAdapterDescriptorFactory.ts, packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/debugging/ProxyDebugAdapter.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/metro.ts, packages/vscode-extension/src/project/project.ts
In #964 we changed the debugger workflow and started using the debugger to also wrap the metro session to allow us reporting bundle errors.
Further #985 and #1001 contributed some changes to the debugger workflows that impacted the way we handle debug commands with assumption there is a separate debug session for metro and a new one for the js debugger.
This PR clears up that assumption and allows for the DebugSession class to work with the parent metro session but also without it. While the latter mode is not used, this refactor is needed to build the new "connect" functionality that allows Radon to work with the externally controlled metro instances. In such scenario we don't get bundle errors and hence can't use the debug session to report these. In addition, we need to handle …
=> Refactor DebugSession and DebugAdapter to support only spawning JS debug session.

packages/vscode-extension/src/builders/BuildManager.ts, packages/vscode-extension/src/dependency/DependencyManager.ts, packages/vscode-extension/src/webview/hooks/useBuildErrorAlert.tsx
Stops iOS build if pods need to be installed, but the `pod install` command doesn't install them successfully.
Adds a descriptive message to the build error alert when pods are not installed.
React Native 78 app in test-apps has an incorrect pods lockfile, which allows testing pod install failure
- try to run `react-native-78` in a freshly cloned repo on iOS -- the pods failed alert should appear
- try to run `react-native-78` in a freshly cloned repo on iOS, with pods not installed correctly -- the pods failed alert should appear
- try to run `react-native-78` in a freshly cloned repo on Android -- the app should build and run correctly
- try to run `react-native-78` in a freshly cloned repo on iOS after resolving the pods issues -- the app should build and run correctly
Previously: …
=> Improve user experience when pods fail to install

packages/vscode-extension/src/plugins/redux-devtools-plugin/ReduxDevToolsPluginWebviewProvider.ts, packages/vscode-extension/src/utilities/extensionContext.ts
VSCode's `Uri.path` includes a leading `/` on Windows (i.e `/c:/things/thing`), causing filesystem operations on file paths obtained from them to fail.
This PR fixes this issue by using `Uri.fsPath`, which is meant to be used with filesystem operations (according to [the API reference](https://code.visualstudio.com/api/references/vscode-api#Uri))
Fixes #1050
- Open the extension on Windows
- Don't crash immediately
=> fix: use Uri.fsPath for filesystem operations

packages/vscode-extension/src/webview/providers/DependenciesProvider.tsx
This PR fixes a mistake introduced in #586, causing missing xcode installation to be registered as emulator and not simulator error.
- Uninstall Xcode form your machine 
- run `react-native-79` test app and remove all devices 
- click `add iPhone` and `add android` and check if it works
=> Fix home screen when xcode is not installed

packages/vscode-extension/src/builders/eas.ts, packages/vscode-extension/src/builders/easCommand.ts
When fetching builds from EAS Build automatically (i.e. without providing a specific build id), we filter the available builds by the fingerprint returned by the `eas-cli fingerprint:generate` command.
- run `expo-52-eas` test app on Android
- open launch configuration and select "EAS Build -> Android Build Profile -> development"
- the build should download from EAS Build successfully
- make a change which invalidates the fingerprint
- clean rebuild the app
- the build should fail, and the logs should indicate no build with matching fingerprint was found
=> Only fetch builds from eas with matching fingerprint

packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/debugging/ProxyDebugAdapter.ts, packages/vscode-extension/src/debugging/RadonCDPProxyDelegate.ts
This PR adds support for built-in Overlay (via CDP) that displays debugger paused status. This only applies to the new debugger.
While the code for supporting this API is added, there is no place in the codebase currectly that'd use this.
As a part of this change however, we had to refactor support for paused/resume events.
Before this change, we'd only fire resume event when debugger runs the Debugger.resume command.
This wasn't ideal as there are other ways how debugger can resume including the Overlay that displays resume button.
The obvious solution would be to rely on debugger's `Debugger.resumed` event. 
This event however comes also when we perform step-over debugging. 
This causes the overlay to blink for a fraction of a second as the debugger is resumed to perform a single step. …
=> Properly trigger resume events to support Overlay CDP methods

packages/vscode-extension/src/builders/buildAndroid.ts, packages/vscode-extension/src/builders/buildIOS.ts, packages/vscode-extension/src/builders/eas.ts, packages/vscode-extension/src/panels/LaunchConfigController.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/utilities/extensionContext.ts
Fixes an issue where the frontend was never aware of the launch config's EAS settings.
This was caused by the frontend and extension using a different method to read the launch config, one of which picked the fields from the config to send explicitely, and which omitted the `eas` entry.
- open the `expo-52-eas` app
- go to launch config options
- verify the development profile is picked for EAS build
- try to build the app after changing something which impacts the fingerprint (to force build fail)
- verify an EAS-related error is displayed
=> fix EAS in launch config not being set correctly in webview

packages/vscode-extension/src/builders/BuildManager.ts, packages/vscode-extension/src/builders/buildAndroid.ts, packages/vscode-extension/src/builders/buildIOS.ts, packages/vscode-extension/src/builders/eas.ts, packages/vscode-extension/src/project/project.ts
Makes sure the error message for the exception thrown from the `eas` builder is reported in the extension output.
- open the `expo-52-eas` app
- make the build fail
- verify that when the build fails, the logs end with a verbose explanation of what went wrong
=> Improve how EAS Build errors are logged

packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/debugging/ProxyDebugAdapter.ts, packages/vscode-extension/src/debugging/startDebugging.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/metro.ts
This PR cleans up the code preparing for changes that'd allow Radon to use existing metro.
In this PR we are decoupling debug session to no longer take metro as argument. This is needed such that we have better control over debug session w/o need of maintaining up-to-date instances of metro class. Eventually, we may want to refactor metro class entirely such that it has a cleaner interface as now it mutates it states when it searches for debugger URL which can be a bit misleading. Regardless – this is out of the scope for this change as we only extract debug session such that it can work based on the session configuration as opposed to fetching details via metro instance.
What's changed:
1. We simplify and move reconnect logic to device session class. Instead of doing promise race we just …
=> Decouple metro and debug session classes

packages/vscode-extension/src/utilities/sdkmanager.ts
This PR adds information that android sdk 36 is android 16 
run extension and add device with sdk 36
=> Add mapping for android SDK 36

packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/utilities/isAutoSaveEnabled.ts, packages/vscode-extension/src/webview/hooks/useBuildErrorAlert.tsx
This PR does two things:
1) disables triggering on source of bundle error when auto focus is enabled, as users give as feedback that this functionality disrupts their flow
2) replaces focus on IDE logs with focus on debug console in Bundle error actions as the bundle error logs are now visible in the console.
- turn on auto save and trigger bundle errors you can now write without stoping to move the pointer
=> Improve Bundle error experience when auto save is enabled

packages/vscode-extension/src/webview/hooks/useBuildErrorAlert.tsx
This PR adds information to the build error baner that informs the user about missing node installation, or that it is too old to suport react native applications.
- use command `nvm alias default 17` and open vscode from new shell 
- test `react-native-79` test app 
- the new description shows app correctly
=> Improve user interface in case of old node version

packages/vscode-extension/lib/network.js
This PR introduces the following enhancements to the XHRInterceptor:
1. **TTFB (Time to First Byte) Tracking**:
- Automatically calculates the TTFB when the `readystatechange` event indicates the `readyState` is 2 (headers received).
- Includes the `ttfb` value in the `Network.responseReceived` message sent to the devtools agent.
2. **Network Enable/Disable Support**:
- Adds support for `Network.enable` and `Network.disable` methods via the `RNIDE_networkInspectorCDPRequest` listener.
- Enables or disables the XHRInterceptor based on the received method.
=> Enhance XHRInterceptor with TTFB tracking and Network enable/disable support

packages/vscode-extension/src/debugging/RadonCDPProxyDelegate.ts
Adds support for source map URLs with `http:` schema in the new debugger.
This is needed for the CPU Profiler's source mapping to work in React Native 79 applications, which (at least in the test-app) returns `http:` source map URLs.
- run `react-native-79` test app
- run the CPU Profiler
- verify the functions in the profile are correctly source mapped
=> fix sourcemap handling for http sourcemap urls

packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts
This PR solves the android application not finding metro when build cache was hit and the application is small enough. 
If we booting device and building the application was fast enough, the emulators network internals would not be loaded before the start of the application.  This in turn would cause [PackagerStatusCheck](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/devsupport/PackagerStatusCheck.kt) to fail and the application would think that there is no metro server. 
To solve this problem we do not allow the IDE process to think that the emulator is ready until network is operational. 
- run `react-native-78` test app and switch android devices multiple times to try and caouse the error
- change the behavior of …
=> Fix android builds not finding metro server 

packages/vscode-extension/src/debugging/CDPDebugAdapter.ts, packages/vscode-extension/src/debugging/CDPSession.ts, packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/debugging/SourceMapsRegistry.ts
This PR updates the original debug adapter implementation to support the updated format of source map aliasing.
For the new react native debugger, we use the option `sourceMapOverrides` in order to translate from "/[metro-project]/" alias that the RN devtools introduced. With the old debug adapter, we've been expecting a different format for this, namely, a list of pairs with alias and absolute file location. Given we may want to use the old debug adapter to support the new debugger while keeping an option to rely on vscode-js-debug, we want to unify these formats, such that we don't need to format the parameters differently depending on the debug adapter we use.
This PR adapts ths old debugger implementation to accept the updated format. Now the overrides are provided as …
=> Adapt updated sourceMapOverrides format in old debug adapter

packages/vscode-extension/src/debugging/CDPDebugAdapter.ts, packages/vscode-extension/src/debugging/CDPSession.ts, packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/debugging/ProxyDebugAdapter.ts
When connecting to the new RN debugger without Radon's runtime, the logs wouldn't appear in the debug console.
The reason was that we improperly transform the output event because we had a special path for creating events that only works when extra parameters are provided via our `wrapConsole` override from `runtime.js`.
However, when we connect to existing metro instance, the override doesn't work, yet we still need to handle the console events. There were a few problems with that:
1) In #846 we changed the way we handle variable references. This was updated in the main path that relied on the call frame being provided from the runtime but not in the `else` branch.
2) When source frame isn't provided via runtime, we never attempt to read the call frame from CDP call which now is properly …
=> Handle call frames when logs don't use radon's runtime

packages/vscode-extension/src/webview/utilities/consts.ts
This PR adds iPhone 16 Pro to device list. We simply copy the configuration from iPhone 15 as all the dimensions and bazels are the same.
1. Open device creation flow, select iPhone 16
2. Run the newly created device on one project, test text/dark mode settings work ok.
=> Add iPhone 16 Pro to device list

packages/vscode-extension/src/debugging/DebugSession.ts
In #1001 we introduced a separate implementaton of DebugAdapter that was based on vscode-js-debug project.
While it is better in many aspects from our previous implementation, we discovered that it perform much worse on bigger projects. Specifically the initialization times were very slow as well as JS reloads. For example https://github.com/bluesky-social/social-app project would take as long as 30 seconds on my M3 mac to initialize while both the app and the editor were hanging and waiting for the initialization to complete.
The initialization issue is likely tied to processing source maps as deleting source map information mitigates this problem (although it breaks all other functions like breakpoints, logs, etc). While it requires some additional investigation this PR disables the new …
=> Force use of Radon's original debug adapter implementation

packages/vscode-extension/package.json, packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/devices/DeviceBase.ts, packages/vscode-extension/src/devices/preview.ts, packages/vscode-extension/src/extension.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/DeviceSettingsDropdown.tsx
This PR adds options in device settings menu that can trigger home and appSwitch button presses on active device.
We utilize the recently updated sim-server for this purpose that now supports new `button` command.
While it may not be the optimal place to add such buttons, they aren't used as frequenly, so we can alter this location once we get more feedback from the users. On top of that we're setting a shortcut that is compatible with iOS simulator for the home button press: Cmd+Shift+H
This change refactors the Project interface and removes method for biometric auth in favor of more generic method that allows us to run a command. This way we can hook into the commands API easily w/o expanding this interface further.
Here's how the new options look like in the device settings menu:
1. …
=> Add options to trigger home button and appswitcher buttons

packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/PreviewLoader.tsx
This PR removes redundant conditional render introduced in #1068, as `previewLoader` is already rendered conditionally in the fallowing code:  
```js
{!showDevicePreview && !hasBuildError && !hasBootError && (
<Device device={device!} resizableProps={resizableProps}>
<div className="phone-sized phone-content-loading-background" />
<div className="phone-sized phone-content-loading ">
<PreviewLoader onRequestShowPreview={() => setShowPreviewRequested(true)} />
</div>
</Device>
)}`
```
the additional check introduced in #1068 causes problems as our startup cycle still has some unhandled errors that do not cause the whole process to crash but do remove "starting" status from `projectState`. We plan to catch all of those edge cases as soon as possible but to unblock user experience for now we …
=> Fix startup cycle

.gitmodules, packages/vscode-extension/package.json
After #1057 we no longer need chrom-devtools-ui dependency in the project.
This PR deletes the submodule and also removes the build steps that were copying the data from that projects which results in significant reduction of the VSIX artifact.
1. Build VSIX with `vscode:package`
2. Observe it is 10MB lighter than before
3. Install VSIX and test network panel
=> Delete chrome-devtools-ui from dependencies

packages/vscode-extension/src/webview/components/shared/Modal.css, packages/vscode-extension/src/webview/views/ActivateLicenseView.css
This PR fixes styles for modals and for the activate license modal in particular.
This addresses the issue with scroll bars appearing on modals when IDE panel is narrow.
This PR makes the following changes to the styles:
- we use percentage to set width and height of the modal (there's a px max limit that we keep). This way they don't reach the very edges of the view which makes it hard to notice the modal edges.
- we allow license key input to scale on its own instead of using 100% which cased it to always expand past the boundaries of the modal (because it also has borders and paddings).
1. Open activate license modal, manage device modal, diagnostics modal and launch config modals
2. Resize the window to see it looks ok with both wide and narrow settings
Before:
After:
This change …
=> Fix license modal sizing issue

packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/project/metro.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/Preview.tsx
This PR introduces the following changes: 
1) bundle error over lay is removed and we instead rely on build in error message box 
2) We no longer focus on debug console and terminal when bundlingError happens, unless during the startup process, then we focus on the error source 
3) we remove redundant hasBundleBuildFailedError, it was always triggered in pair with  bundlingError and bundlingError was enough to throw ide into error  (display error baner and overlay) so we remove it.
4) because the build in error message box contains clickable elements we list the block on sending inputs to the device while in bundlingError state
- run `react-native-79` test app and force bundle errors in startup and non startup scenario
=> Rework how bundle errors are triggered 

packages/docs/docs/guides/configuration.md, packages/vscode-extension/package.json, packages/vscode-extension/src/common/LaunchConfig.ts, packages/vscode-extension/src/devices/IosSimulatorDevice.ts
This PR adds a launch arguments to launch configuration on iOS, for now it only works with non expo applications, but as we'll move away from utilizing expo deep links we can add it to them as well. 
This configuration is useful for projects that use firebase and for full debugging  need to add `-FIRDebugEnabled` argument to launch command. https://firebase.google.com/docs/analytics/debugview
1) add this configuration to `react-native-79` test app and check if it breaks anything 
2) breakpoint in `launchApp` method and see if the argument is passed as expected
3) watch the preview of the documentation on vercel
=> Add launch arguments as a configuration on iOS.

packages/docs/docs/guides/configuration.md
Updates the configuration docs to reflect the new behaviour of EAS build.
Previously, if `buildUUID` was not set, we would use the newest available build for the platform.
Currently, we try to select a compatible build using `eas fingerprint` and use that instead.
=> update the docs to reflect new eas build behaviour

packages/vscode-extension/src/builders/BuildManager.ts, packages/vscode-extension/src/builders/buildAndroid.ts, packages/vscode-extension/src/builders/buildIOS.ts, packages/vscode-extension/src/common/BuildConfig.ts, packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/hooks/useBuildErrorAlert.tsx
Previously, the "builders" (`buildIos` and `buildAndroid` functions) were responsible for selecting the "type" of the build they should perform, based on the radon Launch Configuration and the application workspace. This resulted in a lot of duplicated logic between these functions and makes it impossible for the callers of these functions to control which type of build should be run.
This PR changes these functions to accept a `BuildConfig` parameter which specifies the build type instead, and moves the build type selection logic to the `BuildManager`.
- open test apps from the test app repo and verify the correct build type is used
=> Refactor build type selection logic to happen outside the builders

packages/vscode-extension/package.json
Calling `vite` from `src/network` is unnecessary. First, because `vite` command goes into watch mode so it will never execute the commands after "&&". We also don't need to have a separate instance of vite for network panel because the main instance hosts the network and webview panels.
1. Build in dev mode and make sure network panel loads
=> Remove vite call from src/network

packages/docs/docs/guides/configuration.md, packages/vscode-extension/src/builders/BuildManager.ts, packages/vscode-extension/src/builders/buildAndroid.ts, packages/vscode-extension/src/builders/buildIOS.ts, packages/vscode-extension/src/builders/eas.ts, packages/vscode-extension/src/builders/easCommand.ts, packages/vscode-extension/src/common/BuildConfig.ts, packages/vscode-extension/src/common/LaunchConfig.ts, packages/vscode-extension/src/utilities/subprocess.ts, packages/vscode-extension/src/webview/hooks/useBuildErrorAlert.tsx, packages/vscode-extension/src/webview/views/LaunchConfigurationView.tsx
- Allows configuring EAS apps to build locally instead of downloading from the EAS Build server.
- Allows setting the EAS build `local` flag through UI.
- Updates the docs to include the new flag.
- open the `expo-52-eas` test app
- add a `"local": true` entry to `eas.ios` or `eas.android` launch config
- check that the app is built locally for the platform
- open the "Launch Configuration" menu
- verify you can select "Build Locally > Yes/No" under the EAS options and that the setting is respected
=> Support EAS local builds

packages/vscode-extension/src/builders/BuildManager.test.ts, packages/vscode-extension/src/builders/BuildManager.ts
Adds some trivial unit tests for `BuildType`/`BuildConfig`-related parts of `BuildManager`
=> add unit tests for BuildType and BuildConfig

packages/vscode-extension/.vscode/tasks.json, packages/vscode-extension/vite.config.js
After recent updates of VSCode and Cursor we started seeing issues when launching or re-launching the extension in dev mode from VSCode/Cursor.
I noticed that the issue was because the launcher was waiting for the "start webview server" to complete. However, due to the task being configured such that it waits for "localhost:2137" pattern to appear, it'd never go into a "complete" state for some reason.
What I don't understand is why this hasn't been a problem before. The root cause was the change were we modified vite's configuration to use 127.0.0.1 instead of localhost. However that change got merged a long time ago. So I suspect that something has changed in the code that handles the task runner such that it actually waits for this task to be considered as finished before it can …
=> Fix starting dev version of extension from cursor

packages/vscode-extension/src/project/deviceSession.ts
A last minute addition I made in #1110 introduced a regression where the device session fails to start. The reason was that I extracted code that was meant to control creating devtools instance, but it should not rely on the devtools instance already set on `this` but rather the new devtools instance created in that method.
1. Start any project, see the panel launches normally. Before the panel would get start on 'initializing device" step.
=> Fix device sesstion start

packages/vscode-extension/scripts/build-sim-server-debug.sh
This PR fixes the Github URL from which the simulation server is fetched when running `build-sim-server-debug.sh` on development setup. In the previous version, the script tried to download from `https://github.com/software-mansion/radon-ide/releases/download/<version>/simulator-server-<version>-<platform>`, but the file name doesn't contain the version tag.
Following the steps specified on the [Development](https://ide.swmansion.com/docs/guides/development) docs page, run `npm run build:sim-server-debug`. The server binary is now being fetched successfully.
=> Correct sim server binary name when fetching from releases

packages/vscode-extension/src/project/metro.ts
In RN 77 there were changes to how runtimes descriptions are generated that we addressed in #864. As the new expo go on expo-53 is using a newer version of react native those changes where interfering with how we recognize that the runtime is expo-go, this PR fixes that by additionally using `appId` filed missing from older versions. 
-Run  `expo-53` test app in expo go mode (without prebuilt) and test debugger on ios
=> Add support for expo go in expo 53

packages/vscode-extension/lib/babel_transformer.js, packages/vscode-extension/lib/expo_router_v5_plugin.js
Recently expo released a new version in witch they changed their internal api located in `expo-router/build/global-state/router-store.js`. to acomodate that we add a new `expo_router_v5_plugin.js` and attach it to expo-router entry via our `babel_transformer`
-run `expo-53` test app and test expo router functionality
=> Add expo router support for expo 53

packages/vscode-extension/src/debugging/CDPDebugAdapter.ts, packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/debugging/ProxyDebugAdapter.ts
Currently, the logic for reconnecting the debugger after the application is reloaded always restarts the debug session.
This was uncaught since the behaviour is _technically correct_ (in that in the end, we'll always have a debug session connected to the application after reload), but undesirable (we'd rather reuse the existing debug session since its initialization is relatively slow).
This PR fixes the minor bugs which caused the issue.
Right now, after this fix is applied, the current debugger implementation breaks after JS reload, presumably due to issues with how source maps are cleaned up.
This surfaces by not mapping the sources correctly in the Debug Console (instead always mapping to `__source__`)
This PR also makes the debug session always restart on the old debugger as a …
=> fix debugger always restarting after app reload

packages/vscode-extension/src/debugging/CDPDebugAdapter.ts, packages/vscode-extension/src/debugging/CDPSession.ts, packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/debugging/ProxyDebugAdapter.ts
This PR fixes the issue mentioned in #1120 by waiting for the new main bundle to load before logging to console after a JS reload.
- add log points to `DeviceSession.reconnectJSDebuggerIfNeeded`
- check that after "Reload JS" is triggered in Radon, the function returns early (without calling `this.connectJSDebugger`)
- check that logs in the "Debug Console" are mapped to the source correctly
=> Fix CDP debug session always restarting on JS reload

packages/vscode-extension/src/panels/WebviewController.ts, packages/vscode-extension/src/webview/views/PreviewView.tsx
This PR adds additional telemetry to determine: 
- what location for IDE panel users prefer 
- do users encounter problems after clicking "activate license button"
=> Add additional telemetry

packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/debugging/ProxyDebugAdapter.ts, packages/vscode-extension/src/debugging/RadonCDPProxyDelegate.ts
This PR fixes the issue of _excruciatingly_ long debug startup on larger applications when using the `js-debug`-based debugger implementation and reenables it for React Native apps using the new ("Fusebox") debugger.
It also updates the version of `js-debug` used and applies patches which should improve startup performance in the React Native case, as described in the PR: https://github.com/software-mansion-labs/vscode-js-debug/pull/4
- launch `social-app` (or another large application)
- set some breakpoints
- restart the application a couple of times in various ways (JS reload, full app restart, IDE restart)
- verify that the delay before the set breakpoints are active (indicated in the UI by the breakpoint dot turning red) takes on the order of seconds, and not tens-of-seconds
=> Fix js debug startup delay and reenable js-debug for new debugger targets

packages/vscode-extension/package-lock.json, packages/vscode-extension/package.json
Downgrades the vscode API type definitions to the version which matches the targeted VSCode version (as specified by `engines.vscode` in `package.json`).
=> downgrade vscode types package

packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/debugging/RadonCDPProxyDelegate.ts
Due to the difference in paths between development mode and packaged extensions, the `lib/` directory of the extension was not correctly ignored when the extension was installed from a package (rather than running in the Extension Development Host).
This PR fixes that.
- build an install an extension `.vsix` package
- open a test app from `radon-ide-test-apps`
- check "Uncaught exceptions" breakpoint
- click the "Check uncaught exceptions" button
- verify the debugger doesn't pause inside RN renderer
=> fix debugger not ignoring injected files correctly

packages/vscode-extension/src/project/DeviceSessionsManager.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts
Currently, when a build error happens during a reload, we fail to display the error dialog, instead hanging on "Building...".
The root cause was us not catching the error in `DeviceSessionsManager.reload`, meaning we never set the project state to "build error".
This PR fixes that.
- have an app which fails to build
- open it in Radon
- wait for the build to fail
- reload the app (either from the error dialog or with the Reload button in the URL bar)
- the build error dialog should appear again <- previously, the build would appear to hang instead
=> Fix build error dialog not appearing on reload

packages/vscode-extension/package.json
Currently, we set the default keyboard shortcut for "Perform failed biometric authorization" action to "Cmd+Shift+N" (or "Ctrl+Shift+N" on windows), which conflicts with the default vscode "Open new window" shortcut.
Since opening a new window is an action which many users rely on in their usual workflows, this is undesirable.
This PR changes the default keybind to a less-likely-to-conflict "Cmd+Option+Shift+M" (which is "Perform biometric authorization" + "Shift").
Fixes #1039 
- open a project in Radon IDE
- press "Cmd+Shift+N"
- a new vscode window should open (provided you use the default keybind)
=> Change the default failed biometric auth keybind

packages/vscode-extension/package.json, packages/vscode-extension/src/common/WorkspaceConfig.ts, packages/vscode-extension/src/common/utils.ts, packages/vscode-extension/src/extension.ts, packages/vscode-extension/src/panels/SidepanelViewProvider.ts, packages/vscode-extension/src/panels/Tabpanel.ts, packages/vscode-extension/src/utilities/utils.ts, packages/vscode-extension/src/webview/components/SettingsDropdown.tsx
This PR improves window/panel position management. Before, when using IDE in editor panel, we'd always get the editor position structure messed up when restarting the editor. Thanks to the made changes, we can also take adventage of the new "compact" mode for new windows.
Here's what we're changing:
1. We're deleting code for handling secondary side bar. This includes the setting option etc. Due to limitation of vscode extension API, we cannot control this way and the value gets out of sync between the UI and our configuration. Going forward we have to rely on the user moving it correctly (will be updating the docs to reflect that as well).
2. The panel location now only tell whether we should use "side-bar" or "tab" mode for the IDE panel. This is the only combination that we can …
=> Improve window management

packages/vscode-extension/src/webview/components/UrlBar.tsx, packages/vscode-extension/src/webview/components/UrlSelect.tsx
Due to mistyped parameters, sometimes `value` passed to the `UrlSelect` component is `undefined`, causing an error due to `.toLowerCase` being called on it.
This PR fixes the tyle of `urlSelectValue` state and checks for `undefined` where necessary
- the issue was hard to reproduce reliably, but sometimes the IDE webview would crash due to method call on undefined that is impossible now
=> Fix occasional webview crash in UrlSelect

packages/vscode-extension/eslint.config.mjs, packages/vscode-extension/package-lock.json, packages/vscode-extension/package.json, packages/vscode-extension/src/builders/BuildManager.test.ts, packages/vscode-extension/src/builders/buildIOS.ts, packages/vscode-extension/src/builders/cancelToken.ts, packages/vscode-extension/src/debugging/CDPProxy.ts, packages/vscode-extension/src/debugging/CDPSession.ts, packages/vscode-extension/src/debugging/RadonCDPProxyDelegate.ts, packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts, packages/vscode-extension/src/extension.ts, packages/vscode-extension/src/panels/LaunchConfigController.ts, packages/vscode-extension/src/plugins/redux-devtools-plugin/redux-devtools-plugin.ts, packages/vscode-extension/src/project/devtools.ts, packages/vscode-extension/src/project/tools.ts, packages/vscode-extension/src/utilities/common.test.ts, packages/vscode-extension/src/utilities/platform.ts, packages/vscode-extension/src/utilities/sdkmanager.ts, packages/vscode-extension/src/utilities/utils.ts, packages/vscode-extension/src/webview/components/Feedback.tsx, packages/vscode-extension/src/webview/components/IconButtonWithOptions.tsx, packages/vscode-extension/src/webview/components/Preview.tsx, packages/vscode-extension/src/webview/components/UrlSelect.tsx, packages/vscode-extension/src/webview/components/shared/SearchSelect.tsx, packages/vscode-extension/src/webview/providers/DependenciesProvider.tsx
After updating dependencies in #1107 we changed eslint config to adapt it to a new version in a way that made lint skip all of the files we had in the codebase and effectively we stopped running lint altogether.
This PR restores the lint to run. Since the defaults changed, we are now changing the behaviors of some rules that are specifically annoying but also updating code to reflect rules that are important.
1. Run lint, see it passes
2. Test critical changes, specifically in `waitForEmulatorOnline`
=> Make lint properly run and fix accumulated errors

packages/vscode-extension/src/webview/components/UrlBar.tsx, packages/vscode-extension/src/webview/components/UrlSelect.css, packages/vscode-extension/src/webview/components/UrlSelect.tsx
This PR fixes bugs caused mainly by the application path bar being always enabled, even if Expo Router was not present:
- the input field was active, so the user could input a route and send it to a nonexistent handler, resulting in a hidden error and the app not navigating anywhere, but changing the displayed path;
- the bar did not have any routes to present, but the dropdown could be opened, resulting in broken layout;
- there was no `/` route on the list, so users couldn't intuitively navigate to the homepage with the bar;
- paths not starting with `"/"` were displayed with id instead of name, resulting in unreadable preview paths.
If Expo Router is not used:
- disable the UrlSelect if the path history doesn't exist;
- make the bar's field read-only;
- create a simpler route list …
=> Fix UrlSelect behavior when Expo Router is not used

packages/vscode-extension/src/builders/buildAndroid.ts, packages/vscode-extension/src/builders/buildIOS.ts, packages/vscode-extension/src/dependency/DependencyManager.ts
After #1068, the build error alerts display the error messages of the exceptions thrown while starting the app.
This resulted in the IDE showing non-user-friendly messages to the user.
This PR wraps some of these errors with user-friendly messages redirecting the user to the logs for details.
- break the native code (`ios`/`android` directory) in order to cause a build error
- verify the message redirects you to the build logs to check for details
- break your node install and restart the IDE
- verify the error message when installing node modules redirects you to the Radon logs
=> improve build error alert messages

packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/project/deviceSession.ts
This PR extracts some code changes from #1154 that can be landed separately and improves the codebase regardless.
We've recently struggled with an error that was caused because of the session management is very complex right now. As a consequence, we'd end up getting a multiple debug sessions opened and sticking around in the debug console.
This PR updates the DebugSession code, such that we always guard against the sessions being started in parallel. What would happen before, is that from two different places, we'd request the debug session to start. We'd typically store the debug session in a member variable, that the assignment is only done after await. So, when another call happens before the session is assigned to variable, we don't detect that and the newly created session would …
=> Safeguard agains debug sessions started in parallel

packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts, packages/vscode-extension/src/devices/DeviceBase.ts, packages/vscode-extension/src/devices/IosSimulatorDevice.ts, packages/vscode-extension/src/devices/preview.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/utilities/diffing.ts
This PR extracts fragments of the changes made in #1154 that simplifies the management of device settings.
Before, we'd store settings in device session which is already a pretty complex class with a dozen of different responsibilities. Eventually, the device settings need to be passed to individual device, so I figured it'd be simpler to move them there avoiding extra logic to be held in the session.
This PR refactors the code such that we move the responsibility of managing the device settings onto the base device class that android and iOS device subclesses inherit. This allows the subclasses to access settings when needed as protected class member. The base class also handles the settings that apply only to the preview which is managed by the base device class already (like replays or …
=> Simplify settings management by moving it out of device session manager

packages/vscode-extension/src/common/LaunchConfig.ts, packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/panels/LaunchConfigController.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/utilities/extensionContext.ts, packages/vscode-extension/src/webview/components/AppRootSelect.css, packages/vscode-extension/src/webview/components/AppRootSelect.tsx, packages/vscode-extension/src/webview/components/DeviceSelect.css, packages/vscode-extension/src/webview/components/DeviceSelect.tsx, packages/vscode-extension/src/webview/components/shared/RichSelectItem.css, packages/vscode-extension/src/webview/components/shared/RichSelectItem.tsx, packages/vscode-extension/src/webview/providers/LaunchConfigProvider.tsx, packages/vscode-extension/src/webview/providers/ProjectProvider.tsx, packages/vscode-extension/src/webview/views/LaunchConfigurationView.tsx, packages/vscode-extension/src/webview/views/PreviewView.tsx
Adds a dropdown to the main Preview screen which allows the user to quickly switch between applications in a monorepo as well as see at a glance which app root is selected.
- sometimes after switching the AppRoot, a "Couldn't start selected device" error appears. This doesn't prevent the app to build and run correctly (and after it does, Radon will stop showing the error and work normally), so it seems to be an issue with error handling in device startup.
- open a monorepo or a folder containing multiple RN apps
- the half-pill button next to the device picker should display the name of the current application
- press the button
- the dropdown should contain all the RN apps in the workspace
- selecting an entry should switch Radon to that app
=> Add approot select to Preview

packages/vscode-extension/src/webview/components/AppRootSelect.css, packages/vscode-extension/src/webview/components/DeviceSelect.css, packages/vscode-extension/src/webview/components/shared/RichSelectItem.css, packages/vscode-extension/src/webview/views/PreviewView.css, packages/vscode-extension/src/webview/views/PreviewView.tsx
This PR updates the style of app and device switcher to look a bit better in my opinion.
Before the buttons would only be rounded on one side with a gap in between. This looked a bit weird as you don't typically expect buttons to only be rounded on one side and not the other. This might've resembled the zoom switcher but that one doesn't have gaps.
Also, the highlighted version blends too much with the background, and the "opened" menu has a flat bottom without rounded corners which also look a bit off.
What we're changing here:
1) Both buttons are now in a single container with background and rounded corners
2) In between the buttons we placed a chevron icon
3) We're changing the highlight effect to be fully enclosed within the group background
4) The menu now is rounded from all the …
=> Make app and device seletor look prettier

packages/vscode-extension/src/project/deviceSession.ts
This PR fixes stage progress updates after #1154 
1) We're resetting stageProgress to undefined as it is only expected to be set for stages that can actually report progress (build and bundle)
2) We're resetting stale build cache flag when restarting the device
3) We're only updating stale build cache flag when in running state to prevent accidental reports when build is ongoing and modifies files inside the build folder.
1. Run app
2. Use "clean build" option
3. See the progress is only reported in build and bundle phases and there's no "0%" progress reported elsewhere
4. Make sure that the stale build dialog doesn't pop up when in build process
5. Add some dummy line to podfile and see the stale build dialog appear
6. Use restart button from the dialog
7. It should be gone immediately …
=> Fix build stage state updates

packages/vscode-extension/src/debugging/RadonCDPProxyDelegate.ts
This PR updates the Proxy Debug Adapter such that it considers the skipFiles setting when filtering the stack frame for console logs.
This fixes an issue when using Radon Connect which doesn't override the built-in console log method in a way that'd provide accurate stack frames. For the main IDE panel experience, we append the extra frame data to the log calls and the extract them in the code that handles console logging. Then we use that to strip out the frame from the framework code that supports logging.
With Radon connect we don't have that, and all logs just appear with lines from withing the framework code which isn't super helpful. To fix this, we use skip files to filter the log call frame. This code is universal enough that we should use it in all the configuration hence no …
=> Use skip files for logs in radon connect

packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/webview/components/Preview.tsx
Fixes a small oversight in #1154  causing the debugger overlay to never appear.
- open an app
- set a breakpoint
- trigger the breakpoint
- verify the "Paused in debugger" overlay with debugger controls appears
=> Fix debugger overlay not showing when the debugger pauses

packages/vscode-extension/src/webview/views/PreviewView.css, packages/vscode-extension/src/webview/views/PreviewView.tsx
This PR uses media query to control text on "Activate License" button. On narrow panels where there's not enough space we will show just "Activate" text instead.
https://github.com/user-attachments/assets/034250d3-0bce-4ba2-8dbf-0c7d1647cc37
1. Run any app, change size of the panel to see the button text update at certain threshold
=> Shorten activate license button text on narrow screens

packages/vscode-extension/src/common/DeviceSessionsManager.ts, packages/vscode-extension/src/project/DeviceSessionsManager.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/utilities/packageManager.ts
After #1154 `ensureDependenciesAndNodeVersion` was not passed into device session, this PR changes that and restores the functionality it provided. 
Additionally investigation into #1163 revealed a problem withhoisted pnpm monorepos namely dependencies installed directly in `node_modules` and not in `node_modules/.pnpm` are reported as `unsavedDependencies` by `pnpm ls` command, which caused us to reinstall pnpm every time, potentially causing problems with the set up. 
The changes made to the `isPnpmModulesInstalled` function change the assumption that `node_modules` are installed only if `dependencies` are detected and also allow `unsavedDependencies`  which prevents unnecessary  installs in hoisted setups. 
- run `expo-52` template application in pnpm monorepo, with …
=> Fix and restore ensureDependenciesAndNodeVersion functionality 

packages/vscode-extension/src/webview/components/ReplayOverlay.css, packages/vscode-extension/src/webview/styles/theme.css
The background overlay for Replay feature was hardcoded and didn't adjust to the currently selected vscode theme.
This PR makes the background color aligned to the current vscode theme. Also, fixed the length selector background color. 
https://github.com/user-attachments/assets/d799b5d6-85d3-44ad-9c23-ecaa979a0c58
https://github.com/user-attachments/assets/24b6b4cc-cf0a-46e9-a899-068cb1b2450c
=> Fix replay overlay styles

packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts
This PR fixes an issue with android emulator reloading every time, because of `adb shell settings get system system_locales` returning "null" as string. 
We didn't notice this before because it seems it happens only on some android versions.
run `react-native-77` and change settings on android
=> Fix settings changes causing reloads unnecessarily on android

packages/vscode-extension/src/network/App.tsx, packages/vscode-extension/src/network/components/NetworkRequestLog.tsx
This PR fixes two visual issues in the network panel:
1) When network panel is just opened, the content isn't scrollable until you resize the panel pane
2) When hovering over the requests lists, we'd get the column bar appearing and disappearing
The first issue is fixed by triggering the resize change on component mount.
The second issue is fixed by adding `bordered-columns` prop to `VscodeTable` component. Apparently, this option is require for `resizable` tables, as otherwise the columns only appear when you try to "resize" them which is when you hover. It look better when the columns are shown at all times in that case.
1. Open network panel
2. Make it show a bunch of requests, make sure you can scroll the payload window w/o previously resizing the editor window or the panel pane
3. …
=> Fix network panel scroll on start and blinking column borders

packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts
Fixes an issue where the CPU Profiler would not display the file saving dialog or display the profile file after profiling was finished.
- open an app in Radon
- start the CPU Profiler
- stop the CPU Profiler
- the file saving dialog should pop up
- after saving the profile file, it should be opened by vscode
=> Fix CPU profiler not showing the profile after finishing

packages/vscode-extension/src/webview/components/AppRootSelect.css, packages/vscode-extension/src/webview/components/AppRootSelect.tsx
Adds a label to select dropdown to match the look from device select dropdown. Also, the dropdown w/o any label look very "mysterious" for projects where only one option is available.
1. Open project select dropdown
**Before**
**After**
=> Add label to approot select dropdown

packages/vscode-extension/lib/plugins/react-query-devtools.js, packages/vscode-extension/src/plugins/react-query-devtools-plugin/ReactQueryDevToolsPluginWebviewProvider.ts
React Query plugin only sends and receives communication when the webview panel is opened. Sometimes when working with the app, we only open the query plugin at some later point in time. This lands us in a situation where we start with an empty panel despite the fact the queries have run in our app for a while.
The plugin currently works by having a proxy client that sends all the updates to another client that works within the webview panel. However, we only send updates made after the webview client is initialized. In this PR we're adding a new "init" event that lets the runtime know when the webview is ready, such that runtime can feed previous queries making the plugin start in a pre-initialized state.
1. Run app with react query plugin
2. Enable react query plugin
3. Reload app but …
=> Send and handle init event for react query plugin

packages/vscode-extension/src/project/project.ts
Currently, any changes to the `launch.json` file cause the application to be reloaded when no custom `appRoot` is set in the config.
This is caused by the launch config change listener to always setup a new app root which causes the `DeviceSessionManager` to be disposed, even if the app root didn't actually change.
This PR changes that behavior to instead check if the actual app root changed and only reset in that case.
- open a project without an `appRoot` specified in `launch.json`
- change the contents of `launch.json`
- the application should not restart
=> Fix launch config changes reloading the application

packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/webview/components/DelayedFastRefreshIndicator.tsx, packages/vscode-extension/src/webview/components/Preview.tsx
Refactors the "refreshing" project state from a separate project status to a boolean flag in device session state and hides the refreshing indicator when the preview is not displayed.
- open an app
- start a fast refresh
- verify the fast refresh indicator is shown and hidden as expected
- verify the fast refresh indicator doesn't appear when installing pods/dependencies or installing the app while the app is still loading
=> Refactor "refreshing" from project status to boolean flag

packages/vscode-extension/lib/react_devtools_agent.js
The refactor in #1180 included a typo which prevented the bridge from initializing correctly on iOS.
This PR fixes that.
=> Fix devtools bridge setup on iOS

packages/vscode-extension/lib/expo_router_helpers.js, packages/vscode-extension/lib/expo_router_plugin.js, packages/vscode-extension/lib/expo_router_v2_plugin.js, packages/vscode-extension/lib/expo_router_v5_plugin.js
This PR enhances the readability of displayed dynamic paths by removing all params already present in the route URL from the query (from after the `?` sign). This way, the values won't be passed twice, significantly shortening the path string.
Before:
After:
1. Open an Expo Router project
2. Navigate to a dynamic route - params should now only be present inside the actual path
3. Navigate to a "not-found" route or a static route that accepts query params - normal params are still displayed in the route name
=> Fix dynamic route params duplicating as query params in route displayNames

packages/vscode-extension/lib/expo_router_helpers.js
This PR fixes an issue with the "go home" button on Expo Router apps, caused by the first `navigationChanged` event with path `"/"` not being sent, leading to the home button setting the first route opened from `/` as its target instead of the root path.
This definitely resolves #1213, with the rest of the fix being already merged in PR #1211.
1. Open an Expo Router app
2. Navigate to any non-root route
3. Press the home button - it should navigate back to `/`
=> Fix incorrect home button target

packages/vscode-extension/src/network/components/PayloadTab.tsx
Currently, if a request with a malformed URL is made, the Network Inspector will crash when you try to open the request details.
This PR safeguards against that.
Fixes #1215
- open the network inspector
- make a request to an invalid URL
- open the details of the request
- don't crash :)
=> fix Network Inspector crash caused by invalid request URLs

packages/vscode-extension/src/dependency/DependencyManager.ts, packages/vscode-extension/src/project/ApplicationContext.ts, packages/vscode-extension/src/project/project.ts
This PR changes the `DependencyManager` class to support changing the `appRootFolder` without recreating the instance, fixing the problem where the webview didn't notice dependency changes when switching between apps in monorepos.
This caused bugs with navigation and with UI elements relying on certain dependencies' availability, incorrect results on the "Run diagnostics" screen, and probably more issues we haven't discovered yet.
Check if the discovered bugs were fixed:
1. Open a folder with more than one React Native app, e.g. [radon-ide-test-apps](https://github.com/software-mansion-labs/radon-ide-test-apps)
2. Launch the IDE panel and open an app with Expo Router - the navigation bar has full functionality, and the Diagnostics screen shows Expo/Router is available
3. Change the app to …
=> Fix dependency checks for multi-app projects

packages/vscode-extension/src/common/DeviceSessionsManager.ts, packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/project/DeviceSessionsManager.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/DeviceSelect.tsx, packages/vscode-extension/src/webview/components/DeviceSettingsDropdown.tsx, packages/vscode-extension/src/webview/components/Preview.tsx, packages/vscode-extension/src/webview/components/PreviewLoader.tsx, packages/vscode-extension/src/webview/components/RenderOutlinesOverlay.tsx, packages/vscode-extension/src/webview/components/ToolsDropdown.tsx, packages/vscode-extension/src/webview/components/UrlBar.tsx, packages/vscode-extension/src/webview/components/UrlSelect.tsx, packages/vscode-extension/src/webview/hooks/useBuildErrorAlert.tsx, packages/vscode-extension/src/webview/providers/ProjectProvider.tsx, packages/vscode-extension/src/webview/views/ManageDevicesView.tsx, packages/vscode-extension/src/webview/views/PreviewView.tsx
Refactors project state to store the information about all currently running device sessions in ProjectState. This refactor is necessary to implement running multiple devices simultaneously. 
- verify there are no regressions:
- try switching between devices
- try adding/removing devices
- try removing the running device
- try renaming devices
- to test that multiple device sessions are correctly reported, pass `preservePreviousDevice` to `startOrActivateSessionForDevice` and log the project state to check all sessions are present
=> Refactor device session management in project state

packages/vscode-extension/src/project/deviceSession.ts
This PR solves an issue with with webview showing crashed preview state in the following scenario: 
1) run application 
2) when on "waiting for an app to load" screen click on the device to show preview
3) when app loads use restart option for example "clean metro cache" 
4) now you should see crashed preview 
this was happening because we changed the device status only when the build started and not limitedly after restart this pr fixes that 
run reproduction steps on `expo-53`
=> Fix webview showing crashed preview

packages/vscode-extension/lib/JSXRuntime/react-native-80/Readme.md, packages/vscode-extension/lib/JSXRuntime/react-native-80/react-jsx-dev-runtime.development.js, packages/vscode-extension/lib/babel_plugins/build-plugin-warn-on-deep-imports.js, packages/vscode-extension/lib/babel_transformer.js, packages/vscode-extension/lib/rn-internals/rn-internals-0.80.js, packages/vscode-extension/lib/rn-renderer/react-native-80/ReactFabric-dev.js, packages/vscode-extension/lib/rn-renderer/react-native-80/ReactNativeRenderer-dev.js, packages/vscode-extension/lib/rn-renderer/react-native-80/Readme.md, packages/vscode-extension/lib/runtime.js
This PR adds a support for react native 80 by doing following things: 
1) Update React version support to 19.1, this requires rebuilding renderers and `jsx-runtime` from [this commit](https://github.com/software-mansion-labs/react-radon-ide/commit/0ab8b16ddd2892b8e8dafc10475900dfb5966a4e)
2) change the source of `AppRegistry` core component 
3) initialize `parseErrorStack` before it is passed into the consoleWrapper to avoid infinite loops 
4) override the `warn-on-deep-imports` babel plugin that was added into the RN 80 to warn users that deep inports from react native are deprecated, as the warnings seem useful we don't want to remove them completely with https://reactnative.dev/blog/2025/06/12/moving-towards-a-stable-javascript-api, so we create our onw plug in that ignores any imports …
=> Support for react native 80 

packages/vscode-extension/src/project/DeviceSessionsManager.ts
Previously we saved the last selected session when we started a device instead of when switching. After #1231 this means the device that launches after restarting the IDE might be different from the one that was last shown.
This PR changes the behaviour to instead save the last selected device whenever a device is selected.
- launch Radon with "Shut down devices when switching" turned off
- start a device
- start a second device
- switch back to the first device
- restart Radon
- the first device should start automatically (previously, the second device would)
=> fix last selected session saved incorrectly workspace state

packages/docs/docs/guides/keyboard-shortcuts.md, packages/vscode-extension/package.json, packages/vscode-extension/src/debugging/ProxyDebugAdapter.ts, packages/vscode-extension/src/project/DeviceSessionsManager.ts
Adds vscode commands and keyboard shortcuts for quickly switching between running devices.
- "Cmd + Shift + ]" switches to the next running device
- "Cmd + Shift + [" switches to the previous running device
- holding the shortcut causes the devices to be switched rapidly, extra debug consoles appear (#1254)
- open a project in radon
- launch multiple devices at the same time
- check the keyboard shortcuts work
=> add keyboard shortcuts for quickly switching running devices

packages/vscode-extension/src/extension.ts, packages/vscode-extension/src/project/ApplicationContext.ts, packages/vscode-extension/src/project/DeviceSessionsManager.ts
Fixes a bug introduced in #1247 caused by registering vscode commands multiple times (in the ctor of `DeviceSessionsManager`, which is not a singleton) which broke the AppRoot switcher and broke the IDE tab when closing and reopening
- just switch an app
- or reopen the radon tab
=> fix command registration causing the IDE to not reopen correctly

packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/webview/components/DeviceRemovalConfirmation.tsx
- Stops the device session when removing a device through the UI.
- cancels ongoing actions when `dispose` is called on `DeviceSession`
It should fix errors being reported by tools (`adb`, `simctl` etc.) called by the `DeviceSession` when a running device is removed.
- open Radon
- start app on iPhone simulator
- wait for the "Installing..." step
- remove the selected device
- don't get an error
=> stop device session before removing the device

packages/vscode-extension/src/project/bridge.ts, packages/vscode-extension/src/project/deviceSession.ts
This PR fixes an issue introduces after abstracting inspector bridge interface in #1180. In this PR we moved on from `addListener` `removeListener` pattern to `disposable` one. The new implementation assumed that the listeners array for one event would not change when they were called, which caused some of the listeners to be ignored if the ones defined before them were removed before the end of the iteration. 
This caused problems with `waitForAppReady` promisees not being resolved which caused debbuger not attaching and the problem with Reloading the ide. 
I run the following reproduction steps on `expo-53` test app:
- run app 
- cause bundle error 
- click on realod button a few times 
- fix the bundle error 
- reload 
- use "Reboot IDE" option
=> Fix Radon showing dead preview after bundle error and "Reload IDE"

packages/docs/docs/getting-started/compatibility.md
Radon IDE 1.8 added support for React Native 0.80. This PR updates the compatibility table to reflect this change.
=> docs: update compatibility table for React Native versions

packages/vscode-extension/src/builders/BatchingBuildManager.test.ts, packages/vscode-extension/src/builders/BatchingBuildManager.ts, packages/vscode-extension/src/builders/BuildManager.ts, packages/vscode-extension/src/project/ApplicationContext.ts, packages/vscode-extension/src/project/deviceSession.ts
After #1118 we encounter an issue where, if two devices (with the same platform) are launched at the same time, and we need to build the native application, both will start building at the same time. This causes issues (at least on iOS, running `xcodebuild` from the same project concurrently causes errors in one of the builds) as well as is simply wasteful (since the application build can be used for both devices anyway).
This PR introduces a "batching" mechanism, where if a device requests an application build while a compatible build is already running, it will use the result of that in-progress build instead.
- open an app (which builds the native part locally) in Radon
- choose the "Clean rebuild" option to force a build
- start a second device with the same platform
- check that the …
=> Prevent running the same build concurrently

packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts, packages/vscode-extension/src/utilities/retry.ts
When trying to call `adb` on a newly created Android emulator, it sometimes fails with "device not found" error.
This can cause Radon to be stuck in the "Booting device" state until the device is restarted by the user, due to an `adb` call made in `waitForEmulatorOnline`.
This PR tries to work around the issue by retrying the command until a timeout is reached.
It also throws an error if the `waitForEmulatorOnline` call fails, instead of getting stuck in "Booting Device".
- create a new Android device and select it immediately
- wait for the device to start
- on main branch, the preview will be stuck at "Booting device" and you can see
```
[error] Error: Command failed with exit code 255: adb -s emulator-5556 wait-for-device shell while [[ -z $(getprop sys.boot_completed) ]]; do sleep …
```
=> Fix new Android emulators getting stuck in "booting" state

packages/vscode-extension/src/builders/BuildCache.ts, packages/vscode-extension/src/builders/BuildManager.ts, packages/vscode-extension/src/builders/customBuild.ts, packages/vscode-extension/src/common/BuildConfig.ts, packages/vscode-extension/src/project/ApplicationContext.ts, packages/vscode-extension/src/project/DeviceSessionsManager.ts, packages/vscode-extension/src/project/FingerprintProvider.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts
Makes the `BuildCache` class independent from `LaunchConfig`.
- calls to `BuildCache`'s methods now require passing either `appRoot` or `FingerprintOptions` which include the options previously retrieved from `LaunchConfig`.
- the "build cache stale" listener has been moved from `BuildCache` to `DeviceSession`. 
- fingerprint calculations are now batched, so that when multiple callers try to get the fingerprint while no changes to the project where made, they will get the result of the same calculation
Motivation:
- batch and cache fingerprint calculations to save time on unnecessary computations
- make `BuildCache` independent from `launchConfig` to allow for having multiple launch configs in the future
- launch the app
- verify it grabs the build from cache
- change something that …
=> Make BuildCache independent from `LaunchConfig`, batch fingerprint calculations when workspace doesn't change

packages/vscode-extension/src/extension.ts
Current `uncaughtError` handling captures errors, which are unrelated to `Radon IDE`.
As a result, errors coming from unrelated extensions like `gitlens` or `copilot` are causing `Radon IDE` output panel to open, despite no errors being encountered by `Radon IDE` itself.
This PR prevents the panel from opening automatically on production builds of `Radon IDE`. 
Fixes #1292
- Have `copilot` extension installed (this extension consistently throws `uncaughtError` on my and @robertherber's setups)
- The `Radon IDE` output panel no longer automatically opens on IDE startup due to errors in `gitlens` and `copilot`.
=> Prevent error panel from opening in production builds 

packages/docs/src/theme/Navbar/index.js
This PR adds a cookie consent banner handled by CookieScript - a cookie management system which we already using on the app.js and rtc.on websites. 
The cookie banner will be placed on the bottom-right corner and look accordingly:
It's possible to adjust the banner styles & content from the CookieScript dashboard.
When you close the banner it's still visible with a cookie icon but it's not disturbing
=> docs: add cookie consent banner

packages/vscode-extension/package.json
Removes the duplicate "Radon IDE" entry from the vscode debuggers suggestions.
Updates the deprecation message for `react-native-ide` debugger type.
Updates the configuration attributes for `react-native-ide` debugger type to match `radon-ide`
- open a project without a `launch.json` file
- go to "Run and Debug" menu
- press "Start debugging"
- the drop-down with available debuggers should include a single "Radon IDE" entry
=> remove the legacy "react-native-ide" launch config

packages/vscode-extension/src/webview/components/Preview.tsx
Fixes #1319 
The issue was caused by Shift being pressed while Radon had focus (being a part of keyboard shortcuts for DevTools and video recording), but depressed once focus switched away from Radon, causing the `isPanning` state to be stuck set to `true` until the shift key was pressed again.
- open an app in radon ide
- start multitouch by holding Alt/Option
- open the vscode command palette by pressing Ctrl/Cmd + Shift + P
- close the command palette and move the mouse
- the multitouch anchor should stay in place instead of moving as if the Shift key was held
=> fix multitouch anchor moving if shift is depressed while unfocused

packages/vscode-extension/src/project/launchConfigurationsManager.ts, packages/vscode-extension/src/project/project.ts
Restores the last used launch configuration on start.
The implementation checks if the last used config is still configured, and if not, falls back to the first config on the list.
- open a workspace
- add two (or more) launch configs
- select any custom config
- close and reopen the IDE
- the same config should be selected
=> Restore last used launch config on IDE start

packages/vscode-extension/src/builders/BuildManager.test.ts, packages/vscode-extension/src/common/LaunchConfig.ts, packages/vscode-extension/src/project/launchConfigurationsManager.ts, packages/vscode-extension/src/webview/components/AppRootSelect.tsx, packages/vscode-extension/src/webview/providers/ProjectProvider.tsx
Displays an alert when the currently selected custom config is removed from the `launch.json` file, either because the file is edited by hand, or through the "Delete" option in the UI.
- add a custom launch configuration and select it
- verify that removing it in various ways makes the alert appear:
- remove it via UI (launch config select -> gear icon -> "Delete" button in modal)
- remove it from the `launch.json` file manually
- change it in the `launch.json` file manually
- verify the alert can be dismissed with the "close" button
=> Add warning when the currently selected custom config is removed

packages/vscode-extension/src/webview/components/AppRootSelect.tsx
Fixes the "Unknown Launch Configuration" alert being briefly shown while the IDE starts.
- start Radon with a custom config set up
- the alert should not appear while the IDE is initializing
=> hotfix: unknown configuration alert shown during project initialization

packages/vscode-extension/src/webview/views/PreviewView.tsx
Fixes the Reload button being disabled while starting the device / app. This was introduced in #1314 
- open app in Radon
- verify you can restart the app while it's still building
=> fix: reload button disabled while starting

packages/vscode-extension/package.json, packages/vscode-extension/src/ai/chat/index.ts, packages/vscode-extension/src/extension.ts
This PR adds an option to disable radon ai functionality.
- run any repository 
- check if chat participant is working 
- disable radon ai 
- reload window 
- check the chat participant response 
the documentation is updated in #1357
=> add: option to disable radon ai

packages/vscode-extension/src/project/OutputChannelRegistry.ts, packages/vscode-extension/src/project/project.ts
- fixes a bug where the output channel for Logger would be disposed with IDE, causing issues when the IDE panel is closed and reopened
- fixes a bug where the DeviceSessionsManager would not be cleaned up when the IDE is disposed
- open the IDE panel
- close it
- reopen it
- the IDE should work
=> fix: Logger output channel is disposed when panel closes, DeviceSessionsManager is not disposed correctly

packages/vscode-extension/lib/wrapper.js, packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/webview/components/Preview.tsx
Fixes #980
- open a project which uses the Paper (old) renderer in Radon
- render the C component:
```tsx
function C() {
return (
<React.Fragment>
<B />
<A />
</React.Fragment>
);
}
function A() {
return <View style={{ height: 100, backgroundColor: "red" }} />;
}
function B() {
return null;
}
```
- right click the red `View`
- element inspector should show the element stack with `<View>,  <A>, <C>` components
=> fix: element inspector not working with Fragments wrapping empty components on Paper

packages/vscode-extension/package-lock.json, packages/vscode-extension/package.json, packages/vscode-extension/src/builders/BuildCache.ts, packages/vscode-extension/src/project/ApplicationContext.ts
Loads the environment variables for the application root using `@expo/env` and appends it to the system and configured environment that is passed to the other parts of the extension.
Also changes the build cache key to use a hash of the environment, instead of the full stringified env.
Closes #1350 
- check that adding a `.env` file in the app root folder results in the variables being added to the `ApplicationContext.launchConfig` object
- check that `.env` contents don't override values set in the system or custom launch config
- check that switching app roots doesn't carry over the variables loaded from the previously chosen approot
=> feat: load environment variables from project`s dotenv files

packages/vscode-extension/src/panels/AppRootConfigController.ts, packages/vscode-extension/src/project/launchConfigurationsManager.ts, packages/vscode-extension/src/utilities/getAvailableApplicationRoots.ts
This PR fixes an issue with detected launch configuration never being used as initial launch configuration. 
This was caused by the initial config detector always checking if the saved configuration is still present in the custom configurations list even if the configuration wan never part of that list. 
To fix that we first check if the configurations kind is `Detected` and if it is and the selected appRoot still exists we select it.
- run `radon-ide-test-apps` directory 
- select one of the detected configs 
- turn of vscode 
- turn it back on and check if the above config is the new initial config
Internal fix
=> fix: saving initial launch configuration when it's detected

packages/vscode-extension/src/connect/ConnectSession.ts, packages/vscode-extension/src/debugging/CDPDebugAdapter.ts, packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/debugging/ProxyDebugAdapter.ts, packages/vscode-extension/src/debugging/ReconnectingDebugSession.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/metro.ts
Closes #1368
- open an app in Radon
- close the application through the device's App Switcher
- open the application from the device's system launcher
- check that the debugger connects automatically to the application
- open an app which uses Expo Go
- reload JS
- verify that the debugger still works correctly (e.g. by triggering a breakpoint)
=> feat: automatically reconnect debugger when application is closed and reopened

packages/vscode-extension/src/common/DeviceSessionsManager.ts, packages/vscode-extension/src/project/DeviceSessionsManager.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/webview/components/UrlBar.tsx
- Adds a "Restart Metro server" reload action to the restart dropdown
- No longer restarts the whole device for metro restart actions
Closes #1369 
- open `expo-52-prebuilt` test app
- check that both "Restart Metro" and "Clear Metro cache" options work
- check that Redux / React Query devtools work after restarting metro this way
=> feat: add "Restart Metro" reload action

packages/vscode-extension/src/webview/components/PreviewLoader.tsx
** Description **
When the projects builds for the first time, especially in the case of Android devices, the troubleshooting options during loading appear right before the app successfully launches. Described in Issue #1374.
This PR  increases the time needed for troubleshooting options to appear to 17 seconds during WaitingForAppToLoad phase in PreviewLoader.
Internal change - tested by running the IDE
=> Update timeout for troubleshooting options

packages/vscode-extension/src/webview/components/RenderOutlinesOverlay.tsx
Fixes webview crashes due to invalid use of react hooks in `RenderOutlinesOverlay`.
- open app in Radon
- switch between devices / apps a bunch
- don't crash
=> fix: hooks error in render outlines overlay

packages/vscode-extension/src/project/ApplicationContext.ts
Removes the excessive "loaded environment variables from .env files" logs which currently happen each time anything accesses the project's environment.
- open a project in Radon
- don't get flooded by "loaded environment" logs
=> remove excessive logging when loading dotenv files

packages/vscode-extension/src/panels/WorkspaceConfigController.ts
This PR fixes how we perform the sync with workspace settings.  Before a consecutive fast updates would cause an infinite 
loop of synchronization between `workspaceConfiguration` and our state manager. 
This change checks if the update that comes back is the same as the one just set before updating it. 
Additionally after this change updates that take no effect are not send at all.
- run radon and use `control` +`option` + 0/9 keybinding (rotate the device) in very short succession 
- before this update it would trigger infinite spiral of updates 
internal change
=> fix: workspace state fast updates

packages/vscode-extension/src/webview/components/DeviceSettingsDropdown.tsx
This PR fixes incorrect icon styling in DeviceSettingsDropdown - the "style" parameter now properly uses `option.rotation` instead of `rotation` inside `.map` method.
Visual change, standard IDE setup:
- [ON FIRST RUN] build simulator-server locally as follows:
- in `/packages` run: `git submodule update --init --recursive packages/simulator-server`
- step into simulator-server folder: `cd simulator-server`
- install dependencies as given in README.md and build simulator-server-macos file locally using: `cargo build --release ` 
- step into extension folder: `cd /packages/vscode-extension`
- run: `npm run build:sim-server-debug` or copy built binary from simulator-server into `dist` folder
- run the extension locally using Run and Debug menu -> …
=> fix: correct rotation icons style in DeviceSettingsDropdown

packages/vscode-extension/src/webview/Preview/Device/Device.tsx, packages/vscode-extension/src/webview/components/Preview.css
This PR fixes issue with persistent overflow when device is in portrait mode due to problems with touch-area dimensions. Touch area dimensions have been changed, to not include 7px additional margin on both sides, which has been deemed unnecessary because of current implementation of touch-handling.
- [ON FIRST RUN] build simulator-server locally as follows:
- in `/packages` run: `git submodule update --init --recursive packages/simulator-server`
- step into simulator-server folder: `cd simulator-server`
- install dependencies as given in README.md and build simulator-server-macos file locally using: `cargo build --release ` 
- step into extension folder: `cd …
=> fix: fix touch-area overflow issues

packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/common/State.ts, packages/vscode-extension/src/panels/WorkspaceConfigController.ts, packages/vscode-extension/src/project/ApplicationContext.ts, packages/vscode-extension/src/project/applicationSession.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/Preview.tsx
- moves the implementation of `inspectElementAt` fully to application session (from `Project` and `DeviceSession`)
- changes the API to return a Promise with InspectData instead of accepting a callback
Fixes #1244
- open app in Radon
- verify that the element inspector still works
- verify that after hovering a lot of elements in a short time with the element inspector enabled, you don't see "Too many callbacks in memory! Something is wrong!" warnings in the console logs
=> refactor: cleanup `inspectElementAt` extension-side implementation

packages/vscode-extension/lib/inspector_bridge.js, packages/vscode-extension/lib/react_devtools_agent.js
Fixes runtime errors during JS bundle loading when the `inspectorBridge` is accessed before the DevTools Radon Agent is set up.
Currently, we load the Devtools Radon Agent in `wrapper.js`, which is only loaded when the application first starts and React Native loads the component registered through `AppRegistry.setWrapperComponentProvider`.
However, some of our plugins import `inspectorBridge` directly, but can be loaded before the application runs, during the initial bundle evaluation:
- `react-query-devtools.js` is loaded whenever the `react-query` module is evaluated.
- `expo_dev_plugins.js` is loaded whenever the `redux-devtools-expo-dev-plugin` module is evaluated.
Which causes the `inspectorBridge` to throw an error when checking if the `agent` is already set up, causing the whole …
=> fix: bundle load failing due to agent initalising late

packages/vscode-extension/src/utilities/getMinimumSupportedNodeVersion.ts
This PR changes `getMinimumSupportedNodeVersion` logic to return the most restrictive version instead of the first found one. This Solves an issue with projects that have updated rn version but not the engine requirements in their package.json. 
add a brak point to the `getMinimumSupportedNodeVersion` method run in tin the `react-native-81` test app and check if the return value is 22.14 instead of 18
internal change
=> fix: node version check

packages/vscode-extension/src/webview/views/CreateDeviceView.tsx
This PR hides iOS devices that are not supported by any available runtime. 
add fake iso device to `deviceConstants.ts`: 
```js
{
modelName: "iPhone 16 Pro",
modelId: "com.apple.CoreSimulator.SimDeviceType.iPhone-16-Pro",
platform: DevicePlatform.IOS,
screenWidth: 1178,
screenHeight: 2556,
screenMaskImage: iphone16proscreen,
landscapeScreenMaskImage: iphone16proLandscapeScreen,
bezel: {
type: "mask" as const,
width: 1186,
height: 2564,
offsetX: 4,
offsetY: 4,
image: iphone16probezel,
imageLandscape: iphone16proLandscapeBezel,
},
skin: {
type: "skin" as const,
width: 1285,
height: 2663,
offsetX: 55,
offsetY: 55,
image: iphone16pro,
imageLandscape: iphone16proLandscape,
},
},
```
It should not be visible in create new device modal.
=> feat: hide not supported devices

packages/vscode-extension/src/webview/Preview/MediaCanvas.tsx, packages/vscode-extension/src/webview/components/ReplayOverlay.css, packages/vscode-extension/src/webview/components/ReplayUI.css
This PR fixes:
-  issues with replay rotation, after the device has been rotated during the replay using shortcut
- issues with incorrect controls layout caused by z-index (the 5s/10s/30s/Full dropdown)
- [ON FIRST RUN] build simulator-server locally as follows:
- in `/packages` run: `git submodule update --init --recursive packages/simulator-server`
- step into simulator-server folder: `cd simulator-server`
- install dependencies as given in README.md and build simulator-server-macos file locally using: `cargo build --release ` 
- step into extension folder: `cd /packages/vscode-extension`
- run: `npm run build:sim-server-debug` or copy built binary from …
=> fix: replay rotation and controls z-index

packages/vscode-extension/lib/preview.js
In the latest (0.81) React Native version the `SafeAreaView` was deprecated (https://github.com/facebook/react-native/commit/73133a31d5a47e71edd4e6b798184df8045e2234). 
We used it exclusively in Preview functionality and in result of the above changes came to the conclusion that it's usage wasn't even correct, as the user might wan't to test components outside safe area. 
This PR replaces `SafeAreaView` with `View` in the Preview component. 
- run any react native 81 app in radon 
- the first log in the debug console should be: 
```
Running "${application}" with {"rootTag":${ROOT_TAG},"initialProps":${someProps},"fabric":${IS_FABRIC}}
```
note: the deprecation message might pop out any way if your test app use it but it should not come before the above log.
internal change
=> chore: drop SafeAreaView from preview 

packages/vscode-extension/src/builders/BatchingBuildManager.test.ts, packages/vscode-extension/src/builders/BatchingBuildManager.ts
Fixes an omission in the `BatchingBuildManager` which would cause new builds (started by passing the "force clean build" flag) wouldn't cancel ongoing builds, causing two builds for the same configuration to run concurrently.
- added unit test for the scenario which fails on main
=> fix: force-starting a new build doesn't cancel the ongoing build

packages/vscode-extension/src/webview/components/ReplayOverlay.css, packages/vscode-extension/src/webview/components/ReplayOverlay.tsx
This PR makes the Replay feature easier to navigate by adding keyboard controls. 
`Escape` → closes the Replay UI
`Arrow Right` → advances the video preview by one frame
`Arrow Left` → goes back in the video frame by one frame
`Shift + Arrow Right` → advances the video by 10 frames
`Shift + Arrow Left` → goes back by 10 frames
`Space` → stops/starts playback
`CMD + S` / `Ctrl +S` → saves the replay 
Here's a video of me navigating the video with keyboard
https://github.com/user-attachments/assets/38cb2a03-8af1-4d19-991e-39abef175386
=> feat: add replay keyboard controls

packages/vscode-extension/src/panels/Tabpanel.ts
This PR solves an issue introduces by https://github.com/software-mansion/radon-ide/pull/1147. 
when the user changes the location of the IDE from tab to side panel using `user` scope instead of the default `workspace` 
they could find themselves in a illegal state of having radon open in a tab panel when the setting would be set to 
`side-panel`. Then if the user used an option to open IDE panel like `preview` or just `show IDE` command. they would have to panels open at once. 
-run a test app and open radon in tab panel 
- change it to a different app and switch "panel location" setting to side-panel with `user` scope
- return to the first app and it will open in tab panel instead of side panel
internal
=> fix: changing panel location 

packages/docs/package.json, packages/docs/src/hooks/usePosthog.tsx, packages/docs/src/pages/index.tsx, packages/docs/src/pages/legal/subprocessors.mdx, packages/docs/vercel.json, packages/docs/yarn.lock
This PR adds a PostHog integration for future use for A/B experimentation on the landing page.
This also requires changes in rewrites to send requests from our domain to mitigate them being blocked by adblockers.
Here's the tutorial I followed:
https://posthog.com/docs/advanced/proxy/vercel
Also requires changes to subprocessors legal page.
=> docs: add posthog integration

packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts, packages/vscode-extension/src/devices/DeviceBase.ts, packages/vscode-extension/src/devices/IosSimulatorDevice.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/DeviceSettingsDropdown.tsx, packages/vscode-extension/src/webview/components/Preview.tsx, packages/vscode-extension/src/webview/views/PreviewView.tsx
Allows sending files to the selected device via Radon.
- adds a "Send file" option to the device settings dropdown which opens the system file picker to select the file(s) to send
- allows drag-n-dropping files over the preview in order to send them over to the device
UI to be done in a separate PR.
https://github.com/user-attachments/assets/afd426d1-53a0-471d-8dd6-4cb6ab65ddf2
Limitations: 
- currently, only media files are supported on iOS due to issues with the "Files" app not working correctly in Radon Simulators. The default behaviour of the Apple Simulator app when dropping a (non-media) file over the simulator seems to be the same as `simctl openurl file://${path-to-file}` which opens the "Files" app on the device and allows selecting where the file should be saved. However, on the …
=> feat: allow sending files to device

packages/vscode-extension/src/utilities/extensionContext.ts
This PR fixes an issue with app root detection system treating symlinks to files ad directories. 
To avoid similar problems in the future we not only change the guard check from `!....isFilie()` to .`...isDirectory()` but also encapsulate the error in try catch block.   
check is test apps are still working and run this version of radon on the project where the issue happened.
this is an internal change
=> fix: app root detection system

packages/vscode-extension/src/project/ApplicationContext.ts
Currently we include the resolved environment variables in the build cache key in order to invalidate builds when the user changes something in their environment which can impact the build.
However, this causes issues with e.g. the `VSCODE_PID` variable which changes each time vscode is fully closed and restarted, as well as, presumably, similarly "temporary" variables set by the user's environment.
This PR changes that behaviour by only including the env variables configured in the project's `.env` files and Launch Configurations in the `env` record used throughout the code, including the Build Cache.
- open an app in Radon
- add some env variable to the launch config
- add a `.env` file with some env variable set
- verify that changing either causes the app to be built again when …
=> fix: system env variables impacting build caching

packages/vscode-extension/src/project/ApplicationContext.ts
Fixes errors about missing configuration variables being logged by `@expo/env` whenever the env is being resolved.
- start Radon in the extension development host
- verify no errors mentioning "NODE_ENV" are being logged to the debug console
=> fix: suppress warning/errors from @expo/env

packages/vscode-extension/src/devices/IosSimulatorDevice.ts
This PR solves a problem with a new installed application cacheing system, which would throw an error if the application was never installed on the device before. 
- create a new ios device 
- open any non expo go application 
internal change
=> fix: cacheing ios installed applications

packages/vscode-extension/src/network/App.tsx, packages/vscode-extension/src/network/components/NetworkLogDetails.css, packages/vscode-extension/src/network/components/NetworkRequestLog.css, packages/vscode-extension/src/network/components/NetworkRequestLog.tsx
This PR improves network inspector scroll and select behaviour:
- the selected request logs are now highlighted
- the element now does not re-render whenever height changes
- - if log is selected, after resizing the inspector now ensures that it remains visible and scrolls the list accordingly
- fixed issue, where scroll was reset to the top after closing the details window or changed the inspector's height
https://github.com/user-attachments/assets/f08bb04d-bec0-4786-820c-f86bb0c1d304
- run the extension locally using Run and Debug menu -> Run Extension
- open an application supporting Radon IDE in editor - example of app supporting  rotation: …
=> feat: improve network inspector select and scroll behaviour

packages/vscode-extension/package-lock.json, packages/vscode-extension/package.json, packages/vscode-extension/src/builders/BatchingBuildManager.test.ts, packages/vscode-extension/src/builders/BatchingBuildManager.ts, packages/vscode-extension/src/builders/BuildCache.ts, packages/vscode-extension/src/builders/BuildManager.test.ts, packages/vscode-extension/src/builders/BuildManager.ts, packages/vscode-extension/src/builders/buildAndroid.ts, packages/vscode-extension/src/builders/buildIOS.ts, packages/vscode-extension/src/common/BuildConfig.ts, packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/common/State.ts, packages/vscode-extension/src/dependency/ApplicationDependencyManager.ts, packages/vscode-extension/src/dependency/pods.ts, packages/vscode-extension/src/dependency/prebuild.ts, packages/vscode-extension/src/devices/DeviceManager.ts, packages/vscode-extension/src/devices/IosSimulatorDevice.ts, packages/vscode-extension/src/project/ApplicationContext.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/metro.ts, packages/vscode-extension/src/utilities/common.ts, packages/vscode-extension/src/utilities/json.ts, packages/vscode-extension/src/webview/components/Preview.tsx
This PR refactors the build logic to let the build configuration access the device instance. In particular, `xcodebuild` may need to know the device it builds for. But also to address two main flows of the build strategy:
1) The current implementations leaves orphaned entries in the global state. The reason is that the cache key depends on some parameters that can be adjusted by the user and in particular we also changed the key prefix recently when we added support for iPads.
2) We currently use too few parameters for fingerprinting and hence it may happen that we will attempt to reuse a build that should not be reused. In particular, we only use a subset of launch config options while all of them may impact the output of the build process.
To address the above, we are introducing a new …
=> Reactor build to make builds depend on device and also fix cache to rely on device config

packages/vscode-extension/lib/network.js, packages/vscode-extension/lib/polyfills/index.js, packages/vscode-extension/lib/polyfills/third-party/text_decoder.ts, packages/vscode-extension/src/network/components/PayloadTab.tsx, packages/vscode-extension/src/network/components/ResponseTab.css, packages/vscode-extension/src/network/components/ResponseTab.tsx, packages/vscode-extension/src/network/hooks/useNetworkTracker.tsx, packages/vscode-extension/src/network/utils/requestFormatUtils.ts, packages/vscode-extension/submodules-NOTICES.json
This PR fixes issues with Payload Tab in network inspector, which would cause error throws if the payload was not a proper JSON.
It also introduces:
- Refactors made to Payload Tab to be more in style of Response Tab, included *Copy to Clickboard* button as well
- Deserialising data in `Network plugin` for proper showcase of data sent as UInt8Array
- run the extension locally using Run and Debug menu -> Run Extension
- open an application supporting Radon IDE in editor - example of app supporting  rotation: radon-ide-test-apps/react-native-80 
- run Radon IDE extension panel, launch app on selected device, open network inspector
- **check if Payload and Response tabs …
=> fix: network inspector - payload and response tabs

packages/vscode-extension/src/webview/components/InspectOverlay.tsx, packages/vscode-extension/src/webview/components/Preview.tsx, packages/vscode-extension/src/webview/components/RenderOutlinesOverlay.tsx, packages/vscode-extension/src/webview/components/SendFilesOverlay.tsx, packages/vscode-extension/src/webview/components/ToolsDropdown.tsx, packages/vscode-extension/src/webview/hooks/selectedSession.tsx, packages/vscode-extension/src/webview/hooks/useBundleErrorAlert.tsx, packages/vscode-extension/src/webview/utilities/transformAppCoordinates.ts, packages/vscode-extension/src/webview/views/PreviewView.tsx
This PR adds typing to the `useSelectedDeviceSessionState` to take in to account the fact that it can be undefined 
- open app 
- kill the device it was running on 
internal
=> fix: device session can be undefined 

packages/vscode-extension/src/dependency/ApplicationDependencyManager.ts
Currently, the node version check returns a vague information that node is missing or the version is too low. It could be tricky for people to tell especially that the RN project template doesn't contain the node engine requirements and only react-native package.json has.
This PR, adds a better error for this case:
1) when node is not detected at all, we say it is not found in path
2) when node is too low we print the version that Radon detects and the minimum version.
1) change node version with nvm to some old one
2) run any project 
3) see the new error
4) to test the node missing I renamed `node` exec to some different name such that the exec crashes
=> Add actionable error for node version mismatch

packages/vscode-extension/src/project/OutputChannelRegistry.ts, packages/vscode-extension/src/project/project.ts
In  #1386 we accidently broke focusOutput method because we added a `throw` statement whenever the main logger output channel is requested.
This PR fixes that code by:
1) removing the throw statement from output registry. We change the types such that the main logger output type is excluded since it isn't managed by the registry anyway.
2) we add a check in focusOutput method to conditionally call into Logger.openOutputPanel
1) use the output channel button to reveal IDE logs
2) it should work now
=> Fix 'open channel' flow after #1386

packages/vscode-extension/src/connect/ConnectSession.ts, packages/vscode-extension/src/debugging/CDPDebugAdapter.ts, packages/vscode-extension/src/debugging/CDPSession.ts, packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/debugging/ProxyDebugAdapter.ts, packages/vscode-extension/src/debugging/ReconnectingDebugSession.ts, packages/vscode-extension/src/project/devtools.ts
Implements `addBinding` support for the custom JS debugger to allow it to work with Radon Connect and the new RDT-over-CDP implementation when configured.
- add `"useCustomJSDebugger": true` to a launch configuration for an app running RN >=0.76
- open the app in Radon
- verify the app runs and devtools connect
=> feat: implement connect and new devtools for custom debugger

.github/workflows/build-vsix-nightly.yaml
Changes build workflow schedule time to 2:47. 
Have ran automatically on GitHub Actions 
no documentation.
=> feat: change workflow schedule time

.github/workflows/build-vsix-nightly.yaml
Changes files upload in `Build VSIX nightly` workflow.
Tested manually on GitHub Actions.
no documentation.
=> feat: Change files upload in `Build VSIX nightly`

packages/vscode-extension/src/utilities/iosRuntimes.ts
Users who had beta versions of Xcode installed, may end up with multiple iOS runtimes with exact same identifier but different buildversions. Since we only use the identifier for commands that we run (when building or creating devices), it seems sensible to ignore buildversion entirely which is what seems that Xcode is doing already, as multiple runtimes doesn't show up there.
Fixes #1548
1) I already deleted the orphaned runtimes so just tested that this change didn't break the runtime selector from new device modal
2) I updated the code and hardcoded identifier to always be the same, and verified that only one runtime is listed then.
=> Avoid showing multiple runtimes with colliding identifiers

packages/vscode-extension/lib/JSXRuntime/react-native-82/Readme.md, packages/vscode-extension/lib/JSXRuntime/react-native-82/react-jsx-dev-runtime.development.js, packages/vscode-extension/lib/babel_transformer.js, packages/vscode-extension/lib/rn-internals/rn-internals-0.82.js, packages/vscode-extension/lib/rn-renderer/react-native-82/ReactFabric-dev.js, packages/vscode-extension/lib/rn-renderer/react-native-82/ReactNativeRenderer-dev.js, packages/vscode-extension/lib/rn-renderer/react-native-82/Readme.md
This PR adds support for react native 82, by updating the radon specific renderer logic to include the v19.1.1 react patch that react native 82 also includes.
- run new radon native 82 test app. 
- run tests with `vscode-extension-tester` useing command `npm run run-tests-on-VM -- react-native-82`
to be updated
=> feat: support for react native 82

packages/vscode-extension/lib/expo_router_helpers.js
This PR prevents internal expo-router params from being presented in the URL bar.
In expo-router v6 with new native tabs, expo started appending some internal params to the paths in order to control things like screen animations. Those are typically very long and not useful from the user standpoint. After this change we no longer show these params in the URL bar.
Before:
After:
1) Run expo router app with native tabs
2) Switch between tabs
3) Open URL bar and select some of the routes that belong to tabs
4) before this change you'll see params like `__internal_expo_router_no_animation` in the URL bar being appended to some paths, after this change those params are no longer showing there.
=> Filter out internal expo-router params from url bar

packages/vscode-extension/src/webview/components/shared/Modal.tsx
Changes in #1534 caused the close button for modals to move to the bottom-left corner.
This was caused by the css files being loaded in a different order than before, making the rules for `icon-button` class override those for `modal-close-button` class.
Before:
After:
=> fix: the close button for modals appears in bottom-left corner

packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/debugging/ReconnectingDebugSession.ts, packages/vscode-extension/src/project/applicationSession.ts, packages/vscode-extension/src/project/devtools.ts
Fixes an issue where the CDP devtools fail to connect when switching to a running device with broken code, which produces a bundle error.
The bundle error causes the source maps to not load correctly when reconnecting the debugger, which in turn means the `debugSession.onScriptParsed` event is never fired and the devtools server never establishes the connection with the application. 
- launch `react-native-81` test app
- launch 2 devices at the same time
- introduce an error in the code to force a bundle error
- switch to the other running device
- check that the devtools connect
- check that fixing the bundle error closes the error alert
- check that after switching to the other running device, the error alert disappears as well ()
=> fix: switching to a device with bundle error fails to connect devtools

packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/webview/components/Preview.tsx
This solves an issue that could happen if the user forces the preview screen while debugger was enabled, not allowing to continue the debugger in any way. 
This PR also resets the `showPreviewRequested` flag on every status change which makes it go away on reloads. 
- run radon on test commit (c278d25f3a977f5aff5fb4d21e384d1488ea9406) with information about the device session status obscured and check if debugger works correctly 
internal
=> fix: debugger overlay not showing while status not running

packages/vscode-extension/src/debugging/DebugSession.ts, packages/vscode-extension/src/debugging/ReconnectingDebugSession.ts, packages/vscode-extension/src/project/applicationSession.ts, packages/vscode-extension/src/project/devtools.ts
It cause app stucking on `waiting for app to load` step during clean build.
=> Revert: "fix: switching to a device with bundle error fails to connect devtools"

packages/vscode-extension/src/debugging/ProxyDebugAdapter.ts, packages/vscode-extension/src/debugging/RadonCDPProxyDelegate.ts
With some client's apps, we found that very large source maps may crash the wasm based source maps library that we currently use. After investigating, we found that we don't actually need to process source maps at all, and only rely on the vscode-js-debug implementation (with some modifications: https://github.com/software-mansion-labs/vscode-js-debug/pull/8)
1) we used source map to resume breakpoints on skipped files (i.e. in node_modules). This behavior work when skipFiles are provided but only after https://github.com/software-mansion-labs/vscode-js-debug/pull/8 the skipFiles can work reliably well
2) we also used source maps to annotate CPU profile with file location metadata. This is something that vscode-js-debug does already but we just needed to find a way to utilize the built-in …
=> Remove the need to process source maps in extension code

packages/vscode-extension/src/project/ReadableLogOutputChannel.ts
After #1386 the IDE.dispose method started throwing an error that c.dispose is not a function.
The issue was in the "mock" channel introduced in that PR. The code used `as` operator to cast incomplete type into channel, but it was missing a lot of methods (including the dispose method) that some parts of the codebase could use.
This PR adds a complete LogChannel prototype for the mock implementation.
1) Open IDE panel
2) Use the "switch off" button to turn off the panel when in sidebar mode or just close it the tab in the "tab mode"
3) Before this change we'd get an error that c.dispose is not a function, now this error is gone
=> Fix crash on IDE.dispose

.github/workflows/ui-tests.yaml, packages/vscode-extension-tester/package.json, packages/vscode-extension-tester/scripts/run_tests_on_vm.sh
Adds the ability to choose the VS Code version used during tests. You can select the version by providing the appropriate input in GitHub Actions or by setting an environment variable when running tests locally. For example:
`CODE_VERSION=1.99.1 npm run prepare-and-run-tests` 
tested locally and on GitHub Actions.
no documentation required.
=> feat: VSCode version for tests

packages/vscode-extension/src/common/State.ts, packages/vscode-extension/src/project/applicationSession.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/webview/components/UrlBar.tsx
After #1497 we moved the navigation listener setup to "after" the communication with the application is established, which caused the expo router to integration to not capture information about paths existing in the application. 
This PR fixes it by moving the listeners initialization to application session 
- run expo-53 test app
- check out the navigation list 
- navigate 
- go home 
internal
=> fix: expo router integration

packages/vscode-extension/lib/babel_transformer.js, packages/vscode-extension/lib/expo_router/expo_router_helpers.js, packages/vscode-extension/lib/expo_router/expo_router_plugin.js, packages/vscode-extension/lib/expo_router/expo_router_v2_plugin.js, packages/vscode-extension/lib/expo_router/expo_router_v5_plugin.js, packages/vscode-extension/lib/preview.js, packages/vscode-extension/lib/runtime.js, packages/vscode-extension/lib/wrapper.js, packages/vscode-extension/src/common/State.ts, packages/vscode-extension/src/project/bridge.ts, packages/vscode-extension/src/project/deviceSession.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/components/UrlBar.tsx, packages/vscode-extension/src/webview/components/UrlSelect.tsx, packages/vscode-extension/src/webview/components/UrlSelectItem.tsx, packages/vscode-extension/src/webview/components/UrlSelectItemGroup.tsx
This PR changes the logic behind integration with URL bar, back and home buttons in order to address multiple issues that we have:
1) Currently, the back button is completely disabled in non expo-router projects, it still occupies the UI.
2) Home button reloads the app, which just isn't intuitive. On top of that it also leaves the history polluted which also isn't what people expect from the browser.
3) Back button doesn't work when preview is opened (doesn't navigate back)
4) The preview URL is displayed in the URL bar after "home" button gets pressed and despite the app showing the main screen not the preview.
1) We should use the back button to allow for going back from preview mode.
2) Home button should just wind back the navigation stack, and on non-router apps it should reset the …
=> Fix back and home behavior in UrlBar

packages/vscode-extension/src/debugging/ProxyDebugAdapter.ts
In #1580 we changed the attach logic in `ProxyDebugAdapter` such that it waits for the actual JS session to be initialized instead of the wrapper session that vscode-js-debug starts at first.
This revealed another issue under specific conditions:
1) our proxy delegate communicates with the proxy debug adapter in two ways: one is via events triggered by the vscode-js-debug debug adapter (specifically attach request that resolves startDebugging call), but also via the proxy delegate.
2) because of this, proxy delegate calls may come before the debug adapter is attached
3) this can happen because proxy delegate receives the events first and only then forwards them to the vscode-js-debug adapter
4) as a consequence, some code (i.e. in DebugSession) may skip certain events, because it'd …
=> Queue up ProxyDebugAdapter events such that they are never sent before attach is complete

.github/workflows/ui-tests.yaml, packages/vscode-extension-tester/ui-tests/05-networkPanel.test.js
This PR fixes small syntax error that appeared in this [PR](https://github.com/software-mansion/radon-ide/pull/1585/files) in test suit `05-networkPanel`. 
Additionally it adds one more test case that will be run each night (app: `react-native-81`, vscode version: `1.99.1`, all test sets)
Tested locally
No documentation needed
=> fix: fixes bug that appeared in PR #1585

.github/workflows/lint-extension-tester.yaml, .github/workflows/lint-extension.yml, .github/workflows/ui-tests.yaml, packages/vscode-extension-tester/eslint.config.mjs, packages/vscode-extension-tester/package-lock.json, packages/vscode-extension-tester/package.json, packages/vscode-extension-tester/services/appManipulationService.js, packages/vscode-extension-tester/services/helperServices.js, packages/vscode-extension-tester/services/managingDevicesService.js, packages/vscode-extension-tester/services/radonSettingsService.js, packages/vscode-extension-tester/services/radonViewsService.js, packages/vscode-extension-tester/ui-tests/01-smoke.test.js, packages/vscode-extension-tester/ui-tests/02-GUIButtons.test.js, packages/vscode-extension-tester/ui-tests/03-manageDevices.test.js, packages/vscode-extension-tester/ui-tests/05-networkPanel.test.js, packages/vscode-extension-tester/ui-tests/06-screenshots.test.js, packages/vscode-extension-tester/ui-tests/07-radonTools.test.js, packages/vscode-extension-tester/ui-tests/08-deviceSettings.test.js, packages/vscode-extension-tester/ui-tests/09-radonSettings.test.js, packages/vscode-extension-tester/ui-tests/10-expo.test.js, packages/vscode-extension-tester/ui-tests/11-switchingApps.test.js, packages/vscode-extension-tester/ui-tests/setupTest.js
This PR adds to CI Lint checks for the tests directory and fixes the Lint issues found there (mostly imports order).
tested locally by running:
`npm run lint`
No documentation needed
=> feat: Add Lint for tests directory and fix lint issues

packages/vscode-extension/package-lock.json, packages/vscode-extension/src/common/Project.ts, packages/vscode-extension/src/devices/DeviceManager.ts, packages/vscode-extension/src/project/project.ts, packages/vscode-extension/src/webview/views/ManageDevicesView.tsx
This PR forces a reload of available ios/android sytem images when the `ManageDevicesView` so before the user will open `createNewDeviceView` to prevent a scenario in which the user can not choose a runtime that was added while Radon was running. 
- open radon 
- add a new runtime in xcode ( I added 18.4 )
- wait until it is installed and without closing radon open "menage devices" and the "create a new device" 
- try selecting the runtime and check if the new one is on the list  
internal
=> fix: loading of new runtimes 

packages/vscode-extension/src/webview/views/PreviewView.tsx
This removes unused import introduced by #1612 that caused the Pipeline to fail.
=> fix: lint 

packages/vscode-extension/lib/babel_transformer.js, packages/vscode-extension/lib/plugins/react-query-devtools.js
after recent clean up of the `/lib` dir file structure we left some devplugin related imports pointing to the wrong spot. This PR fixes that 
- run expo-52-prebuild-with-plugins test app 
- it works
internal
=> fix: dev plugins 

packages/vscode-extension/lib/babel_transformer.js, packages/vscode-extension/lib/plugins/react-query-devtools.js, packages/vscode-extension/src/debugging/RadonCDPProxyDelegate.ts, packages/vscode-extension/src/project/applicationSession.ts, packages/vscode-extension/src/project/devtools.ts, packages/vscode-extension/src/webview/components/DeviceRenameDialog.tsx, packages/vscode-extension/src/webview/providers/ModalProvider.tsx
After recent changes to the boot up system we had a lot of unhandled exceptions flying on loads and reloads this PR solves the following: 
1) `devdools` initilization failed - we had a los promise that was unhandled 
2) sourceMap parseing failed - turns out source maps can come to us without the sources filed causing us to log unnecessary error.
3) wait for an app to load canceled - because of how the application is initialized we need to set up the `appReadyPromise` before performing actions like `reloadWithDebugger` those actions can fail tho before we would normally await `appReadyPromise` making it reject outside of the try catch scope on the next reload when it was cancelled. 
- run expo 54 test app 
- perform reloads bundle errors and reloads during bundelle errors 
internal
=> fix: unhandled exeptions

packages/vscode-extension/lib/network/network.js, packages/vscode-extension/lib/network/networkRequestParsers.ts, packages/vscode-extension/src/network/components/Tabs/ResponseTab.tsx, packages/vscode-extension/src/network/types/network.ts, packages/vscode-extension/src/plugins/network/network-plugin.ts
This PR fixes problems with Network Inspector elements dependent on header fields (i.e. syntax highlighting not working properly on android).
As it turns out, due to XHRInterceptor implementation differences, headers on IOS are written capitalised (`Content-Type`) and on android in lower case (`content-type`). This caused problems with Syntax Highlighting on android, no other issues have been found.
- [ON FIRST RUN] build simulator-server locally as follows:
- in `/packages` run: `git submodule update --init --recursive packages/simulator-server`
- step into simulator-server folder: `cd simulator-server`
- install dependencies as given in README.md and build …
=> fix: network inspector - android header case convention problems

packages/vscode-extension/src/builders/BuildManager.ts, packages/vscode-extension/src/common/BuildConfig.ts, packages/vscode-extension/src/dependency/ApplicationDependencyManager.ts, packages/vscode-extension/src/project/ApplicationContext.ts
In our recent changes to the prebuild system, we added an automatic detection to check if the project uses `dev-client` and force a prebuild if it does. This however made us ignore the old `usePrebuild` option in such a scenarion not allowing a user to opt in into a manual prebuild by default. 
- run `social-app` 
- set the `usePrebuild` option to false
- after it works reload the whole of radon ide
not different from the 1.11.2
=> feat: make `usePrebuild` option more important then automatic heuristic 
